### ISSUE TITLE
Saml2AuthenticationModule events

### ISSUE THREAD

**Issue by Raschmann** [KentorIT/authservices#109]
Hi, as I'm currently trying to find and test replacement for old solution based on non existing `Saml2AuthenticationModule` from MS, it provides some extensibility through events in this class. Original MS handler had contained same collection of event handlers sames as `WSFederationAuthenticationModule` class: http://msdn.microsoft.com/en-us/library/system.identitymodel.services.wsfederationauthenticationmodule_events(v=vs.110).aspx

Concretely I will need these: `SecurityTokenReceived`, `RedirectToIdentityProvider` and `SignInError`

Will it be possible to provide those event in future release?

**Comment by AndersAbel** [comment]
Callbacks are now supported through the Notifications mechanism.
