### ISSUE TITLE
TestShib compatibility test

### ISSUE THREAD

**Issue by dmarlow** [KentorIT/authservices#113]
I would like to test my SP using http://testshib.org/ to ensure I'm compatible with other IdPs out there. I tried using the following identityProvider:

    <add entityId="http://www.testshib.org/metadata/testshib-providers.xml"
         allowUnsolicitedAuthnResponse="true"
         loadMetadata="true" />

But received an error in runtime: "Unable to cast object of type 'System.IdentityModel.Metadata.EntitiesDescriptor' to type 'System.IdentityModel.Metadata.EntityDescriptor'."

   at Kentor.AuthServices.IdentityProvider.get_ActiveIdentityProviders()
   at Kentor.AuthServices.SignInCommand.CreateResult(EntityId idpEntityId, String returnPath, Uri requestUrl) in Kentor.AuthServices\SignInCommand.cs:line 31
   at Kentor.AuthServices.SignInCommand.Run(HttpRequestData request) in Kentor.AuthServices\SignInCommand.cs:line 22
   at Kentor.AuthServices.Mvc.AuthServicesController.SignIn() in Kentor.AuthServices.Mvc\AuthServicesController.cs:line 20
   at lambda_method(Closure , ControllerBase , Object[] )
...

When I attempt to register the metadata with TestShib, I get an error. https://www.testshib.org/register.html

"The file you are attempting to upload is not valid metadata. Please correct any errors and try again."

Please let me know if I've gone about this the right way.

Thanks!

**Comment by rdefreitas** [comment]
I'm having trouble trying to get AuthServices working with testshib. @dmarlow can you share a snippet from your web.config ?

**Comment by dmarlow** [comment]
It's been a long while since I've messed with it, but here's what I had for my SampleMVCApplication web.config:

```xml
  <kentor.authServices entityId="http://localhost:2181/" 
                       assertionConsumerServiceUrl="http://localhost:2181/AuthServices/Acs" 
                       returnUri="http://localhost:2181/">
    <!--<identityProviders>
      <add entityId="http://stubidp.kentor.se/Metadata" 
           destinationUri="http://stubidp.kentor.se/" 
           allowUnsolicitedAuthnResponse="true" 
           binding="HttpRedirect">
        <signingCertificate fileName="~/App_Data/Kentor.AuthServices.StubIdp.pfx" />
      </add>
      <add entityId="http://www.testshib.org/metadata/testshib-providers.xml"
         allowUnsolicitedAuthnResponse="true"
         loadMetadata="true" />
    </identityProviders>-->
    <federations>
        <add metadataUrl="http://www.testshib.org/metadata/testshib-providers.xml" allowUnsolicitedAuthnResponse="true" />
    </federations>
  </kentor.authServices>
```

Let me know if you need anything else :)

**Comment by rdefreitas** [comment]
assertionConsumerServiceUrl isn't a valid attribute. Had you made any changes to the code?

**Comment by rdefreitas** [comment]
So I removed that attribute (since it was breaking), and I now get the following error after putting credentials into testshib:

> The Saml2Response must have status success to extract claims.

**Comment by dmarlow** [comment]
Sorry, it's been a while. I don't think I changed anything in code related to that. I know a lot has changed within the project since I last used it and my config may no longer apply. If you share your configuration and what problems you're having with TestShib, I, or others, may be able to help.

**Comment by AndersAbel** [comment]
The `assertionConsumerServiceUrl` has been removed from the configuration some time ago. It was probably part of the config when @dmarlow made his config, but it isn't in the current release.

If you get the error message that "The SAML2Response must have status success to extract claims" AuthServices has received a response, but it contains an error code. Try using FireFoxe and the Saml Tracer plugin to view the actual SAMLResponse contents and see if you can figure out anything from the status code sent by TestShib.

**Comment by rdefreitas** [comment]
Here's the status response.  Config is set up exactly like @dmarlow minus the assertionConsumerServiceUrl, and I registered with testshib by uploading the metadata generated by the AuthServices url (using the MVC version)

    <saml2p:Status>
        <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder" />
        <saml2p:StatusMessage>Unable to encrypt assertion</saml2p:StatusMessage>
    </saml2p:Status>

**Comment by AndersAbel** [comment]
That looks like Shibboleth wants to encrypt the assertion, which is not supported by AuthServices (yet, see #78). Check if there is a way to disable encrypted assertions in Shib.

**Comment by agricfowl** [comment]
I have done this successfully without getting the same response. I however provided a signed certificate. 

Regards
Derrick

**Comment by rdefreitas** [comment]
@agricfowl since the AuthServices config only has signingCertificate uner identityProviders, can you offer some insight on how you used federation metadata alongside the certificate?

**Comment by agricfowl** [comment]
@rdefreitas I think l got my wires crossed here. 

I used TestShib as an SP and not as an IDP to test compatibility with a Shibboleth 2.0 SP. I had to handcraft my metadata and provided a signing certificate both for encryption and signing.

    <md:IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
      <md:KeyDescriptor use="encryption">
        <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
          <ds:X509Data>
            <ds:X509Certificate>... </ds:X509Certificate>
          </ds:X509Data>
        </ds:KeyInfo>
      </md:KeyDescriptor>
      <md:KeyDescriptor use="signing">
        <ds:KeyInfo  xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
          <ds:X509Data>
            <ds:X509Certificate>... </ds:X509Certificate>
          </ds:X509Data>
        </ds:KeyInfo>
      </md:KeyDescriptor>

I didnt use Kentor.AuthServices to set this as the dummy project is more SP than IDP and not targeted at SAML 2.0 as implemented by Shibboleth.

Sorry if l misled you.

**Comment by nikgoile** [comment]
@rdefreitas I also got the "Unable to encrypt assertion" error from TestShib.

I managed to get around it using TestShib by manually updating the metadata like @agricfowl suggested (but in the SP metadata). I created a self-signed cert following these instructions (http://www.akadia.com/services/ssh_test_certificate.html) and then added it here:

```
<SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <KeyDescriptor>
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>
            ...
          </ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </KeyDescriptor>
    <KeyDescriptor use="signing">
      <ds:KeyInfo  xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>
            ...
          </ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </KeyDescriptor>
  <AssertionConsumerService etc etc.
```

The response is now failing at my web application so guessing its my fault from this point onwards!

Hope that helps.

**Comment by AndersAbel** [comment]
@nikgoile By adding a KeyDescriptor without `use` attribute to the metadata, you enable Shibboleth to send encrypted assertions to AuthServices. But AuthServices doesn't support that, see #78, so that's why it's failing.

**Comment by albinsunnanbo** [comment]
An updated version of the config from https://github.com/KentorIT/authservices/issues/113#issuecomment-104046279 compatible with the AuthServices v0.13.0 would be

    <kentor.authServices entityId="http://localhost:2181/"
                        returnUrl="http://localhost:2181/">
      
      <federations>
        <add metadataUrl="http://www.testshib.org/metadata/testshib-providers.xml" allowUnsolicitedAuthnResponse="true" />
      </federations>
    </kentor.authServices>

**Comment by the-jiveman** [comment]
Hello.  I just tried to get Kentor AuthServices working with TestShib, too, but I get the following error:

> The Saml2Response must have status success to extract claims. Status: Responder. Message: Required NameID format not supported.

This happens AFTER My App sends me to TestShib to authenticate, I enter credentials, and it sends me back to my application and fails (with that error) at `http://localhost:1035/AuthServices/Acs`.

My web.config setup is:
```
<kentor.authServices entityId="http://localhost:1035/AuthServices"
                     returnUrl="http://localhost:1035/"
                     authenticateRequestSigningBehavior="Always">
    <nameIdPolicy allowCreate="true" format="Persistent"/>
    <metadata cacheDuration="0:0:42" validDuration="7.12:00:00" wantAssertionsSigned="true">
      <organization name="MyTestApp" displayName="My Test App" url="http://myapp.test.com" language="en-us" />
      <contactPerson type="Other" email="test@test.com" />
      <requestedAttributes>
        <add friendlyName ="Test App 1" name="urn:someName" nameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
        <add name="Minimal" />
      </requestedAttributes>
    </metadata>
    <!--<identityProviders>
      <add entityId="https://stubidp.kentor.se/Metadata"
           signOnUrl="https://stubidp.kentor.se"
           allowUnsolicitedAuthnResponse="true"
           binding="HttpRedirect"
           wantAuthnRequestsSigned="true">
        <signingCertificate fileName="~/App_Data/Kentor.AuthServices.StubIdp.cer" />
      </add>
    </identityProviders>-->
    <federations>
      <!--<add metadataLocation="https://federation.example.com/metadata.xml" allowUnsolicitedAuthnResponse = "false" />-->
      <add metadataLocation="http://www.testshib.org/metadata/testshib-providers.xml" allowUnsolicitedAuthnResponse="true" />
    </federations>
    <serviceCertificates>
      <add fileName="~/App_Data/Kentor.AuthServices.Tests.pfx" />
    </serviceCertificates>
  </kentor.authServices>
  <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" name="SampleMvcAppilcationAuth" />
    </federationConfiguration>
  </system.identityModel.services>
```
And the way I'm invoking the sign in process is just by clicking a link on the home page to `~/AuthServices/SignIn` which successfully redirects me to TestShib, like I said before.

Any ideas what I'm doing wrong?  

The Stack Trace:
```
[UnsuccessfulSamlOperationException: The Saml2Response must have status success to extract claims. Status: Responder. Message: Required NameID format not supported.]
   Kentor.AuthServices.Saml2P.<CreateClaims>d__53.MoveNext() +695
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +381
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options) +90
   Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState) +36
   Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) +379
   Kentor.AuthServices.Mvc.AuthServicesController.Acs() +54
   lambda_method(Closure , ControllerBase , Object[] ) +62
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +37
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9744373
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
```

**Comment by albinsunnanbo** [comment]
@the-jiveman 
If you can capture the SAML2 data with https://addons.mozilla.org/sv-se/firefox/addon/saml-tracer/ or https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace it would certainly be helpful when diagnosing.
But maybe you should open a separate issue?

**Comment by AndersAbel** [comment]
@the-jiveman I don't think that testShib supports the Persistent NameId format. Try to change to `<nameIdPolicy allowCreate="true" format="Transient"/>`

**Comment by the-jiveman** [comment]
@albinsunnanbo Thanks for the tip, I'll see if I can use that to help in the future.  And, I figured commenting i this thread still made sense since it has to do exactly with TestShib compatibility, but I'm happy to open a separate issue if folks think that would be best.

@AndersAbel Thanks for that info.  I tried it but had to remove `allowCreate="true"` because I received an error message that allowCreate attribute cannot be used with Transient format.  But when I did that (and after re-uploading new metadata to TestShib's registration), I received a new error message upon returning from TestShib:

> SHA256 signatures require the algorithm to be registered at the process level. Call Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures() on startup to register.

This is also on `~/AuthServices/Acs`, same as before.
This is also

**Comment by AndersAbel** [comment]
Looks like the you're now receiving a response from TestShib. The new error is because. NET doesn't support SHA256 automatically. Just add that method call somewhere in application startup and everything should work.

**Comment by the-jiveman** [comment]
Hey, worked!  Thanks a lot @AndersAbel, this is a very interesting product!  I will continue to investigate it for my potential needs. Thanks again!

**Comment by AndersAbel** [comment]
Looks like this works, so closing.
