### ISSUE TITLE
Saml2AuthenticationModule SignOut

### ISSUE THREAD

**Issue by Raschmann** [KentorIT/authservices#117]
Hi, do you have plan to implement SignOut functionality and perhaps federated SignOut? Currently sign-ou process only kills the session on SP side not in the STS side. Can you please point me to SAML specification referring to out out request message?

**Comment by barryofguilder** [comment]
Just curious if this feature is something that might be implemented in the near future or is it still a ways away?

**Comment by AndersAbel** [comment]
@barryofguilder It's not planned for the near future. We're doing development primarily based on our customers' requirements and none of them have asked for signout functionality.

This is something we will look into when we have time lefter over, or if someone pays us to do it. You are of course always welcome to look into it yourself and submit a pull request.

**Comment by AndersAbel** [comment]
There is an older issue #29 for single logout, so this is actually a duplicate. Closing.

**Comment by AndersAbel** [comment]
@barryofguilder It looks like I have to updated the prognosis on when this can be implemented. I just received pull request #197 that is an implementation of single logout, so it will probably be merged quite soon.

**Comment by barryofguilder** [comment]
@AndersAbel awesome, thanks for letting me know!  I'll take a look.
