### ISSUE TITLE
AuthnRequest signing

### ISSUE THREAD

**Issue by Raschmann** [KentorIT/authservices#123]
My question:

Do you think it can be implemented same way as signing response by calling  Sign  method of  XmlDocument  class?

Your last answer:

Do you mean signing the  AuthnRequest ? In that case it's specified in the binding spec, section 3.4.4.1. It requires changing the  Saml2RedirectBinding  implementation if I understand the spec. correctly.

**Comment by AndersAbel** [comment]
There was already an existing ticket #95 on this, closing this one as a duplicate.
