### ISSUE TITLE
Fails on redirect binding when destination contains query

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#132]
If the destination URI of a redirect binding contains a query string, the binding fails.

First noted by @panmanphil in comment on #119.

**Comment by bomzj** [comment]
When IDp sso url contains query string, Kentor generates url with second question mark. Is there any progress on the issue ?

**Comment by albinsunnanbo** [comment]
I'm not aware of anyone working on this issue, you are more than welcome to provide a pull request if you have the time.

**Comment by AndersAbel** [comment]
Fixed by #296
