### ISSUE TITLE
SessionToken Lifetime configuration

### ISSUE THREAD

**Issue by Raschmann** [KentorIT/authservices#154]
Currently the session token is created with the default lifetime value (10 hours). Use the `<sessionTokenRequirement>` lifetime atribute (if present) to set the lifetime during creation.

**Comment by AndersAbel** [comment]
The source of the lifetime config should be the following order:

1. SessionNotOnOrAfter in the assertion.
2. Configured lifetime from SessionSecurityTokenHandler in ISPOptions.
3. Default value from SessionSecurityTokenHandler.

For MVC and HttpModule using the SessionAuthenticationModule that configuration should be used. It is not as obvious for owin - have to look into if there is some similar construct in there that would be a better fit.
