### ISSUE TITLE
Integration tests does not find references

### ISSUE THREAD

**Issue by TobbeHolmstrom** [KentorIT/authservices#177]
There is no longer a dedicated solution file for the integration tests and therefore it doesn't automatically get the required packages. In this case the affected package is the Selenium Webdriver.

**Comment by AndersAbel** [comment]
The solution file for the integration tests where removed in https://github.com/KentorIT/authservices/commit/753079070fbcdd34c3dd5afe6b26ed20eeeac2aa to resolve an Azure deployment issue. We obviously have to put it back (and possibly add back the special VS-Premium sln file too) while still getting the deployments to work.
