### ISSUE TITLE
Support for Thinktecture Identityserver 3

### ISSUE THREAD

**Issue by henninga** [KentorIT/authservices#180]
Hi

I'm in the process of evaluating SSO tools and technologies and I have all but landed on Thinktecture IdentityServer 3. It is primarily using OpenId Connect, but my requirements include Saml2 using OpenSSO/OpenAM. 

Do you know if the owin middleware is able to plug right into IdentityServer? If not, do you know if it requires much alterations to make it work?
 I'm currently waiting on logon credentials for the saml2 server, so I'm not able to test it out yet.

**Comment by AndersAbel** [comment]
I was actually just talking to @leastprivilege about testing AuthServices with IdentityServer v3. We're planning to test them together and make sure they work within the next few days.

**Comment by henninga** [comment]
That is awesome. Do you think it is plug and play or is some modifications necessary?

**Comment by leastprivilege** [comment]
We will tell you once we know :)

**Comment by henninga** [comment]
Ok. I'll hopefully test it out myself once I get those credentials

**Comment by AndersAbel** [comment]
#127 was required by IdSrvr, but it's fixed now and I've got IdSrvr to run with a local dev build of AuthServices. I'm planning a release today that is compatible.

**Comment by henninga** [comment]
Wow, that was fast. Thank you. Can't wait to try it out.

**Comment by AndersAbel** [comment]
I just pushed v0.12.0 to nuget, which is tested with IdentityServer v3. Please let me know if you run into any trouble using it. There is one limitation that I know about: It doesn't support using a Discovery Service together with IdentityServer (issue #182).

The startup config I used is available on https://github.com/AndersAbel/Thinktecture.IdentityServer.v3/blob/Saml2p/source/Host/Startup.cs.
