### ISSUE TITLE
Owin Middleware doesn't preserve AuthenticationProperties across Discovery Service

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#182]
Similar to #127, but that is about preserving the properties when doing an AuthnRequest and processing the response. To have a complete solution it needs to be preserved across Discovery Services calls too.

**Comment by federicobarera** [comment]
Hi @AndersAbel ,

I came across authservices while investigating Saml2p support in identity server. 
Could you please spare a minute to extend on the implications of these limitation? Which flows/ bindings affects? Thanks

Federico

**Comment by AndersAbel** [comment]
This particular issue relates to when there is a Discovery Service configured with AuthServices. That is typically the case when you have a federation with a dynamically loaded list of identity providers. The Discovery Services is a UI for letting the user chose hat identity provider to use for authentication.

Using a discovery service is an advanced scenario. If you haven't configured one and nobody on the identity provider side has ever mentioned the need of one, you're not affected.

**Comment by wagich** [comment]
I debugged the issue and made a few changes to persist the state of the AuthenticationProperties using the existing StoredRequestState facilities. The solution works beautifully but I'd quite like a second opinion on my implementation. If all looks good I'd be happy to make a pull request.

You can have a look at the code on https://github.com/wagich/authservices/tree/preserve-state-across-ds

**Comment by AndersAbel** [comment]
@wagich Looks interesting. Please submit a PR to get it through the automatic bild and code coverage.
