### ISSUE TITLE
SP metadata file with IdentityServer 3.0

### ISSUE THREAD

**Issue by henninga** [KentorIT/authservices#184]
Hi

Still haven't been able to test authservices with IdSrv 3.0 yet, but I was wondering if it was possible to generate a SP metadata file, as the IDP requires exchanging the metadata files before using the service?

**Comment by AndersAbel** [comment]
If you install AuthServices in IdSrv the metadata will be available at ~/AuthServices (with ~ being whatever path you mapped IdSrv to).

The metadata contains a lot of URLs so it is by far easiest to grab it from the running environment. Another option is to take the owin sample application in the AuthServices Repo, configure it with your parameters and grab the metadata it exposes and then adjust the URLs.

**Comment by henninga** [comment]
Great, thanks. Does it support Single logout?

**Comment by AndersAbel** [comment]
No, not yet. It's on the todo-list: #29.

When using AuthServicse with Thinktecture IdSrv the logout process will probably be even more complex, as it would require logout both from the client, from IdSrv, the Idp and any other SAML SP that the Idp has authenticated.

**Comment by henninga** [comment]
Ahh, I see. Is that something to be implemented in the near future?

**Comment by AndersAbel** [comment]
Most features for AuthServices are done when we have a (paying) customer case for it. But we also try to make as many improvements as possible when we have time for it. Right now we've unfortunately got quite limited time to to general improvements so I cannot make any promises. If you need it, we're of course always interested in discussing sponsored development where you pay for the feature to be developed. It's much easier to ask our boss to spend time if there is a customer paying us ;-)

**Comment by henninga** [comment]
I realize that this might be difficult to answer now, but hypothetically, how much would that cost?

Is there any other big ticket items thats missing that might cause issues that you know of?

**Comment by AndersAbel** [comment]
Please mail me at anders.abel@kentor.se, or add me on skype: anders.abel.
