### ISSUE TITLE
Customizable error page

### ISSUE THREAD

**Issue by albinsunnanbo** [KentorIT/authservices#186]
Currently a validation error in the acs handler gives the yellow screen of death.
I suggest the ability to somehow specify a customized error page.

One solution could be a redirect to a configured error page URL with error information as arguments.
Or you could create a plugin/filter/middleware solution for injecting error handlers into AuthServices where you could write your own logging and error page display logic.

**Comment by AndersAbel** [comment]
I assume that this is for the Owin API? In that case it is quite tricky, as the Owin middleware runs outside the error handling mechanisms of the hosting MVC application. I'd like to have a look at how other Owin Middleware, such as those in Katana handles errors.

**Comment by albinsunnanbo** [comment]
Yep, it's the Owin stuff. Used from an ASP.NET MVC application.

**Comment by albinsunnanbo** [comment]
Stumbled upon OwinFriendlyExceptions https://github.com/abergs/OwinFriendlyExceptions today.
The name suggests it could be useful. I have not looked into any details.

**Comment by Peperud** [comment]
> Currently a validation error in the acs handler gives the yellow screen of death.
> I suggest the ability to somehow specify a customized error page.

I'm using the middleware with IdSrv3 and it is not very clear to me in this scenario who's responsibility should be do deal with it...

**Comment by AndersAbel** [comment]
The owin middleware's error behaviour has now changed. It no longer throws exceptions but rather returns an error ticket and logs the error, so this is no longer relevant.
