### ISSUE TITLE
QueryString variables (like ReturnUrl) are CaseSensitive since v0.12.0

### ISSUE THREAD

**Issue by grabmill** [KentorIT/authservices#199]
Due to replacing the querystring as NameValueCollection with ILookup<String, String>, it has become case-sensitive.

**Comment by AndersAbel** [comment]
Thanks for noticing. That has to be fixed. Should be possible to use a IEqualityComparer for the key that is case insensitive.

**Comment by AndersAbel** [comment]
Maybe I was a bit too quick, according to http://stackoverflow.com/a/24700171/280222 the query string part of a URI should be case sensitive. If I remember correctly, the casing of all SAML query string parameters is very well defined so maybe it can be left as it is now?

@grabmill Did you run into any specific problems, or did you just notice?

**Comment by grabmill** [comment]
I ran into problems indeed, but it may be because I did it wrong in the first place. If you take a look at https://msdn.microsoft.com/en-us/library/ms150046%28v=vs.110%29.aspx however (which is the code you use before), you'll see it returns a NameValueCollection, which in turn has the following info: "The comparer determines whether two keys are equal. The default comparer is the CaseInsensitiveComparer."

So, I suppose that QueryString parameters are case sensitive indeed, which means that Microsoft's implementation of HttpUtility.ParseQueryString is just a bit sloppy.

I did find an easier implementation though, for your 'problem' that you wanted to make AuthServices independent of System.Web. I messed up with Git though, so instead of making a separate Pull Request, I added it as a changeset to my other one.

**Comment by grabmill** [comment]
Could solve my problems by simply provide the ReturnUrl querystring-variable with the right casing. I'm closing this issue, as I'm convinced now that your implementation is the better one.

**Comment by AndersAbel** [comment]
There is a fix in 833228c that should be looked into, but that PR won't be merged as it contains fixes for multiple issues.

**Comment by AndersAbel** [comment]
As per the discussion above, it's perfectly fine to treat query string parameters case sensitive. Closing this as won't fix.
