### ISSUE TITLE
IdentityProvider.SigningKey wrongly named?

### ISSUE THREAD

**Issue by explunit** [KentorIT/authservices#203]
Am I correct that [IdentityProvider.SigningKey](https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/IdentityProvider.cs#L251) is wrongly named, since it is of type `AsymmetricAlgorithm` and doesn't actually contain any information about the public key of this identity provider?

**Comment by AndersAbel** [comment]
I'd rather say that it is `AssymetricAlgorithm` that is wrongly named. The `AssymetricAlgorithm` object contains both a reference to the algorithm used and to a specific key. The API used to verify signatures is `SignedXml.CheckSignature(AssymetricAlgoritm)` at [Saml2Response.cs:#414](https://github.com/KentorIT/authservices/blob/41c81b5d2ea2800d07deb33382ef859c9fd27cd4/Kentor.AuthServices/SAML2P/Saml2Response.cs#L414).
