### ISSUE TITLE
Support AssertionConsumerServices path other than "Acs"

### ISSUE THREAD

**Issue by explunit** [KentorIT/authservices#211]
AuthServicesUrls currently adds a hardcoded "Acs" for the AssertionConsumerServices:
https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/WebSSO/AuthServicesUrls.cs#L66

If you use the request and response classes separately (not using the HttpModule or the Mvc classes) this becomes awkward.

One solution would be to add a constructor to `AuthServicesUrls` which accepts two Uri's -- one for `AssertionConsumerServiceUrl` and the other for `SignInUrl`

I can create this pull request if you think this is an OK change.

**Comment by AndersAbel** [comment]
I think it's a great suggestion to add another ctor. `AuthServicesUrls` is a quite recent addition, and I've not used it outside of the standard APIs myself so far. It makes perfect sense to make them more flexible when working directly with the protocol classes.

Adding a ctor is better than making the properties' setters public. Immutable classes makes it harder to make mistakes.
