### ISSUE TITLE
Support for SAML artifact resolve?

### ISSUE THREAD

**Issue by jparra2K** [KentorIT/authservices#213]
Hi Guys,

Sorry, I did not find any other forum to post this question... I am being thinking of using Kentor Authservices for a SAML2 integration with a local government logon service. This service use a SOAP-based Artifact resolver in one part of the authentication flow. Is it any support for SAML2 artifact resolution in Kentor? If not, do you guys know any workaround?

Thanks,

Jose Parra

**Comment by AndersAbel** [comment]
There is no support for the artifact resolution binding. It's possible to add, but probably quite a lot of work. You're free to try yourself, or mail me if you want information on commercial development.

**Comment by jparra2K** [comment]
Anders, many thanks for your promptly answer.

**Comment by AndersNordin** [comment]
Hi, I'm in a similar situatuation as @jparra2K was. Has it been any progress on this issue? Any solution or workaround?

**Comment by AndersAbel** [comment]
@AndersNordin  There's been no work on artifact yet, but I am currently looking into a request to do it. If you would be able to sponsor part of the development effort it would be appreciated both by me and by those having reqeusted it. Please mail me if you're open to discuss that.
