### ISSUE TITLE
Issue with Validating the signature of Assertions

### ISSUE THREAD

**Issue by martinjt** [KentorIT/authservices#219]
I'm trying to use the library to implement a custom SSO solution to work with ADFS.  So I'm not using any of the modules, just the library to get at the Saml2Response object.  I'm not a SAML expert, so please be gentle...

At the moment, I'm simply serializing the response from an IDP initiated session like this:

     Dim encodedString as String = Request.Form("SAMLResponse")
     Dim decodedBytes as Byte() = Convert.FromBase64String(encodedString)
     Dim samlString as String = Encoding.UTF8.GetString(decodedBytes)
     Dim samlResponse as Saml2Response = Saml2Response.Read(samlString)

All the options are manually setup in code, so SPOptions and IdentityProvidersDictionary, so there's a chance that these could be wrong, however, I'm not sure due to the point at which it's failing...

When I run:

     Dim claims As List(Of ClaimsIdentity) = samlResponse.GetClaims(options)

I get a validation exception that's being thrown during the validation of the assertions.

I can debug this further, and maybe provide some example requests, but I'm trying to work out if this is something that should actually work or not.

**Comment by albinsunnanbo** [comment]
Can you post the details of the exception?
Is `allowUnsolicitedAuthnResponse` set to true?
Have you configured the certificate for the IDP?

**Comment by albinsunnanbo** [comment]
From what you describe it should work if everything is set up correctly and the request is valid.
You may want to have a look at the Saml2Response.* unit tests for guidance.

**Comment by martinjt** [comment]
it's thrown at line 417 of Saml2Response.cs

"Signature validation failed on SAML response or contained assertion."

specifically, it's when enumerating the Assertion Nodes.

Yes it sett to allow unsolicited responses, and it has a certificate.

Happy to provide any more information, I'm currently investigating whether it's a certificate issue.

**Comment by martinjt** [comment]
looks like it might be a certificate issue, changing the source of Kentor to "signedXml.CheckSignature()" with no parameters so it uses the inbuilt certificate works fine...

**Comment by AndersAbel** [comment]
That exception message indicates that it is a certificate issue. Have you been able to confirm that it indeed was? In that case, please close this issue.

**Comment by martinjt** [comment]
I'll give it a try in the next few days, if I haven't got back to you by this time next week then assume it's sorted, but I'll try my best to get back to you before that.

**Comment by martinjt** [comment]
Verified that it was user-error... for anyone else who comes across this with ADFS... you need to export the token-signing certificate.

**Comment by AndersAbel** [comment]
That's actually one of the things what I'm working on in the fix for #191, to handle the case where the signature doesn't contain the key data.
