### ISSUE TITLE
Support for InResponseTo cache in a database

### ISSUE THREAD

**Issue by martinjt** [KentorIT/authservices#221]
We are currently looking to implement kentor, however, we don't currently have guaranteed sticky sessions through our load balancers.

Is there any inbuilt ability to store the cache that stores InResponseTo objects in a datastore other than Application state?

I'm happy to put together a pull request if it doesn't exist and if you have an idea of how you would want it implementing?

**Comment by albinsunnanbo** [comment]
There is some work going on in https://github.com/KentorIT/authservices/pull/194 to move the InResponseTo content to encrypted cookies. I don't know the current progress of this. Maybe @AndersAbel or @doormalena can provide an update?

**Comment by AndersAbel** [comment]
There is an idea on how to handle this by saving the state in an encrypted cookie instead. That would make the server truly stateless, at the cost of loosing replay detection. But the validation of the assertions done by System.IdentityModel already does replay detection (including possibilities for farm setup).

I'm not working actively on this and as far as I know @doormalena has been busy elsewhere too. Nevertheless it is on my todo list, but until I have a paying customer (which you can become if you want) it won't be prioritized for some time.)

There's a quite extended discussion in #98 on this, so I'll close this issue as a duplicate. Please join the discussion on #98 if you have any further questions.
