### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by martinjt** [KentorIT/authservices#222]
Hi @AndersAbel 

When do you expect to push the next official release?  I want to know when I would need to get my work on the pendingAuthnRequests interface done to align with our releases, and also when I can get some of the new stuff you've put in (specifically some work in the AuthServiceUrls class).

I know I can use a compiled version of my own making, but I want to just use the stock repository if possible.

Thanks,
Martin

**Comment by AndersAbel** [comment]
As soon as I have time :-)

I think that there are quite a few new features that should go into a release. Initially I had planned to get a few bugs fixed too, but as time goes, it might be better to do a release anyway.

I've created a milestone with the things I think are reasonable to get done quite soon and then make a release: https://github.com/KentorIT/authservices/milestones/v0.13.0

What do you think? Does that make sense? Should I remove anything to get the release done earlier? Or is there anything more that really should go in the release?

Looking post 0.13.0 there will be another release where the signature handling is rewritten (I'm working on it). It will fix the signed assertion issue #191 and make the integration with WIF better. After that, I think that the API should be stable which means it's time to finally go to 1.0.0!

**Comment by martinjt** [comment]
That looks great, the only thing I need for my end of April go-live is the
AuthServiceUrl's work.  I need the PendingAuthnRequests work for June (only
the interface work, we can write a basic backend for it until there is an
official one), so would you be planning another release by then?

**Comment by AndersAbel** [comment]
We can do another intermediate release if there are new features that you need.

**Comment by explunit** [comment]
Assuming you are OK with #249 I would be very happy if we had an interim release with that included.

**Comment by AndersAbel** [comment]
I'm sorry for the delay, but now I'm finally wrapping up the release as outlined in https://github.com/KentorIT/authservices/milestones/v0.13.0. If there's anything more that is really urgent to have in the release, please let me know ASAP.
