### ISSUE TITLE
Test Suite status

### ISSUE THREAD

**Issue by martinjt** [KentorIT/authservices#223]
Hi all,

Is the test suite currently supposed to fully pass? I'm making some changes and I need to know if I'm supposed to make them all pass or not?

Thanks,
Martin

**Comment by AndersAbel** [comment]
Yes, except the two disabled tests for signed assertions, everything is supposed to pass. Both the unit tests, and the integration tests (in a separate project). If there's something that's broken in master, please create an issue for it and I'll have a look.
