### ISSUE TITLE
The tests Saml2RedirectBinding_Bind and Saml2RedirectBinding_Unbind are failing

### ISSUE THREAD

**Issue by martinjt** [KentorIT/authservices#224]
The above tests are failing... the encoded data is different... could this be machine specific?

**Comment by AndersAbel** [comment]
They work for me, using 522ff01, but of course they should work on your machine too. Can you provide some more details on how they fail?

**Comment by AndersAbel** [comment]
Could this be a crlf issue depending on the git settings? Maybe we should change the string constants to not embed the newline and instead use lines like `"some data\n" + `?

**Comment by martinjt** [comment]
I do get a CRLF warning on opening in VS, so that could be it.  Could just
do it as a load into an XmlDocument, then write it out?  that would get
around it too.

**Comment by AndersAbel** [comment]
I think that changing the string constant to not depend on the newlines in the file is better. Using an XmlDocument is more of a workaround to me.
