### ISSUE TITLE
FedAuth cookies seem to get dropped doing an Http:Redirect after an HttpPost

### ISSUE THREAD

**Issue by barrywimlett** [KentorIT/authservices#226]
So I'm still trying to work out whats happening to my FedAuth cookies....

So having had a spelunk around the code..

I notice that everywhere you set up a redirect you use HttpStatusCode.SeeOther which is a 303.

However looking in fiddler I notice that the redirect actually being done is a 302 not a 303.

I can also see numerous bug reports using a variety of server and code ( not just dot net ) technologies that complain about cookies getting lost during a 302 after a post.

Do you know any way of forcing the stack you sit on top to do a real 303 SeeOther instead of the 302 its actually doing ??

**Comment by barrywimlett** [comment]
As its the ACS Command I could not see anwhere in that call tree where I could influence the redirect type.

I found some logic in CommandResultHttpExtension::Apply which looked promising - but when trial running I could not get a breakpoint in there to fire.

And to be clear I am NOT saying this is your fault - it seems to be a browser issue - Firefox works, Chrome doesn't, IE can't decide -
and looking at the apply logic:

            if (commandResult.HttpStatusCode == HttpStatusCode.SeeOther || commandResult.Location != null)
            {
                if (commandResult.Location == null)
                {
                    throw new InvalidOperationException("Missing Location on redirect.");
                }
                if (commandResult.HttpStatusCode != HttpStatusCode.SeeOther)
                {
                    throw new InvalidOperationException("Invalid HttpStatusCode for redirect, but Location is specified");
                }

You seem to go out of your way in that code to ensure that only SeeOther/303s are used...

However in CommandResult - WHICH YOU DO CALL

You do this

            switch (commandResult.HttpStatusCode)
            {
                case HttpStatusCode.SeeOther:
                    return new RedirectResult(commandResult.Location.OriginalString);
                case HttpStatusCode.OK:
           
I suspect RedirectResult only does a 302 HttpStatusCode

You might have to create a custom ActionResponse which has some of the Parts of RedirectResponse and Some of HttpStatusCodeResponse
so you can do CustomRedirectResult(HttpStatusCode.SeeAlso,commandResult.Location.OriginalString);

**Comment by AndersAbel** [comment]
We finally resolved this, it was due to a redirect-path `http://site.com/path`, while the cookie had a path of `/path/`. In that case Chrome and IE won't send the cookie as the path redirected to isn't beneath the path for the cookie.
