### ISSUE TITLE
Sample OWIN project bug

### ISSUE THREAD

**Issue by cornem** [KentorIT/authservices#227]
I'm trying to get the sample OWIN project to work, but it looks like there's an error here (Startup.Auth.cs):

    var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
    {
        SPOptions = spOptions
    };

    // -- SNIP --
    new Federation(new Uri("http://localhost:52071/Federation"), true, authServicesOptions);

    return authServicesOptions;

`new Federation` expects type `Options` as the third parameter, but you're passing type `KentorAuthServicesAuthenticationOptions`.

**Comment by cornem** [comment]
Update: this doesn't happen when I clone the project from GitHub, but it does when I add the NuGet packages to another project and then copy the code from the sample solution.

**Comment by AndersAbel** [comment]
I think I've changed the API between the version currently on NuGet and the code in the repository. To get a version of the code compatible with that in the NuGet, use the code from the release tag at https://github.com/KentorIT/authservices/releases/tag/v0.12.0.

**Comment by cornem** [comment]
That's OK, looks like I don't need `Federation` anyway.
