### ISSUE TITLE
Local IDP metafile / License Question

### ISSUE THREAD

**Issue by Gerhard66** [KentorIT/authservices#229]
Great Product!

I evaluate Kentor AuthServices for an internal ASP.NET Project, which must access our already existing internal IDP. Because SAML2 protocol is used I found your product.
To fullfill our requirements the IDP-metadatafile must be deployed locally on the IIS. 
I made two patches: one for accessing the IDP-metafile locally and another one to reduce the number of web.config file accesses. With this two small patches everything seems to work fine!

My questions are license related: 
1st) Am I allowed to patch your source code and use it in our internal project? (this will later be a part of a commercial in-house application)
2nd) It would be possible to make the patched source public, but I'm not able to maintain all aspects of a "perfect" reuseable design. I'm thinking of more tailored configuration exactly matching our needs.  Is this possible with the LGPL 3.0 license?

Best Regards, Gerhard

**Comment by AndersAbel** [comment]
Thank you for your interest in AuthServices.

1. Yes, you are allowed to make modifications to the source code and use it in a commercial application, under conditions that:

 a. you keep the AuthServices code in a separate library that you link against. If you instead copy code files into your project, that will make your entire project open source under LGPL (which I assume you don't want to).
 b. you offer to supply the complete AuthServices source, including your modifications, to anyone that you distribute the application to.

If this is an in-house application that never will be distributed to someone else, that means you can keep the source to yourself.

2. You don't have to make a perfect design, please submit what you have as a pull request and leave a comment that it is not generic yet, but rather tailored to your needs. It might be a good start for someone else that want to take the time to make the code generic. There is also a reason for you to get the features that you need into the main releases: it will make it easier for you to upgrade to new versions.

For the web.config patch, you might want to look into what @doormalena did in #233.
