### ISSUE TITLE
 Metadata pulled in every request when using HTTPModule approach and loadMetadata="true"

### ISSUE THREAD

**Issue by doormalena** [KentorIT/authservices#232]
When an application (SP) is configured using the HTTPModule, and loadMetadata is set to true, the metadata is downloaded for each request to the SP. This result in a overload of data transfer of the metdata from the IDP to the SP. Depending on the capacitiy of the IDP, and the number of SP's configured, and the number of requests per second to each SP, this can result in a DDoS.

E.g. the metdata is an xml of 50kb. When accessing a page containg 1 css, 1 js and 5 images, the metadata is downloaded 8 times. 8 x 50 k = 400k for 1 user during a single page view. Imagine this with 100 page requests per second = ~40 mb/s (!)

**Comment by doormalena** [comment]
I have created a patch for it. I will upload this later via a seperate pull request as well as the other two we discussed a while ago.

The solution I have implemented moves the loading of options (via options = Options.FromConfiguration) to the Init method and assigns it to an instance variable. In the OnBeginRequest the instance variable is used. This prevents reloading the settings (including metadata and certificates) on each request in the http module. This results in a huge performance boost.

**Comment by AndersAbel** [comment]
Thanks for noticing this, the options should of course be cached to not reload the metadata all the time.

This is a problem specific to the Http module. The MVC controller caches the options in a static member. The Owin middleware gets an options instance injected as a constructor parameter.
