### ISSUE TITLE
EncryptedAssertion instead of Assertion

### ISSUE THREAD

**Issue by anepher** [KentorIT/authservices#239]
I ran into a problem at the moment when I receive the saml XML after the user gets authenticated, when the authServices on Saml2Response class in trying to parse the XML nodes to find the Assertion tag (xe.LocalName == "Assertion") the xml contains only the EncryptedAssertion tag, the principal is not created and the application throw exception for each further request. The authServices  supports decryption and simply is not happening in my case or I should implement myself a decrypt method? Or maybe the encryption is on  upper level and the Assertion should not be encrypted at all?

**Comment by explunit** [comment]
Encrypted assertions are not yet supported. See #78 for discussion about progress.
