### ISSUE TITLE
No HTTP module in the authservices package

### ISSUE THREAD

**Issue by mip1983** [KentorIT/authservices#241]
I've pulled down Kentor.AuthServices from nuget, and I get a reference to Kentor.AuthServices, but not  Kentor.AuthServices.HttpModule.

I'll pull down the source and add it manually but it could do with fixing.
![capture](https://cloud.githubusercontent.com/assets/2116108/7863953/21a4bd20-0557-11e5-8cce-3c8bf6657965.PNG)

**Comment by AndersAbel** [comment]
The HttpModule has been moved to an own assembly and changed namespaces in the current code, but it has not yet been released. So if you've looked at the documentation in HEAD you've found the new config. It will be fixed in the next release (which I hope to get time to do shortly).
