### ISSUE TITLE
Persist session across browser sessions

### ISSUE THREAD

**Issue by keesschollaart81** [KentorIT/authservices#242]
Is there a way to persist the authentication cookie ('FedAuth') between browser sessions? My goal is to keep the user logged in after he restarts his browser. I'm using the MVC Module. 

After adding `sessionToken.IsPersistent = true;` on line 72 in [this file](https://github.com/KentorIT/authservices/blob/069841535fc33655984d1cf1cdad63802eb856a4/Kentor.AuthServices.Mvc/CommandResultExtensions.cs) the cookie persists but that requires me to modify your code. 

Maybe I'm missing something and it's also possible in other ways?

**Comment by AndersAbel** [comment]
I've not looked into it myself, but there is a `persistentSessionLifeTime` setting in `<system.identitymodel.services>` that is related to that. Maybe it is enough to add that to the config?

Please leave a comment here if you try and make any findings.

**Comment by keesschollaart81** [comment]
Hi, thanks for your quick response, I'll look into that next week, will get back to you!!

**Comment by jsoncox** [comment]
I had this same issue. I was not able to get the `persistenSessionLifetime` setting to have any effect on the cookie expiration until I added `IsPersistent = true` in `SignInOrOutSessionAuthenticationModule` of CommandResultHttpExtension.cs.
