### ISSUE TITLE
Kentor.AuthServices and Framework C# NET 4.0

### ISSUE THREAD

**Issue by oriolisxra** [KentorIT/authservices#243]
Hello !

I am trying to set up SAML V2.0 Authentication in an WebSite using framework NET 4.0 and WebForms.
Is your library compatible with Framework 4.0 ?

**Comment by AndersAbel** [comment]
No it isn't compatible with 4.0. AuthServices relies heavily on the WIF components that were brought into the framework in 4.5.

If possible I'd recommend upgrading to .NET 4.5 if you need SAML support as the support for claims based identity is wastly improved.

**Comment by oriolisxra** [comment]
Unfortunately, I am not the one who decide to upgrade to NET4.5... It would be too easy otherwise.

Thank you for your quick answer.
