### ISSUE TITLE
SAML request as a querystring

### ISSUE THREAD

**Issue by agricfowl** [KentorIT/authservices#244]
Why in Saml2RedirectBinding is the SAML request expected in the Querystring when it can also appear in the Form?

I am having issues unbinding an AuthnRequest from a Shibboleth SP because their SAML request is in the form and not part of the Querystring.

I just need to know why because l am thinking of amending the code locally to look for it in the Params collection.

**Comment by albinsunnanbo** [comment]
The Saml2RedirectBinding expects the request/response to be in the query string, if you wan't to use data from a posted form you should use the Saml2PostBinding.

**Comment by agricfowl** [comment]
Saml2PostBinding expects a SAMLResponse, not a SAMLRequest.

**Comment by albinsunnanbo** [comment]
Ah, I see.
Except for the limited parts used by the StubIdp, the Authservices library does not claim to provide any IDP functionality, only SP functionality. There is no implementation for parsing requests using the post binding.
However, the ambition is to be able to use building blocks from Authservices in other applications and you are more than welcome to submit a pull request for unbinding requests using the Saml2PostBinding.
Just make sure to read the https://github.com/KentorIT/authservices/blob/master/doc/Contributing.md and before you write any major piece of code, write us a note describing the solution and we can check that it does not collide with anything else that is currently in the works.

**Comment by agricfowl** [comment]
Okay. Thanks. 

I will look into it after reading the necessary notes.
