### ISSUE TITLE
Read Audience Uris from web.config/system.IdentityModel.

### ISSUE THREAD

**Issue by mip1983** [KentorIT/authservices#246]
I'm having an issue where Saml2PSecurityTokenHandler.cs is throwing an exception (which internally is coming from 'base.ValidateConditions'): 

ID1038: The AudienceRestrictionCondition was not valid because the specified Audience is not present in AudienceUris.

Audience: 'localhost:54295'

I've tried various permutations of settings in my web.config under 'system.identityModel > identityConfiguration':

      <audienceUris>
        <add value="http://localhost:54295/" />
      </audienceUris>

I've tried these values:

http://localhost:54295/
http://localhost:54295
localhost:54295
localhost:54295/

No matter what I set, it still tells me 'Audience is not present in AudienceUris'. 
I've also tried 'audienceUris mode="Never"' which doesn't seem to have any effect.

Am I doing somthing wrong?

**Comment by AndersAbel** [comment]
I wouldn't say that you're doing something wrong, it might also be AuthServices that is wrong - but AuthServices never looks at those configured values. The audience URI is assumed to be the same as the entity ID of the SP, see https://github.com/KentorIT/authservices/blob/5a7f52d2798510b3f6ea0b93471153391603c365/Kentor.AuthServices/SAML2P/Saml2PSecurityTokenHandler.cs#L36.

This is probably a room for improvement. Do you you have any suggestion on how this is better handled?

**Comment by mip1983** [comment]
Ah, thank you for that. I've noticed in the constructor of Saml2PSecurityTokenHandler.cs, it's configuring its audience restriction from the spOptions.EntityId.Id. Perhaps to avoid any confusion it should read from 'spOptions.SystemIdentityModelIdentityConfiguration.AudienceRestriction' and if it's not null, overwrite the restrictions with that?

**Comment by AndersAbel** [comment]
Yes, that's probably a good idea. Keeping the current behaviour as a default, but allowing an override through configuration in a well known location.

Feel free to implement it and submit a PR (please read the [contribution guidelines](https://github.com/KentorIT/authservices/blob/master/doc/Contributing.md) before coding).

**Comment by AndersAbel** [comment]
Note: This is a breaking change, as configuration is now required to be set to AudienceMode.Never to accept assertions that do not contain an AudienceURI (such as the ones from the stub-idp).
