### ISSUE TITLE
Logout from ASP.NET request

### ISSUE THREAD

**Issue by nikudale** [KentorIT/authservices#251]
Hi,
I am new in this and trying to implement logout functionality. i am not sure which service need to call or if i need to reset cookies to logout for my session.
I tried to abandon my .net session and redirecting to ping url but still i am getting Request.Form["SAMLResponse"] and hence this return proper claim.
Also i tried calling FederatedAuthentication.SessionAuthenticationModule.SignOut(); 
but i am getting null for SessionAuthenticationModule, i dont know from where i can retrieve this or this is right method.

Can you please help me here to implement logout functionality in ASP.Net.

Thanks for Help!!!

**Comment by cederlof** [comment]
Refer to pull request: https://github.com/KentorIT/authservices/pull/217 as
this functionality is not yet in the main repo.

Best,
Erik
tis 23 jun 2015 kl. 14:57 skrev nikudale <notifications@github.com>:

**Comment by nikudale** [comment]
Thanks for reply.
Can you please provide code snippet to call logout and how to configure in config.
Thanks again for your reply.
