### ISSUE TITLE
Support for <RSAKeyValue> keys in metadata

### ISSUE THREAD

**Issue by wjr-** [KentorIT/authservices#253]
Currently idp metadata with key in RSAKeyValue format causes exception "This SecurityKeyIdentifier does not have any clause that can create a key".

**Comment by AndersAbel** [comment]
To read metadata we're using WIF/System.IdentityModel. The key reading is somewhat limited though, so this is something that we would have to extend to add support for.

**Comment by wjr-** [comment]
Luckily it's quite easy to implement, I'll submit a pull request shortly :)

**Comment by AndersAbel** [comment]
That would be appreciated. If you haven't seen them already, please read the contribution guidelines before you start coding.
