### ISSUE TITLE
Nuget Package doesn't really work.

### ISSUE THREAD

**Issue by tonyeung** [KentorIT/authservices#255]
I tried pulling the nuget package and creating a sample app using the samples in the source.
Looks like the versions are way out of sync.

Is there a pre-release nuget package that I can download or do I have to build from source?

**Comment by AndersAbel** [comment]
They are out of sync. I'll try to release updated nuget packages within the next few days.

If you want to use the present nuget packages, you can use the docs from the current release tag https://github.com/KentorIT/authservices/tree/v0.12.0

**Comment by tonyeung** [comment]
Nice, thanks for getting back to me so fast. I'll see how it goes.
