### ISSUE TITLE
SampleOwinApplication error v0.13

### ISSUE THREAD

**Issue by eaviran1** [KentorIT/authservices#264]
Hi,
I have downloaded the version from GitHub. Try to run the the OwinSample but its not running.
SigningKey = new X509Certificate2(
                        HostingEnvironment.MapPath("~/App_Data/Kentor.AuthServices.StubIdp.pfx"))
                        .PublicKey.Key

i get Cryptographic exception. The system cannot find the file specified.
Can you help with that, thanks

**Comment by albinsunnanbo** [comment]
Hi
I can't reproduce, the file is https://github.com/KentorIT/authservices/blob/master/SampleOwinApplication/App_Data/Kentor.AuthServices.StubIdp.pfx in GIT and loads correctly on latest from master.
Can you verify that the file has been checked out correctly and then set a breakpoint in Startup.Auth.cs:60 and check if `HostingEnvironment.MapPath("~/App_Data/Kentor.AuthServices.StubIdp.pfx")` points to the checked out file or somewhere else?

**Comment by eaviran1** [comment]
Hi sorry was my mistake somehow i did moved the Kentor.AuthServices.StubIdp.pfx file and not copied it.
