### ISSUE TITLE
Shibboleth SP metadata

### ISSUE THREAD

**Issue by eaviran1** [KentorIT/authservices#266]
Is it possible to create Shibboleth SP metadata to be given to an IDP other than kentorStubIdp for upload and than  after logging in to the IDP by using the http-redirect sso to be returned to kentor for acs. ?? Thus be authorized to get to the secure area?? If it is possible how to make that happen in code??
Thanks
  Eitan

**Comment by albinsunnanbo** [comment]
I have not use Shibboleth myself, I know there has been some discussions, please check the issues at https://github.com/KentorIT/authservices/issues?utf8=%E2%9C%93&q=shibboleth+ see if they are of any help.

**Comment by AndersAbel** [comment]
If I understand correctly what you want, you just want to get the metadata document describing the SP application that uses AuthServices? In that case, just hit ~/AuthServices on your application and you should get the metadata that you can send to the Shibboleth Idp.
