### ISSUE TITLE
Manage Logout

### ISSUE THREAD

**Issue by ViviB** [KentorIT/authservices#270]
In the official library purposed by Nugget, the logout is not manage.
I did many changes to manage logout :
- Add classes : Saml2LogoutRequest, LogoutCommand and PendingLogoutRequests
- Modify classes : IdentityProvider et Saml2RequestBase : add methods
- Modify class CommandFactory : add  a command to logout
- Modify class and interface KentorAuthServicesSection and ISPOptions

Question : You will handle the logout in the future version ?

**Comment by cederlof** [comment]
There is an open Pull-request over here: https://github.com/KentorIT/authservices/pull/217 You're welcome to improve it, and it will get merged into Main in a future version.

**Comment by ViviB** [comment]
Thanks. The code was almost the same ! : )

**Comment by ViviB** [comment]
When the future version will be available ?

**Comment by AndersAbel** [comment]
As soon as I have time to look through the pull request, which will be after my vacation - hopefully in late August.

**Comment by jdmcnair** [comment]
Any updates regarding the merging of that pull request?

**Comment by AndersAbel** [comment]
@jdmcnair Unfortunately not. It's still very relevant, but I'm overwhelmed by other work and haven't had time to work on this :-(
