### ISSUE TITLE
Rename AuthServices before 1.0.0 Release?

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#272]
When I first started working on AuthServices, my intention was to provide a SAML2 authentication module and an improved Session authentication module in the project. That would mean some general authentication (and later on maybe authorization) services - hence the name.

Now, it's evident that AuthServices has become a SAML2P implementation and nothing else. With the way the project has moved on, I think that it should stay focused on SAML2P. With that in mind, I'm not sure that "AuthServices" is the best name any more. People seldom refer to the library as "AuthServices", but rather as "Kentor" (which is a bit misleading as Kentor is a company name that does a lot more than developing this library).

So, I'd want to hear your opinions on the name - should it remain "AuthServices" or does anyone has a good alternative name? I haven't come up with anything, but a name that associates naturally with SAML2 or SAML would be nice. 

If you have a suggestion or opinion, please leave a comment!

**Comment by albinsunnanbo** [comment]
I'm pro something with SAML2 in the name to make it really obvious and easy to find.
But we need to find some unique pre/suffix to make it searchable and not drown in other SAML2 stuff.

**Comment by AndersAbel** [comment]
Now when I've been thinking of this for 6 months I suggest renaming to "Kentor.Saml2".

* Much more clear on what it is.
* Searchable
* Nobody cares about the "AuthServices" name, everyone is referring it as "Kentor".

Doing the rename would imply a lot of breaking changes and will be done before 1.0.0 is released. I'm thinking of making a final 0.X.0 release with the AuthServices name, and then make a renamed release with the new name and same features.

Any objections?

**Comment by explunit** [comment]
That sounds fine to me. 

I do notice that some other OSS (e.g. [IdentityServer3](http://leastprivilege.com/2015/03/29/identityserver3-vnext/)) have tried to separate project name from company brand/trademark, but I'm not familiar with the legal reasons why you would want to do that. It does become difficult to have a searchable name unless you have more creativity than myself (says the guy who used a [nonsense word generator](http://soybomb.com/tricks/words/) to create his github username).

**Comment by albinsunnanbo** [comment]
I'm pro the Kentor.Saml2 name

You could make the last 0.X.0 release "empty", but depend on the new Kentor.Saml2 NuGet package to help users discover the transition.Make the old package break in an instructional way with a reference to a migration guide?

**Comment by AndersAbel** [comment]
I'm starting to have second thoughts about this. It's been a few months and the number of downloads on nuget has increased steadily. People are getting used to the name and we've started using it in legal docs such as support agreements.

**Comment by kb99** [comment]
would renaming the package also involve renaming the SAML endpoint - e.g. http://localhost/identity/AuthServices ?  Some sort of upgrade path where both endpoints (authServices endpoint and new endpoint) are supported side by side would be required as this endpoint would be issued to clients using our services.

**Comment by AndersAbel** [comment]
@kb99 It would involve renaming the endpoint, but current users would be able to keep the current setup by setting a `modulePath` config. But it is one more thing that would break for everyone...

**Comment by AndersAbel** [comment]
Obsolete by #787.
