### ISSUE TITLE
Request: Can the assemblies be signed?

### ISSUE THREAD

**Issue by mip1983** [KentorIT/authservices#276]
Would it be a problem if you guys signed the assemblies? I'm presently downloading the source code and having to sign them myself to use in our solution.

**Comment by AndersAbel** [comment]
This has been discussed before, see #198. If you still need strong naming after having read that discussion, please comment on it and I'll reopen that issue.

**Comment by AndersAbel** [comment]
This has been discussed before in #198, please see that discussion and leave a comment there if you still need signing after having read those comments.
