### ISSUE TITLE
Doesn't detect my SAML in the POST body rather than Form variables

### ISSUE THREAD

**Issue by peterswallow** [KentorIT/authservices#285]
A windows application will POST a HTTP request to my Service Provider. The body of the request contains a SAML2P response message along with other XML attributes.
A sample of the HTTP body looks like this:

    <SessionRequest ... >
     <Provenance>
       <saml base64="false">
          <samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ... >
             ...
             <saml:Assertion>
                <saml:Issuer>Some Random Organsation</saml:Issuer>
              <saml:Conditions NotBefore="2015-07-31T10:25:35.9456347Z" NotOnOrAfter="2015-07-    31T10:35:35.9466348Z">
                </saml:Conditions>
             </saml:Assertion>
             <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
                <SignedInfo>
                  <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                  <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
                  <Reference URI="#F14965EE-ED43-4417-8DA3-0D302AB41AF8">
                    <Transforms>
                      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                      <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </Transforms>
                    <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                    <DigestValue>iEGFK3G9vgfj3g9gj23098Tblahblahblah....</DigestValue>
                  </Reference>
                </SignedInfo>
                <SignatureValue>
                    KkUbn3of329jas0d093jgsgblahblahblah............
                <SignatureValue>
             </Signature>
          </samlp:Response>
       </saml>
     </Provenance>
    </SessionRequest>

This saml token isn't contained within the URL or within a Forms variable, so I don't see how it can be read using the "Bind" methods for HttpPostBinding.

Or have I completely misunderstood the way it works :)

I've tried the Http Module and also looked at the OWIN code but it doesn't look like it would detect this correctly. It doesn't contain a namespace of "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" either.

Do I need to extend the supported Binding options or is this SAML in a strange format?

Thanks.

**Comment by AndersAbel** [comment]
Sending the SAML message in the request body with a POST request looks like a HTTP-POST binding. But as you've found out, this doesn't follow the format of a proper HTTP-POST binding.

The format is unknown to me and most likely the result of the windows application sending the SAML message in a non-standard way.

If you want to make AuthServices support this format, you could add another binding class that handles it. You would have to maintain that yourself though, as I don't want to merge a non-standard binding into the main library (unless more people have this exact issue).
