### ISSUE TITLE
Question: Dynamic configuration for OWIN middleware?

### ISSUE THREAD

**Issue by Peperud** [KentorIT/authservices#287]
Working with Identity Server 3 and it's support for OWIN middleware based external STS support. 

The problem is - in a multi-tenant, multi-customer etc. scenario each tenant might have their own external IdP I need to integrate with. Changes to the external IdP configuration must be wired up dynamically at runtime  without disruption of service. 

This doesn't seem to sit well with OWIN if each external provider will have to be defined upfront and basically loaded on startup (yes, it is possible to rebuild the OWIN pipeline at run-time, but this would cause service interruption and the pipeline can still get quite "stuffed"). 

Would it be possible to use Kentor in a way that will not require separate middleware instances for different IdPs, but rather have one "generic" instance which based on the request chooses a particular configuration?

**Comment by AndersAbel** [comment]
That's actually supported by AuthServices. You only need to register one middleware instance. During runtime, if you add or remove any IdentityProviders to the KentorAuthServicesOptions instance that you provided in the owin startup, those changes will immediately be used by the middleware.

**Comment by Peperud** [comment]
So I can register different IdPs in the same middleware instance and change the set of registered IdPs at runtime? 
Is there a way then to associate a tenant with a particular IdP only and route it straight to their IdP (home realm discovery hint etc.)?

**Comment by AndersAbel** [comment]
Yes, you can register different IDPs and change it during runtime.

For choosing IDP, there are two options. Either you supply a specific IDP when invoking the middleware. See the [owin docs](https://github.com/KentorIT/authservices/blob/master/doc/OwinMiddleware.md)for how to do that. Unfortunately I doubt that you will be able to do that when AuthServices is called from IdSrv3.

Another option is to use the discovery service support. That way IdSrv3 doesn't have to be involved. Instead AuthServices redirects to a discovery service where you let the user choose, or through code figure out what Idp to use and redirects back to AuthServices through the Idp Discovery protocol. Unfortunately that won't work until #182 is fixed.

**Comment by vidhyasagarreddy** [comment]
Solution over the mentioned docs doesn't seem to be working, Can you please provide me suggest a path to fix this?
