### ISSUE TITLE
Single Logout support

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#29]
Add support for single logout according to the [section 3.7 in the SAML2 specification](https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf).

**Comment by AndersAbel** [comment]
The [standards wiki start page](https://wiki.oasis-open.org/security/FrontPage#SAMLV2.0Standard) contains links to the formal specifications, including the latest errata. The single logout protocol is part of the [core](https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf) spec.

**Comment by AndersAbel** [comment]
The #197 pull request contains an implementation of this.

**Comment by renklaf** [comment]
Hi @AndersAbel. Can you elaborate on the status of merging this PR? Thanks.

**Comment by AndersAbel** [comment]
A suggested scope for a first implementation:

* Support for front-channel binding via HTTP Redirect/POST. Not SOAP at this time.
* Support for server-initiated SLO in all three API modules.
* Exposure in metadata of LogOut endpoint.
* Support for initiating SLO in all three API modules. For Owin that would be to intercept AuthenticateResponseRevoke. For MVC and HttpModule to provide logout URLs.

**Comment by AndersAbel** [comment]
Things are starting to come together. The work so far is in branch 29_SingleLogout.

**Comment by henningjensen** [comment]
This is awesome! We really need this in our current project. Thank you!
