### ISSUE TITLE
Support ForceAuthn

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#293]
Add `ForceAuthn` support to outgoing AuthnRequests.

* <del>Add `ForceAuthn` param on idp and federation config.</del>
* <del>Add `ForceAuthn` property on IdentityProvider class (set by federation if the idp is created by the federation).</del>
* Add `ForceAuthn` to `Saml2AuthenticationRequest` and to the XML.

*It's much better to let the user of the library set `ForceAuthn` through the `AuthenticateRequestCreated` notification instead of through config, so I've removed those points.*

**Comment by dammejed** [comment]
Hi,

I've encountered a usecase where I need to support sending the ForceAuthn parameter of the request for only certain types of requests. It's my intention to provide a customized action the IOptions.AuthenticationRequestCreated action and account for this in only the specified usecase, but of course I need the ability to mutate the Saml2AthenticationRequest to actually add this, hence the need for the implementation of this feature. :)

I intend to address each of the bullet points you mentioned in a pull request that I'll submit soon, though I will only minimally test the configuration cases in integration. (IdentityProvider and Federation, and their equivalent -Element classes, respectively.)

Aside from the advice mentioned in the Contribution guidelines, any specific advice regarding the configuration changes? Updates to the readme, examples? Do you expect updates to the integration tests in addition to the unit tests?

**Comment by AndersAbel** [comment]
Thanks for commenting before coding :-)

That description is outdated - it was written before the notification system was in place. With the notification system I don't see a need for having `ForceAuthn` in the configuration at all. In most use cases it will be set on a per-request basis according to some business rules (like in your case), so a static config doesn't make much sense.

I've updated the description to rely on notifications only.

**Comment by dammejed** [comment]
Great!
To be honest I had my doubts about the usefulness of the static config for ForceAuthn as well, but I figured I just didn't know the domain well enough. Glad I'm not too crazy. :)

I should be submitting the PR later today.

**Comment by premnathj** [comment]
Hi.. Greetings! I am using the kentor authservices APS.net MVC controller flow .. And I have configured the settings in the web.config.. Our Idp is Okta and things are working fine.. Now we have a use case to force the authentication.. As I explored, I need to set the ForceAuthn in the authentication request. But I don't know how to achieve this. Could you please let me know how to go about it? - Thanks

**Comment by AndersAbel** [comment]
Hook the AuthenticationRequestCreated notification and set the ForceAuthentication flag.

**Comment by premnathj** [comment]
Thankyou @AndersAbel. 
I was not using the OWIN startup as I was using just configuration in the web.config.
Now I have added the OWIN startup class and added the below code.
```
 AuthServicesController.Options.Notifications.AuthenticationRequestCreated = (request, provider, dictionary) =>
                    {
                        request.ForceAuthentication = true;
                    };
```
Please let me know if this is enough?. If not the please share some guidance.
Thanks

**Comment by AndersAbel** [comment]
@premnathj Did you test it? Does it work? There's a nice plugin to Google Chrome called SAML Dev tools that can be used to see the decoded SAML messages.

**Comment by premnathj** [comment]
Hi Anders,

Thanks of the chrome plugin. No, ForceAuthn doesn't work and I don't see
its set in the request.
Requesting you to send me some idea/code to make it work in my MVC app.

Thanks & Regards,
Prem

**Comment by premnathj** [comment]
Hi Anders,

Thanks for the plugin. I see the ForceAuthn set to "true" in the saml authentication request. Things seem to be working fine. :) 

Thanks a lot. :)

**Comment by nicswan** [comment]
Hi - I have this library working with a couple apps using ADFS as the identity provider. Now for one app (which is using the HttpModule) I have need to include ForceAuthn in the SAML request. I've read through this issue and the code in the referenced pull request (and generally looked through the other code), but it's unclear to me how I can utilize the notifications extension in the HttpModule scenario. Can you point me in the right direction? Thanks!
