### ISSUE TITLE
Cert config with thumbprint

### ISSUE THREAD

**Issue by Peperud** [KentorIT/authservices#301]
A thought - when setting the IdP, wouldn't it be enough to identity the IdP's signing cert by its thumbprint, rather than having to set the whole key explicitly? 
It's easier and more efficient to store/retrieve the thumbprint. The signing cert is always sent down with the SAMLResponse. So you can still verify the signature and can check if it is produced by a cert you expect.

And while we're here - some providers actually send two signing certs (one of which is about to expire in the near future) and they both valid for signing. 
How is this handled in Kentor?

**Comment by AndersAbel** [comment]
I've been looking into it. Before the summer, I made quite a huge effort to rewrite the certificate handling to use WIF (System.IdentityModel) and use the certificate configuration principles from there. Part of that was to allow thumbrint config. Unfortunately the rewrite didn't work out, as I found out that the WIF validator fails if the signed XML contains whitespace. Our signature validation works with that, so I chose to continue to use the present.

Regarding the signing cert being part of the signature - the cert is included in most cases, but not always so it can't be relied on.

Nevertheless I think it's a good idea to allow thumbprint config if the cert is included in the signature.

Regarding multiple signing certs, that's discussed in #105.

**Comment by Peperud** [comment]
@AndersAbel 
Interesting. Are you talking about the signature on the whole document or on the assertions?
My current code in production is mostly WIF based and I've had no issues with token validation. I do verify the document signature (if present) myself, but the token validation is WIF (which also  makes handling two signing certs relatively easy). 

I suppose you're right - it is possible not to get the signing cert in the response, though over a few dozens implementations across different providers, I'm yet to encounter one that doesn't do it. 

Thanks.

**Comment by AndersAbel** [comment]
I'm talking about the signature validation in general. If there is whitespace between the elements in the XML, the WIF signature validation fails. This is probably not a common scenario, but nevertheless something that might get us into problems.

I think that adding thumbrint as a config option to the current validation code would be great.
