### ISSUE TITLE
Web forms authentication question

### ISSUE THREAD

**Issue by bnordstrom** [KentorIT/authservices#306]
I've created a web forms application using authservices that's pointed at an ADFS instance that been configured appropriately to accept requests from my development machine.  When I use application or IDP initiated authentication I'm getting an exception when it checks if the status = Saml2StatusCode.Success in:

Kentor.AuthServices\Saml2P\Saml2Response.cs line 472
The Saml2Response must have status success to extract claims

In this instance the status is coming back as responder from the authservices/acs URL after a redirect from the authservices/signin, which then causes the exception.  

If I suppress the exception the logic runs fully, but an identity isn't being set for the user and I get the following exception:

```
[NullReferenceException: Object reference not set to an instance of an object.]
   System.Web.Configuration.AuthorizationRuleCollection.IsUserAllowed(IPrincipal user, String verb) +89
   System.Web.Security.UrlAuthorizationModule.OnEnter(Object source, EventArgs eventArgs) +12411294
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +91
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +164
```

I strongly suspect the issue has to do with the configuration on my end.  What follows are the what I think are the pertinent sections:

```
<configuration>
  <configSections>
    <section name="kentor.authServices" type="Kentor.AuthServices.Configuration.KentorAuthServicesSection, Kentor.AuthServices"/>
    <section name="system.identityModel" type="System.IdentityModel.Configuration.SystemIdentityModelSection, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
    <section name="system.identityModel.services" type="System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
```
...
```
<authentication mode="Forms">
      <forms name="SAMLSP" loginUrl="~/AuthServices/SignIn" defaultUrl="~/default.aspx" slidingExpiration="false" timeout="30" protection="All"/>
    </authentication>
```
...
```
<kentor.authServices entityId="http://mymachine.somedomain.com/SAMLSP" returnUrl="http://mymachine.somedomain.com/SAMLSP/secure" modulePath="/AuthServices">
    <metadata cacheDuration="0:15:00">
      <organization name="My Machine SP Test" displayName="portal4" url="http://mymachine.somedomain.com" language="en"/>
      <requestedAttributes>
        <add friendlyName="Last Name" name="http://schemas.somedomain.com/claims/lastname" nameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri​" isRequired="false"/>
        <add friendlyName="First Name" name="http://schemas.somedomain.com/claims/firstname" nameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="false"/>
        <add name="Minimal"/>
      </requestedAttributes>
    </metadata>
    <identityProviders>
      <add entityId="https://msidp.somedomain.com/adfs/services/trust" metadataUrl="https://msidp.somedomain.com/federationmetadata/2007-06/FederationMetadata.xml" allowUnsolicitedAuthnResponse="true" loadMetadata="true" binding="HttpRedirect"/>
    </identityProviders>
  </kentor.authServices>
```

I restricting access to the secure directory by role at the moment to trigger .Net to send the request for authentication /secure/web.config:

```
 <?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.web>
    <authorization>
      <allow roles="UberUser" />
      <deny users="*" />
    </authorization>
  </system.web>
</configuration>
```

I had intended to add logic to the Application_AuthenticateRequest to add the roles as needed once I had the users identity.

Thanks for the library and any assistance you can offer.

Brian.

**Comment by AndersAbel** [comment]
If a SAML message contains another status code than success, it shouldn't contain any assertions/claims. It looks like you've established contact with your ADFS server, but ADFS replies with some kind of error code. The easiest way to debug it is to download the SAML Tracer plugin for firefox and check the SAML response sent by ADFS.

**Comment by bnordstrom** [comment]
Handy plug in.  The error it logs is after it come back from the ADFS instance to /SAMLSP/AuthServices/Acs.

````
 The Saml2Response must have status success to extract claims.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: The Saml2Response must have status success to extract claims.

Source Error:


Line 476:            }
Line 477:
Line 478:            foreach (XmlElement assertionNode in AllAssertionElementNodes)
Line 479:            {
Line 480:                using (var reader = new FilteringXmlNodeReader(SignedXml.XmlDsigNamespaceUrl, "Signature", assertionNode))
````

From what I'm seeing in the logging its looks like an issue after authentication, but I could easily be missing something.  I'm not sure how typical traffic should look in this situation as it looks like its looping back to the the ADFS server several times:

![Uploading Log.png…]()

**Comment by AndersAbel** [comment]
If it loops back to ADFS something is wrong. Can you see what the status message is in the first response sent by the ADFS server? Typically there should be some more information in the message if the status is not success.

**Comment by bnordstrom** [comment]
The initial post back to authservices/asc contains the following on SAML,  I think its was successful.
````
<samlp:Response ID="_ad241234-489c-4a2c-8cc4-32eca342a97a"
                Version="2.0"
                IssueInstant="2015-09-21T20:05:04.354Z"
                Destination="https://mymachine.somedomain.com/SAMLSP/AuthServices/Acs"
                Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
                InResponseTo="idc79a17751bf542fd8bcb57903d8b5dc0"
                xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                >
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">https://msidp.somedomain.com/adfs/services/trust</Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <Assertion ID="_68cb8169-3063-4b7b-95e1-b5f2d33f5ed1"
               IssueInstant="2015-09-21T20:05:04.338Z"
               Version="2.0"
               xmlns="urn:oasis:names:tc:SAML:2.0:assertion"
               >
        <Issuer>https://msidp.somedomain.com/adfs/services/trust</Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
                <ds:Reference URI="#_68cb8169-3063-4b7b-95e1-b5f2d33f5ed1">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                    <ds:DigestValue>...</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>...</ds:SignatureValue>
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>...</ds:X509Certificate>
                </ds:X509Data>
            </KeyInfo>
        </ds:Signature>
        <Subject>
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData InResponseTo="idc79a17751bf542fd8bcb57903d8b5dc0"
                                         NotOnOrAfter="2015-09-21T20:10:04.354Z"
                                         Recipient="https://mymachine.somedomain.com/SAMLSP/AuthServices/Acs"
                                         />
            </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2015-09-21T20:05:04.338Z"
                    NotOnOrAfter="2015-09-21T21:05:04.338Z"
                    >
            <AudienceRestriction>
                <Audience>http://mymachine.somedomain.com/SAMLSP</Audience>
            </AudienceRestriction>
        </Conditions>
        <AuthnStatement AuthnInstant="2015-09-21T19:44:54.930Z">
            <AuthnContext>
                <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</AuthnContextClassRef>
            </AuthnContext>
        </AuthnStatement>
    </Assertion>
</samlp:Response>
````

**Comment by AndersAbel** [comment]
Yes, it's successful as indicated by `<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />`

The trace indeed shows that there is a loop. AuthServices receives the incoming response from ADFS and then redirects to SAMLSP/Secure, but at that point the user is redirected back to the SignIn url instead of allowed access. I assume that you are using the Httpmodule package? Did you load the Session Authentication Module?

**Comment by bnordstrom** [comment]
I am indeed using the HTTP module package.  The application should be loading the session authentication module, unless I've incorrectly configured something.

Web.config:
```
<system.webServer>
    <modules>
      <add name="SessionAuthenticationModule" type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
      <add name="Saml2AuthenticationModule" preCondition="" type="Kentor.AuthServices.HttpModule.Saml2AuthenticationModule, Kentor.AuthServices.HttpModule"/>
```
I'm checking into things on the ADFS side to see if I can get additional error information.  

Stepping through the authentication process in the debugger I can see where ```FederatedAuthentication.SessionAuthenticationModule
.AuthenticateSessionSecurityToken(sessionToken, true)``` 
is called and it appears to work.  It does show one claim and I would have thought there would be a claim for each requested attribute.

**Comment by AndersAbel** [comment]
It should indeed be one claim for each attribute. To find the error, I'd suggest that you change the ReturnUrl to a page that does allow unauthenticated users. In that one you can check what the claims look like. One thing to look for is to see if you get a principal of type RolePrincipal. In that case the RoleManagerModule which is part of the old membership system is messing things up. I think you should also remove the extra attributes `lidingExpiration="false" timeout="30" protection="All"/` in the forms auth config as you're should really use the forms auth module. You just want the redirection logic from it.

**Comment by bnordstrom** [comment]
Turns out you were correct that the role manager was indeed causing issues.  When I changed the config in the directory I was securing from:

```
configuration>
  <system.web>
    <authorization>
      <allow roles="UberUser" />
```
To:
```
<configuration>
  <system.web>
    <authorization>
      <deny users="?" />
```
It worked.  I'm seeing the claims and everything looks good.

Thank you very much for the assistance.
