### ISSUE TITLE
Need help for Kentor and Okta configuration, SSO How it work

### ISSUE THREAD

**Issue by tung1401** [KentorIT/authservices#313]
I am a new for SSO, I download kentor solution project and want to connect OKTA. it show many error on VS but I dont have idea for fix it

This is my web.config

< kentor.authServices entityId="http://localhost:2181/" returnUrl="http://localhost:2181/" discoveryServiceUrl="http://localhost:52071/DiscoveryService" >
    < identityProviders >
          < add entityId="https://dev-388517.oktapreview.com/app/exk5a2irk2RelVzNc0h7/sso/saml/metadata"
           destinationUrl="https://dev-388517-admin.oktapreview.com/"
           allowUnsolicitedAuthnResponse="true" binding="HttpRedirect" >
        < signingCertificate fileName="~/App_Data/Kentor.AuthServices.StubIdp.pfx" />
      </add >
    < /identityProviders >
    < federations >
      < add metadataUrl="http://localhost:52071/Federation" allowUnsolicitedAuthnResponse="true" />
    < /federations >
  < /kentor.authServices >

I found something may be it make error:
InResponseTo == null when OKTA response back to kentor

this is on Exception code:
No Idp with entity id "http://www.okta.com/exk5a2irk2RelVzNc0h7" found.

Anyone know, please help me. Thank  you

**Comment by albinsunnanbo** [comment]
Have you checked our [documentation on Okta](https://github.com/KentorIT/authservices/blob/master/doc/IdentityServer3Okta.md)?

Your `<federations>` element points to the default port of the StubIdp running on local host.
If you are using a federation you need to configure that to the correct federation url, but most likely you should remove the `<federations>` element.

**Comment by tung1401** [comment]
Thank you @albinsunnanbo 

yes, it work when I set configuration for redirect to http://localhost:2181/ it show all user data from OKTA in page.

next question
if OKTA allow user permission, I want to go to http://localhost/EHProfile/sso/sp/index for login my user inside web

and then it error like this:

An exception of type 'System.IdentityModel.Tokens.AudienceUriValidationFailedException' occurred in Kentor.AuthServices.dll but was not handled in user code

Additional information: ID1038: The AudienceRestrictionCondition was not valid because the specified Audience is not present in AudienceUris.

Audience: 'http://localhost/EHProfile/sso/sp/index'

this is new Web.config as 

 < kentor.authServices entityId="http://localhost:2181/" returnUrl="http://localhost:2181/" discoveryServiceUrl="http://localhost:52071/DiscoveryService">
    < identityProviders >
          < add entityId="http://www.okta.com/exk5a2irk2RelVzNc0h7"
           destinationUrl="https://dev-388517-admin.oktapreview.com/"
           allowUnsolicitedAuthnResponse="true" binding="HttpRedirect"
          metadataUrl="https://dev-388517.oktapreview.com/app/exk5a2irk2RelVzNc0h7/sso/saml/metadata " loadMetadata="true"  
          >
        < signingCertificate fileName="~/App_Data/Kentor.AuthServices.StubIdp.pfx" />
      < /add>
    < /identityProviders>
  < /kentor.authServices>
   < system.identityModel>
    < identityConfiguration>
      < audienceUris>
        < add value="http://localhost/EHProfile/sso/sp/index" />
      < /audienceUris>
    < /identityConfiguration>
  < /system.identityModel>

@albinsunnanbo  or Anyone Help me please, Thank you.

**Comment by albinsunnanbo** [comment]
Your config still looks a bit odd, you shouldn't have the StubIdp.pfx cert. When you configure from metadata the cert is received in the metadata.

Regarding the AudienceRestriction. If you check https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/SAML2P/Saml2PSecurityTokenHandler.cs#L35 you see that the audiencerestriction should be your SP entityId, that is `entityId="http://localhost:2181/"`. I have not used Okta myself, but i recommend following the Okta documentation closely and use configuration by code instead of configuration in web.config. Try removing your config from web.config and set up both Okta and Authservices following the documentation.
