### ISSUE TITLE
Change AuthServices to C#6?

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#314]
I'm thinking of starting to use C#6 features in AuthServices. That would require Visual Studio 2015 to be able to work with and compile the source.

Anyone for? Anyone against?

**Comment by explunit** [comment]
For

**Comment by albinsunnanbo** [comment]
For

With the Visual Studio Community edition available I can't see no reason it would prevent people from debugging and contributing.

**Comment by AndersAbel** [comment]
Great point @albinsunnanbo, with VS Community even someone that only have an older Visual Studio version from the employer can use VS2015 for AuthServices work.

I find it settled then, so feel free to use C#6. The first thing I'll look into are all ArgumentNullException checks that could use `nameof()`.

**Comment by albinsunnanbo** [comment]
It looks like installing http://code-cracker.github.io/ or similar could help converting `nameof()`, etc.

**Comment by AndersAbel** [comment]
@albinsunnanbo I just fixed nameof() for all ArgumentNullExceptions through a regexp search-replace ;-)
