### ISSUE TITLE
Problem with signature validation

### ISSUE THREAD

**Issue by apehkone** [KentorIT/authservices#328]
Hi, 
I have a problem that SAML response cannot be validated and I'll receive an exception "Signature validation failed on SAML response or contained assertion.". 

Originally authentication was working fine and the problem appeared after the customer added few custom attributes to the response message. After debugging the problem I've come to conclusion that the response itself is valid because it can be validated with SignedXml class and the problem is related to the XML structure itself and how Saml2Response retrieves assertion elements from the original XmlDocument. 

The problem is that custom attributes have namespaces defined like this: 

			<saml:Attribute Name="groups" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
				<saml:AttributeValue xsi:type="xs:string">att1</saml:AttributeValue>
				<saml:AttributeValue xsi:type="xs:string">att2</saml:AttributeValue>
			</saml:Attribute>
and the `xsi` is defined (outside of assertion node) on the XML root as `xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance`

Now in Saml2Response.CheckSignature assertion node is taken like this (line 406): `xmlDocument.LoadXml(signedRootElement.OuterXml);`

And in my case it has this XML inside the attributes node: 

		<saml:Attribute Name="groups" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
			<saml:AttributeValue xsi:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">attr1</saml:AttributeValue>
			<saml:AttributeValue xsi:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">attr2</saml:AttributeValue>
		</saml:Attribute>

As it can be seen now attributes have namespace declarations inline because the original declaration was done outside of the assertion node. As a result assertion node is changed from the original and the XML signature cannot be validated anymore. 

I think I can create a short term workaround to fix my case, but I don't understand the library well enough to make a proper fix. I have also asked the customer if they can do something on their side, but I'm sure someone will stumble to a same problem. I'm willing to contribute if I can do something to help. Thank you.

**Comment by AndersAbel** [comment]
Thanks for the detailed report.

This is a case we never thought about when we wrote the signature validation code. When validating the signature of an embedded assertion, we are extracting the assertion xml to a separate xml document and validating that. When the namespaces declaration is on the response level, that won't work.

It looks like we're up for some major rewriting of the signature validating code. It should be extracted to helper classes too, as it will be used not only for SAML Responses but also for metadata (#172)

**Comment by apehkone** [comment]
Thanks for the quick response. If I can help somehow, please let me know. 

In case you're interested, I created a temporary workaround for the problem: 
https://gist.github.com/apehkone/ff477d0c1bc6681bb96d

**Comment by AndersAbel** [comment]
Can you give a hint on what changes you've done? What line numbers?

The signature validation can be quite tricky, if you want to look into it I'd suggest you read the [breaking SAML](https://www.usenix.org/system/files/conference/usenixsecurity12/sec12-final91.pdf) paper that describes a heap of ways to do XML signature verification wrong.

**Comment by apehkone** [comment]
Sure, I added method CheckSignatureFromOriginalDocument (lines 462 to 474) as a fallback if signature validation fails on CheckSignature method (line 446). 

Here's the code: 

       void CheckSignatureFromOriginalDocument(IEnumerable<AsymmetricAlgorithm> idpKeys) {
            var originalXml = new XmlDocument();
            originalXml.LoadXml(xmlDocument.OuterXml);

            var signedXml = new SignedXml(originalXml);
            var nodeList = originalXml.GetElementsByTagName("Signature", SignedXml.XmlDsigNamespaceUrl);
            signedXml.LoadXml((XmlElement) nodeList[0]);

            if (!idpKeys.Any(signedXml.CheckSignature)) {
                throw new Saml2ResponseFailedValidationException("Signature validation failed on SAML response or contained assertion.");
            }
        }

This solved my problem for now, but it doesn't really cover any other cases.

Thanks, I'll take a look on the paper.

**Comment by AndersAbel** [comment]
That code looks vulnerable to assertion injection. Did you run the test suite? If we've done the test suite properly, there should be a few tests that no longer pass if you add that code. If all tests pass we might need to add some more to harden the signature validation even more.

**Comment by apehkone** [comment]
Actually there should be a check if "Signature" element is found from the document e.g. 

            if (nodeList.Count == 0) {
                throw new Saml2ResponseFailedValidationException("Signature validation failed on SAML response or contained assertion.");
            }

Then it passes the tests. 

However, I had one failing test "Saml2RedirectBinding_Bind_WithQueryIn_destinationUrl" in the non-modified code as well which I didn't investigate any further.

**Comment by AndersAbel** [comment]
The signature validation was rewritten in 0.16.0 so that it no longers extract the assertion before validating signature. That should have fixed this. If not, please reopen/comment.
