### ISSUE TITLE
Q: GlobalEnableSha256XmlSignatures & RSA-SHA384, RSA-SHA512

### ISSUE THREAD

**Issue by Peperud** [KentorIT/authservices#337]
Just an opinion really...
Providers are starting to offer not only **RSA-SHA256**, but also **RSA-SHA384** & **RSA-SHA512**.
Does it make sense then to have an explicit method to enable the first, but not the rest (and whatever comes next really)? 
I'd argue that conceptually the responsibility for providing methods for configuring this on process level, should lay outside of Kentor core.

**Comment by albinsunnanbo** [comment]
The `GlobalEnableSha256XmlSignatures` is just a convenient helper to make it easier to setup Authservices. It looks reasonable to include the other two algorithms too. We need to write the `SignatureDescription` for those, but that does not look very hard.

To simplify Authservices setup I could rather argue for an Autoconfig of known signature algorithms. If Authservices detects that RSA-SHA256/384/512 is required it could automatically enable that algorithm before trying to validate the signature.

**Comment by AndersAbel** [comment]
Looks like it's time to extend the support to more algorithms. Since this affects the entire process I think that this must be an opt in. I know that there's been reports on IdentityServer3 breaking when `GlobalEnableSha256XmlSignatures` has been called.

**Comment by albinsunnanbo** [comment]
Example of RSA-SHA512 SignatureDescription http://stackoverflow.com/a/21435041/401728

**Comment by Peperud** [comment]
> I know that there's been reports on IdentityServer3 breaking when GlobalEnableSha256XmlSignatures has been called.

Yes. Though it is not IdSrv's fault and is not limited to IdSrv. As far as I could tell the JWT sighing fails when SHA-2 algorithm is registered (even if not used anywhere), and the certificate used for sighing (IdSrv signing cert, not the cert an incoming SAML response was signed with) does not support SHA-2. 
It might work if CSP is explicitly specified after the private key is created from the cert (and before it is used), however this is all in the MS code. 
I haven't tried it, but the same thing might happen with XML signing as well (if the above step is not explicitly taken).
The whole thing looks very much like a MS brain fart and it appears that the easiest fix is to just get a signing cert with SHA-2 support and move on.

**Comment by AndersAbel** [comment]
Microsoft just announced that .NET 4.6.2 will have built in support for these signature algorithms. See [this blog post](https://blogs.msdn.microsoft.com/dotnet/2016/03/30/announcing-the-net-framework-4-6-2-preview/).

I suggest that when 4.6.2 is released we update AuthServices to require it and get rid of the GlobalEnableSha256XmlSignatures.

**Comment by albinsunnanbo** [comment]
Give it a while, it usually takes some time to get servers upgraded.

**Comment by AndersAbel** [comment]
Using .NET 4.6.2 AuthServices supports RSA-SHA384 and RSA-SHA512.
