### ISSUE TITLE
Saml2AuthenticationModule swallows exceptions

### ISSUE THREAD

**Issue by mnaoumov** [KentorIT/authservices#338]
I am getting 500 error when I reach http://myserver/AuthServices/Acs and it was not clear why is that happening.

When I attached debugger and disabled **Just My Code** setting in Visual Studio I finally found the place

https://github.com/KentorIT/authservices/blob/f038e2d598f81f8d6d45a8e58775caf497df2a77/Kentor.AuthServices.HttpModule/Saml2AuthenticationModule.cs#L72

Here errors are caught but not shown afterwards. Is that intentional? How should we troubleshoot such errors if we cannot attach debugger?

BTW, In my case that was an **NoSamlResponseFoundException**

**Comment by AndersAbel** [comment]
Swallowing the exact exception that way looks like one of my worst ideas ever. I might have had some kind of idea to now show security sensitive stuff to the user. But that's not a valid reason, if the site shows detailed exceptions they have themselves to blame.

I'm tagging this as a bug.
