### ISSUE TITLE
Option to set application URL

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#340]
This is a discussion, based on the #331 pull request. I prefer to have it as an issue too, to make sure it's kept track of.

## Short summary of that thread

@simon-hofer describes the problem where an AuthServices instance running behind a reverse proxy will generate URLs based on the internal URL of the server. Those are not valid for the client. The URLs generated should match the reverse proxy's external URLs.

@explunit mentions that [IdentityServer3](https://identityserver.github.io/Documentation/docs/configuration/identityServerOptions.html) has such an option, which is called `PublicOrigin`.

## My Comments
I think that adding the feature is good. Thanks @explunit for pointing to the IdSrv3 doc. What I would like to discuss is how this option should relate to `ModulePath`. Should they be merged into one base url path? Or kept as two separate options? Although looking similar, they are used in different places and merging them might make it hard to separate them. `ModulePath` is used to match incoming requests, and should always be relative to the web application. In some cases ModulePath might not even match the public facing URL. `PublicOrigin` would be used when generating URLs in outbound messages.

I'm leaning towards keeping `ModulePath` as is and adding `PublicOrigin` as a new option. If both are specified, I think that `PublicOrigin` should be the full URL of AuthServices - e.g. `https://sp.example.com/Application/AuthServices`.

Any comments?

**Comment by simon-hofer** [comment]
I agree with you, it could become complicated to separat in future and is more clear with tow options. I alos agree with the naming in a more generci manner and consequent implementation on all outgoing urls produced in any requests.
Should i improve to pull  request #331 or is it better when you implement this?

**Comment by Peperud** [comment]
@AndersAbel 
I just got bitten by this.

Please consider the `PublicOrigin` to be overridable ***per-request***. 
IdentityServer3 does have the public origin concept at global level, but it also has an OWIN environment extension method to set the origin per request. This is very useful when working behind proxies and need to inject custom resolving logic. 

A related issue is that IdSrv3 is not case sensitive when it comes to the urls it was accessed on, but then the SAML IdP will perform a case sensitive compare on the ACS URL (which Kentor middleware will build based on the request).
