### ISSUE TITLE
Okta Set up for IdP-Initiated support

### ISSUE THREAD

**Issue by ruslander** [KentorIT/authservices#341]
Going through the tutorial of configuring Okta in a spike. So far it went great until I reached the following block of code

            var client = new OAuth2Client(new Uri("https://<youridentityserver>" + "/connect/authorize"));
			var scopesForAuth = "<the scopes for your application>";

            var returnUrlForOkta = client.CreateAuthorizeUrl(
	            	"<youridserverclientid", 
	            	"id_token token", 
	            	scopesForAuth, 
	                "https://yoursite.com/yourreallogintarget", 
	                state, 
	                nonce, 
	                acrValues: string.Format("idp:{0}", idp), 
	                responseMode: "form_post"
                );

For a newbie does not feel very intuitive where I get the values for following blanks. I will try to be more explicit.

1) "https://youridentityserver"
	- the fully qualified domain name to where is hosted IdentityServer
	- ex https://samlauth-rr-71k0j0ps.cloudapp.net/identity

2) var scopesForAuth = "<the scopes for your application>";
	using "openid email profile"
	- no idea 

3) "<youridserverclientid"
	- the setup of the client app in the IdentityServer3
	- not clear how to configure that
	- ex https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/WebHost%20(minimal)/WebHost/Configuration/Clients.cs

4) https://yoursite.com/yourreallogintarget
	- i assume that after I log in this is the landing page

5) Given that Okta is user authority how should following be configured
	Users 
	Scopes
	Clients 

I'll appreciate any hint/links and happily send you a pull request with what I find to the docks.

Thanks R

**Comment by AndersAbel** [comment]
@dahlsailrunner do you have time to look at this?

**Comment by dahlsailrunner** [comment]
Hi guys - sorry for the tardy response.  I've got a production release coming up Wednesday and have been busy getting ready for it.  I'll try to address your questions point by point, but it seems like you are new to IdentityServer3 and setting up clients/scopes/etc.  

From a high level, there are really three major players in the picture with this landscape: 1) various identity providers (like okta, Azure Active Directory, etc), 2) your identity server which will presumably use the idp's for authentication, and 3) any number of client applications in which you will use identity server for login -- these clients could be javascript apps, websites, mobile apps, desktop apps or whatever.  To start setting this up within IdentityServer (which needs to know about your idps AND your client apps), [this doc is a really good walkthrough] (https://identityserver.github.io/Documentation/docsv2/overview/simplestOAuth.html).  

Now for your questions:
1.  Looks like you have this correct.  The URI you are trying to construct is the "authorize" endpoint within your identity server.  So if your identity server is running at https://samlauth-rr-71k0j0ps.cloudapp.net/identity, then the full URI you are building is this:
https://samlauth-rr-71k0j0ps.cloudapp.net/identity/connect/authorize.

2 (and 3).  These are really both addressed by configuring your scopes, claims, and clients within IdentityServer3 (see the walkthrough link above).  The IdentityServer3 docs provide [more details on scopes and claims] (https://identityserver.github.io/Documentation/docsv2/configuration/scopesAndClaims.html) as well as on [Clients] (https://identityserver.github.io/Documentation/docsv2/configuration/clients.html).  In a nutshell, the scopes for ANY client that you want to allow should be in your Scopes.cs file.  All of your clients are configured as Client objects in the Clients.cs class, each containing either a list of allowed scopes for the client or "allow all".  If you have a single website that you want to login to via Identity Server, you could simply configure one Client.  Part of the object is the string for ClientId.  The allowed scopes, and then client id you establish here (within IdentityServer3) are what you use for your questions on points 2 and 3.

4.  For me, the "real login target" was something like this: "https://mysite.com/Login.aspx" (using webforms -- if you're using MVC you could just set up a method with the [HttpPost] attribute on it).  Then what you want is some code that will handle the passed id_token and/or token (access token) by either storing them in session and/or turning them into a claims identity. My code snippet below is in the Page_Load method for my login.aspx page.  The "SignInExternalUser(token)" call creates a ClaimsPrincipal by calling the JwtSecurityTokenHandler.ValidateToken method (I can provide some code if you want to see this).  You could also call the access token validation endpoint of IdentityServer3 to get a list of claims from the access token if that seems easier.

```charp
// if the "id_token" is in the POST content, then we are logging in through id server and have a valid id_token
            //    so we need to take the id_token and sign them in, and then redirect them.     
            var token = Request["id_token"];
            if (token != null)
            {
                NwpSession.IdToken = token;
                NwpSession.AccessToken = Request["access_token"];
                if (SignInExternalUser(token))
                {
                    var cp = HttpContext.Current.User as ClaimsPrincipal;
                    RedirectUser();
                    return;
                }
            }

5. The "Scopes" and "Clients" part of your question I'm thinking have been addressed by the notes above.  As for the "Users" question - that gets more complicated I think.  If you already have a list of valid okta users (and that list will stay up to date) you can simply add them to the "InMemoryUserStore" within IdentityServer3 as shown in the walkthrough above.  If, on the other hand, you just want to accept any okta users or have them "register" somehow on your site/app, you will probably need a [custom user service as described here] (https://identityserver.github.io/Documentation/docsv2/advanced/userService.html).  I have done this myself and it's not too bad.  The "AuthenticateExternalAsync" method will be hit when you have a user authenticated through okta, and the ExternalIdentity will be the identity that came from Okta.  From there you can look it up in a user list, simply allow it in by setting the AuthenticateResult object.

HTH.  If anything is unclear after reviewing this, let me know and I can take another shot at explaining.
Cheers - 
Erik

**Comment by ruslander** [comment]
@AndersAbel @dahlsailrunner  thank you for your time and quick response.

This is definitely very helpful, the replay is dense. Let me process it and I will get back to you
in case I exercise all the resources and I have any questions.

**Comment by ruslander** [comment]
I got my hello world sample working with following settings

Identity server config
	new Client
    {
        ClientName = "sassrr",
        ClientId = "sassrr",
        Enabled = true,
        AccessTokenType = AccessTokenType.Reference,
        Flow = Flows.Implicit,
        RequireConsent = false,
        RedirectUris = new List<string> { "http://localhost:54792/Default.aspx"},
        ClientSecrets = new List<Secret>{ new Secret("F621F470-9731-4A25-80EF-67A6F7C5F4B8".Sha256())},
        AllowedScopes = new List<string>{"sassweb"}
    }

    new Scope
    {
        Name = "sassweb"
    }


Authorization check

	var client = new OAuth2Client(new Uri("https://samlauth-rr-71k0j0ps.cloudapp.net/identity/connect/authorize"));
    var startUrl = client.CreateAuthorizeUrl(
        clientId: "sassrr",
        responseType: "token",
        scope: "sassweb",
        redirectUri: "http://localhost:54792/Default.aspx",
        nonce: "random_nonce",
        responseMode: "form_post",
        acrValues: "idp:okta");

    Response.Redirect(startUrl, false);

**Comment by dahlsailrunner** [comment]
Glad to hear it, and congrats!  :)

**Comment by ruslander** [comment]
The use case I'm trying to make it work is I want to accept any okta users. I'm reaching the 
login.aspx with Request["access_token"] populated till here is all good. From here I need 
access to the email of the current user.

To get to it i've tried couple of things:

	1) in okta enabled the attributes for [user.email, user.firstName, user, user.lastName, user.login]. 
	   And I can see it in the "Preview the SAML assertion".
	2) in the Startup.cs added following code with intention to intercept auth

			var userService = new ExternalRegistrationUserService();
            factory.UserService = new Registration<IUserService>(resolver => userService);

		unfortunatelly this code in AuthenticateExternalAsync and GetProfileDataAsync never gets called.
		No idea how to get to context.ExternalIdentity.

	3) tried to include "email" scope in CreateAuthorizeUrl and getting invalid_scope

I'll apreciate if you guys can point me to the light at the end of tunel

Thanks,
R

**Comment by albinsunnanbo** [comment]
Is it startup.cs of your IDP or SP?
If it is on the SP (AuthServices) side you just inspect the claims on the identity, preferably in [ClaimsAuthenticationManager](https://github.com/KentorIT/authservices/blob/master/doc/ClaimsAuthenticationManager.md), see example in https://github.com/KentorIT/authservices/blob/4ffe5c54f8b2100a37a6e4cf7269f65a40b0798e/Kentor.AuthServices.Tests/ClaimsAuthenticationManagerStub.cs

**Comment by ruslander** [comment]
@albinsunnanbo 
I'm using following topology [sp] -> [Federated Idp] -> [okta]. The startup.cs I mentioned above it is in [Federade Idp]. The [sp] is the location where i want to get access to the email claim. [sp] is a web forms app, at this point I can only get the auth token with CreateAuthorizeUrl. 

Looking for an example of how I can access the email in the sp.

**Comment by dahlsailrunner** [comment]
Couple of comments -- the ExternalUserRegistrationService really should get called when you do your auth -- this would be invoked during your "authorization check" code above -- the response.redirect from your login page.  Are you setting the options.Factory = the factory you have instantiated?  I'm doing something very similar with a custom user service and it works fine.

Once you get in there you should be able to see the external identity and its claims.

For your note about the "invalid_scope", this is because (I presume) your Client is not allowed that scope -- in your config code above, you have to add the "email" scope to the list of Scopes, and then also add it to the AllowedScopes for your Client.  Doing this will not magically put the email in your claims response, but it will allow your client to request that scope without getting an "invalid_scope" message.

**Comment by ruslander** [comment]
The AuthenticateExternalAsync in ExternalRegistrationUserService does not get invoked, running it with following binaries

  <package id="IdentityServer3" version="2.2.3" targetFramework="net45" />
  <package id="Kentor.AuthServices" version="0.14.0" targetFramework="net45" />
  <package id="Kentor.AuthServices.Owin" version="0.14.0" targetFramework="net45" />

the Setup.cs on federated idp with Okta

app.Map("/identity", idsrvApp =>
    {
        var factory = new IdentityServerServiceFactory();
        factory
            .UseInMemoryClients(Clients.Get())
            .UseInMemoryScopes(Scopes.Get());

        var userService = new ExternalRegistrationUserService();
        factory.UserService = new Registration<IUserService>(resolver => userService);
        factory.CorsPolicyService = new Registration<ICorsPolicyService>(new DefaultCorsPolicyService { AllowAll = true });

        idsrvApp.UseIdentityServer(new IdentityServerOptions
        {
            SiteName = "Federated Identity Server 3",
            SigningCertificate = WebHost.Configuration.Certificate.Load(),
            Factory = factory,
            AuthenticationOptions = new AuthenticationOptions
            {
                IdentityProviders = WireIdps
            },

            EventsOptions = new EventsOptions
            {
                RaiseSuccessEvents = true,
                RaiseErrorEvents = true,
                RaiseFailureEvents = true,
                RaiseInformationEvents = true
            }
        });
    }); 

new Client
    {
        ClientName = "sassrr",
        ClientId = "sassrr",
        Enabled = true,
        AccessTokenType = AccessTokenType.Jwt,

        Flow = Flows.Implicit,
        RequireConsent = false,

        RedirectUris = new List<string>
        {
            "http://localhost:54792/Default.aspx"
        },

        ClientSecrets = new List<Secret>
        {
            new Secret("F621F470-9731-4A25-80EF-67A6F7C5F4B8".Sha256())
        },


        AllowedScopes = new List<string>
        {
            Constants.StandardScopes.OpenId,
            Constants.StandardScopes.Profile,
            Constants.StandardScopes.Email,
            Constants.StandardScopes.Roles,
            Constants.StandardScopes.OfflineAccess,

            "sassweb"
        }
    }

new List<Scope>
    {
        new Scope
        {
            Name = "sassweb"
        },

        StandardScopes.OpenId,
        StandardScopes.Roles,
        StandardScopes.Profile,
        StandardScopes.Email,
        StandardScopes.OfflineAccess
    };

When I call the authirization 

            var client = new OAuth2Client(new Uri("https://samlauth-rr-71k0j0ps.cloudapp.net/identity/connect/authorize"));
            var startUrl = client.CreateAuthorizeUrl(
                clientId: "sassrr",
                responseType: "id_token token",
                scope: "sassweb openid",
                redirectUri: "http://localhost:54792/Default.aspx",
                nonce: "random_nonce",
                responseMode: "form_post",
                acrValues: "idp:okta");

            Response.Redirect(startUrl, false);

Produces following output

  22:00:03 [Information] WebHost.Startup Configuration started
  22:00:03 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log AuthorizationCodeStore not configured - falling back to InMemory
  22:00:03 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log TokenHandleStore not configured - falling back to InMemory
  22:00:03 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log ConsentStore not configured - falling back to InMemory
  22:00:03 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log RefreshTokenStore not configured - falling back to InMemory
  22:00:05 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log {
    "Category": "Information",
    "Name": "Signing certificate validation success",
    "EventType": "Information",
    "Id": 4012,
    "Details": {
      "SigningCertificateName": "CN=idsrv3test",
      "SigningCertificateExpiration": "2020-01-20T22:00:00+00:00"
    },
    "Context": {
      "TimeStamp": "2015-12-09T22:00:05.2027034+00:00",
      "ProcessId": 3972,
      "MachineName": "SAMLAUTH-RR"
    }
  }
  22:00:05 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log CORS request made for path: "/AuthServices/Acs" from origin: "https://dev-935143.oktapreview.com" but rejected because invalid CORS path
  22:00:06 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log Start authorize request
  22:00:06 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log Start authorize request protocol validation
  22:00:06 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log "Authorize request validation success"
   "{
    \"ClientId\": \"sassrr\",
    \"ClientName\": \"sassrr\",
    \"RedirectUri\": \"http://localhost:54792/Default.aspx\",
    \"AllowedRedirectUris\": [
      \"http://localhost:54792/Default.aspx\"
    ],
    \"SubjectId\": \"ed3ab4e557539ba1fc51c95189bfa297\",
    \"ResponseType\": \"id_token token\",
    \"ResponseMode\": \"form_post\",
    \"Flow\": \"Implicit\",
    \"RequestedScopes\": \"sassweb openid\",
    \"Nonce\": \"random_nonce\",
    \"AuthenticationContextReferenceClasses\": [
      \"idp:okta\"
    ],
    \"SessionId\": \"2a125b199f5509f2ca2977db4604a907\",
    \"Raw\": {
      \"client_id\": \"sassrr\",
      \"response_type\": \"id_token token\",
      \"scope\": \"sassweb openid\",
      \"redirect_uri\": \"http://localhost:54792/Default.aspx\",
      \"nonce\": \"random_nonce\",
      \"acr_values\": \"idp:okta\",
      \"response_mode\": \"form_post\"
    }
  }"
  22:00:06 [Information] WebHost.ExternalRegistrationUserService IsActiveAsync RRRRRR IsActiveAsync called 0
  22:00:07 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log Creating Implicit Flow response.
  22:00:07 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log {
    "Category": "TokenService",
    "Name": "Access token issued",
    "EventType": "Information",
    "Id": 2000,
    "Details": {
      "TokenType": "Jwt",
      "SubjectId": "ed3ab4e557539ba1fc51c95189bfa297",
      "ClientId": "sassrr",
      "Scopes": [
        "sassweb",
        "openid"
      ],
      "Lifetime": 3600,
      "Claims": {
        "client_id": "sassrr",
        "scope": [
          "sassweb",
          "openid"
        ],
        "sub": "ed3ab4e557539ba1fc51c95189bfa297",
        "auth_time": 1449680786,
        "idp": "okta",
        "amr": "external"
      }
    },
    "Context": {
      "ActivityId": "3e00adef-99f4-4da4-8901-9882250fca74",
      "TimeStamp": "2015-12-09T22:00:07.1870654+00:00",
      "ProcessId": 3972,
      "MachineName": "SAMLAUTH-RR",
      "RemoteIpAddress": "208.185.125.115",
      "SubjectId": "ed3ab4e557539ba1fc51c95189bfa297"
    }
  }
  22:00:07 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log Getting claims for identity token for subject: ed3ab4e557539ba1fc51c95189bfa297
  22:00:07 [Information] WebHost.ExternalRegistrationUserService GetProfileDataAsync RRRRRR GetProfileDataAsync called 0
  22:00:07 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log {
    "Category": "TokenService",
    "Name": "Identity token issued",
    "EventType": "Information",
    "Id": 2001,
    "Details": {
      "SubjectId": "ed3ab4e557539ba1fc51c95189bfa297",
      "ClientId": "sassrr",
      "Lifetime": 300,
      "Claims": {
        "nonce": "random_nonce",
        "iat": 1449698407,
        "at_hash": "pGs6qo83tEk-jl_e3dK8kA",
        "sid": "2a125b199f5509f2ca2977db4604a907",
        "sub": "ed3ab4e557539ba1fc51c95189bfa297",
        "auth_time": 1449680786,
        "idp": "okta",
        "amr": "external"
      }
    },
    "Context": {
      "ActivityId": "3e00adef-99f4-4da4-8901-9882250fca74",
      "TimeStamp": "2015-12-09T22:00:07.2495639+00:00",
      "ProcessId": 3972,
      "MachineName": "SAMLAUTH-RR",
      "RemoteIpAddress": "208.185.125.115",
      "SubjectId": "ed3ab4e557539ba1fc51c95189bfa297"
    }
  }
  22:00:07 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log {
    "Category": "Endpoints",
    "Name": "Endpoint success",
    "EventType": "Success",
    "Id": 3000,
    "Details": {
      "EndpointName": "authorize"
    },
    "Context": {
      "ActivityId": "3e00adef-99f4-4da4-8901-9882250fca74",
      "TimeStamp": "2015-12-09T22:00:07.3433145+00:00",
      "ProcessId": 3972,
      "MachineName": "SAMLAUTH-RR",
      "RemoteIpAddress": "208.185.125.115",
      "SubjectId": "ed3ab4e557539ba1fc51c95189bfa297"
    }
  }
  22:00:07 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log End authorize request
  22:00:07 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger Log Posting to http://localhost:54792/Default.aspx


I included in each overloaded member in ExternalRegistrationUserService a line for tracing purpose
    Log.Information("RRRRRR [method name here] called " + Users.Count);

I can see in the generated log   
  22:00:07 [Information] WebHost.ExternalRegistrationUserService GetProfileDataAsync RRRRRR GetProfileDataAsync called 0
  22:00:06 [Information] WebHost.ExternalRegistrationUserService IsActiveAsync RRRRRR IsActiveAsync called 0

and i do not see any AuthenticateExternalAsync

Do i miss something in the configuration or there is a bug in IdentityServer3 ?

ps: if any of you is interested in consulting please dm me on twitter at @ruslanrusu

**Comment by dahlsailrunner** [comment]
Can you provide your code for your UserService?  And which version of id server are you running?

**Comment by ruslander** [comment]
@dahlsailrunner  Here it is just the service, if you think it is gonna be helpful i can push to github a minimal sample in which the issue manifests.

    public class ExternalRegistrationUserService : UserServiceBase
    {
        public static List<CustomUser> Users = new List<CustomUser>();

        public override Task AuthenticateExternalAsync(ExternalAuthenticationContext context)
        {
            Log.Information("RRRRRR GetProfileDataAsync called " + Users.Count);

            var user = Users.SingleOrDefault(x => x.Provider == context.ExternalIdentity.Provider && x.ProviderID == context.ExternalIdentity.ProviderId);
            string name = "Unknown";
            if (user == null)
            {
                var nameClaim = context.ExternalIdentity.Claims.First(x => x.Type == Constants.ClaimTypes.Name);
                if (nameClaim != null) name = nameClaim.Value;

                user = new CustomUser { 
                    Subject = Guid.NewGuid().ToString(),
                    Provider = context.ExternalIdentity.Provider,
                    ProviderID = context.ExternalIdentity.ProviderId,
                    Claims = new List<Claim> { new Claim(Constants.ClaimTypes.Name, name) }
                };
                Users.Add(user);
            }

            name = user.Claims.First(x => x.Type == Constants.ClaimTypes.Name).Value;
            context.AuthenticateResult = new AuthenticateResult(user.Subject, name, identityProvider:user.Provider);
            
            return Task.FromResult(0);
        }

        public override Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            Log.Information("RRRRRR GetProfileDataAsync called " + Users.Count);

            var user = Users.SingleOrDefault(x => x.Subject == context.Subject.GetSubjectId());
            if (user != null)
            {
                context.IssuedClaims = user.Claims.Where(x => context.RequestedClaimTypes.Contains(x.Type));
            }

            return Task.FromResult(0);
        }
    }

Thanks,
R

**Comment by dahlsailrunner** [comment]
Does your "UserServiceBase" implement IUserService?  My custom user service doesn't use a base class but just implements IUserService directly.  Then my factory registration is (just like yours):
```csharp
   var userService = new NwpUserService();
   factory.UserService = new Registration<IUserService>(resolver => userService);
```
Also - could you change your logging line inside AuthenticateExternalAsync to log that it's calling that method rather than GetProfileData (and then re-run your test and show the logging output)?

If these notes don't create any conclusions a little GitHub sample would be the next step.  Failing that, I might have you post your question on the IdentityServer3 repo.  But I'm not throwing in the towel yet!  :)

**Comment by ruslander** [comment]
@dahlsailrunner, I've attached here the `ExternalRegistrationUserService` which implements `IUserService` and the output log file it produces

[ExternalRegistrationUserService.txt](https://github.com/KentorIT/authservices/files/58324/ExternalRegistrationUserService.txt)

[out.txt](https://github.com/KentorIT/authservices/files/58330/out.txt)

**Comment by dahlsailrunner** [comment]
From what I can tell on the docs (https://github.com/IdentityServer/IdentityServer3/issues/975, and https://identityserver.github.io/Documentation/docsv2/advanced/userService.html), you may need to be allowing and providing the profile and openid scopes in order for the authenticateexternalasync to be called.  There is a pretty full sample on GitHub here: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService/CustomUserService.  I'd say give that a shot and then let's see where you're at.

You might also try implementing the PreAuthenticateAsync and PostAuthenticateAsync methods and see if they yield any information.

**Comment by ruslander** [comment]
@dahlsailrunner  I gave it a shot and still nothing. Here is what i did

	1) added logging in each overloaded member
	2) included openid and profile in auhorization call

Still do not see the AuthenticateExternalAsync being called.
I have attached here the execution log and link to the smallest
code to recreate the environment. 

Code: https://github.com/ruslander/ssosaml
[log2.txt](https://github.com/KentorIT/authservices/files/58622/log2.txt)

**Comment by dahlsailrunner** [comment]
I've just gotten a big dump of work that I have to address here over next couple of days.  Can you post your question to identityserver3 repo -- specifically just post your GitHub project and ask why the AuthenticateExternalAsync is not getting called?

**Comment by ruslander** [comment]
@AndersAbel thanks I will do that

**Comment by bitbybitllc** [comment]
This helped clear up a lot. However I'm getting type or namespace for OAuth2Client could not be found. 

Solutions to fix this?

**Comment by dahlsailrunner** [comment]
This is probably some package reference that you might be missing.  Are you still having trouble?  Is this a build (compile time) or execution (run time) error that is happening?  And what is the line of code that references OAuth2Client?
