### ISSUE TITLE
HttpModule should allow a Https AssertionConsumerServiceURL

### ISSUE THREAD

**Issue by karimainine** [KentorIT/authservices#354]
I have been able to successfully configure my .NET application to send SP requests to an Oracle based IdP and authenticate. However, when deploying the code on the staging servers, the entityID needed to be a HTTPS url (all requests going through the server need to be HTTPS, otherwise they are blocked by a F5 irule). 

I have noticed that regardless of the entityID protocol, the assertionConsumerServiceURL always uses HTTP. On returning from the IdP, the application attempts going to http://hostname/AuthServices/Acs and gets blocked by the F5. 

Is there any way I can set the assertionConsumerServiceURL manually or programmatically?

**Comment by albinsunnanbo** [comment]
The protocol of the ACS-url is the same protocol as your application uses.
If you initiate the login from http://hostname/AuthServices/SignIn the ACS will be http://hostname/AuthServices/Acs but if you initiate from https://hostname/AuthServices/SignIn the ACS will be https://hostname/AuthServices/Acs

**Comment by AndersAbel** [comment]
Are you terminating the TLS connection in an external load balancer/firewall? So that while the client sees https, the server is actually serving pages over http? Then please see #340.

**Comment by karimainine** [comment]
Thanks albinsunnanbo, the request is originating from https://hostname/AuthServices/SignIn. However, like Anders suggested, the pages are being served over http off the load balancer. 
Thanks Anders, I agree that a "PublicOrigin" option would make life easier in some cases. Similar to the assertionConsumerServiceUrl option in version 0.7.2, where the full URL can be set manually. As I have a deadline and need this done quickly, I will check with the networks team to see if they can insert a X-Forwarded-Proto https header to all http requests from the server.

**Comment by albinsunnanbo** [comment]
If you are in a hurry and can accept running a custom build you can change the uri scheme on `ApplicationUrl = new Uri(url, applicationPath);`in HttpRequestData.cs:51 (In method Init)
It looks like that should be enough, but @AndersAbel may have a clue if any other parts of the code needs to be modified.

**Comment by karimainine** [comment]
Thanks for the suggestion Albin. I am not very comfortable at this stage of the project to put in a custom build. I have been able to work with the networks team to get the pages served as https from the F5 irule. Through the network inspection viewer in Google Chrome, I can confirm that the application goes to https://hostname/AuthServices/SignIn but the AssertionConsumerServiceURL is still http://hostname/AuthServices/Acs. Any ideas?

**Comment by karimainine** [comment]
I checked with networks again and I can see now that the load balancer adds a header HTTP_FRONT_END_HTTPS=on. HTTPS variable is still off. Having said that, the originating request does come from https://hostname/AuthServices/SignIn.

**Comment by AndersAbel** [comment]
AuthServices does not recognize the HTTP_FRONT_END_HTTPS header, so that won't work. There is a PR in #331 to fix this, but it has some issues that need to be fixed before it can be merged.

**Comment by karimainine** [comment]
Thanks Anders, would it recognise x-forwarded-proto?

**Comment by AndersAbel** [comment]
No, it doesn't look at the headers at all. But it looks like those are fairly standard so I added an issue #363 about it. Until either #363 or #340 is solved there is no support for a load balancer that doesn't use the exact same URL for connecting to the internal server as is used by the client.
