### ISSUE TITLE
Support for service provider certificate rollover

### ISSUE THREAD

**Issue by explunit** [KentorIT/authservices#355]
I started a branch to support key rollover on the service provider certificate and wanted to validate several assumptions before I go too far with one approach:

Current situation: today we have one `ServiceCertificate` property that's used for decryption of inbound assertions if needed. It can be [read from config](https://github.com/KentorIT/authservices/blob/master/doc/Configuration.md#servicecertificate-element), e.g.

```
<serviceCertificate fileName="Kentor.AuthServices.Tests2.pfx" />
<identityProviders>
...
```

Two basic questions:
 1. Once #95 is implemented, do we want to support using a different certificate for signing requests vs. the one used for decryption?
 1. Do we want to configure the certificates as one list with different properties to indicate their purpose and whether they are the active cert? something like
```
<serviceCertificates>
  <serviceCertificate fileName="cert1.pfx" keyType="Encryption" active="true"  /> <!--published in metadata -->
  <serviceCertificate fileName="cert2.pfx" keyType="Signing" active="true" /> <!--published in metadata -->
  <serviceCertificate fileName="old-cert1.pfx" keyType="Encryption" active="false"  /> <!-- still accepted for use until expired, but no longer published -->
</serviceCertificates>
```

I'm assuming the answer is "Yes" to both but I thought it was worth asking. I'm sure the above example is not exact, but should give an idea of what I was thinking.

And the default would be active=true and keyType is unspecified, so the simple case when used for both signing & encryption and no rollover in progress:
```
<serviceCertificates>
  <serviceCertificate fileName="cert1.pfx"  />
</serviceCertificates>
```

This would be a breaking change vs. 0.14 but I assume this is OK until 1.0.

For comparison:
https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPMultipleCredentials

**Comment by AndersAbel** [comment]
Thanks for looking into this.

1. Yes, I think we should support it, as well as support a scenario where one certificate is used for both purposes.
2. Yes, that's a good idea.

I like the basic setup of your example config. A few minor thoughts:

* The parent element should be `<serviceCertificates>` as you've done, but the child elements can be named `<add>`. That would follow how federations and identity providers are configured.
* The `<add>` element could subclass the existing `CertificateElement` type that is used for idp certificates. The derived class just needs to add the active and use/keyType flag. That would reuse support for both loading cert store and from file (including web root relative file names).
* I'd prefer if the `keyType` attribute is renamed to `use` which is the term in the metadata, as well as in the Shib example you link to. There is an existing enum `System.IdentityModel.Metadata.KeyType` that could be used, but it has one drawback: To allow usage for both signing and encryption it should be left out, or set to "unspecified" which I find a bit confusing. Maybe an own enum is better? It can be value compatible with the existing, but with 0=Both.
* There is one more case that's needed for rollover: use="Signing" and active="false". That would publish the key in metadata but the SP shouldn't use it to sign. It's used in preparation for switch-over, to inform the Idps of the new, yet not active key.
* With use="Both" and active="false" the key should be accepted for decryption, and published in metadata with use="signing".

It's indeed a breaking change to 0.14.0, but I'd rather take it ASAP before going to 1.0.0.

**Comment by explunit** [comment]
_Following up on the discussion of how different combinations get used and/or published in metadata, here's my current thinking_

`Active` (True/False) seems to create a lot of confusion, at least in my mind. I'm thinking `Status` (Current/Future) instead.

(Row number is for easier discussion -- not part of config or object model)

Row | Use | Status | Published in Metatadata | Used by AuthServices
------------ | ------------- | ------------- | ------------- | -------------
1 | Both | Current | Unspecified _unless Future key exists_, then Signing | Yes 
2 | Both | Future | Unspecified | For decryption only 
3 | Signing | Current | Signing | Yes 
4 | Signing | Future | Signing | No 
5 | Encryption | Current | Encryption _unless Future key exists_ then not published | Yes 
6 | Encryption | Future | Encryption | Yes 


As another comparison point, [SimpleSamlPHP docs](https://simplesamlphp.org/docs/stable/saml:keyrollover) say:
> When the new key is added, simpleSAMLphp will attempt to use both the new key and the old key for decryption of messages, but only the old key will be used for signing messages. The metadata will be updated to list the new key for signing and encryption, and the old key will no longer listed as available for encryption. This ensures that both those entities that use your old metadata and those that use your new metadata will be able to send and receive messages from you.

This seems compatible with the first two rows of the table above.

Unfortunately, the SAML spec itself is silent on how rollover should be accomplished. If someone finds a definitive guide, let me know. It also seems there is variation in how Idp's support rollover, so I'm tempted to also include a `MetadataPublishOverride` property of each `ServiceCertificate`. These would be the enum values:
 * `None` (published according to the rules in the table above)
 * `PublishUnspecified`
 * `PublishEncryption`
 * `PublishSigning`
 * `DoNotPublish`

The above is all very complex, but the simplest case of rollover using default values of properties would be like this:

#### 0 - Initial state
```
<serviceCertificates>
  <add fileName="cert1.pfx"  />
</serviceCertificates>
```
Metadata has one key with no use specified

#### 1 - Add the new key
```
<serviceCertificates>
  <add fileName="cert1.pfx"  />
  <add Status="Future" fileName="cert1-new.pfx"  />
</serviceCertificates>
```
 * cert1 is published as use=Signing and we continue to use it for Signing outbound requests and to decrypt inbound requests
 * cert1-new is published with no use specified and we use it to decrypt inbound requests (i.e. we might try to decrypt with both certs because we can't control the timing of Idp updates)

#### 2 - Wait for x hours/days

#### 3 - Make new key the current key
```
<serviceCertificates>
  <add fileName="cert1-new.pfx"  />
</serviceCertificates>
```

cert1-new is published with no use specified

**Comment by explunit** [comment]
In-progress branch here: https://github.com/explunit/authservices/compare/explicit-config-conversion...explunit:service-cert-rollover?expand=1

See e.g. SPOptionsTests.cs for the unit test version of most of the above rules

**Comment by AndersAbel** [comment]
> The above is all very complex

Yes, but I've think you just simplified it a lot and found a model that will work. I really like that you have got the "happy path" with single-key rollover so simple to do.

Adding a MetadataPublishOverride would allow advanced users to have some more flexibility, but still let most users just ignore it.

From me it's just a huge thumbs up!
