### ISSUE TITLE
WantAssertionSigned in SP metadata

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#372]

**Comment by eppyjerk** [comment]
Hey Anders.  Will this enhancement allow me to deny any requests that are not signed from the Idp?  Thanks for the awesome work.

**Comment by AndersAbel** [comment]
@eppyjerk This change only affects the metadata. However AuthServices already requires incoming responses to be properly signed by the Idp. Either the entire Response has to be signed, or all contained assertions have to be signed. If not, AuthServices stops processing and throws an error.
