### ISSUE TITLE
AssertionConsumerServiceURL customization

### ISSUE THREAD

**Issue by cristiano-degiorgis** [KentorIT/authservices#381]
I did not find a parameter within the configuration to specify the 
 EntityDescriptor -> SPSSODescriptor -> AssertionConsumerService -> Location and/or
AssertionConsumerServiceURL within the saml2p:AuthnRequest.

I assume the url has been calculated on fly by the library according to the application hosting url.
for ex: if my app has been hosted at http://localhost:54591 the EntityDescriptor -> SPSSODescriptor -> AssertionConsumerService -> Location will be http://localhost:54591/AuthServices/Acs
I'm a right?
If so, since our production environment use a load balancer in offload mode, the https is handled at the balancer level, while the server that host the application receives the request from the balancer in http so I assume the autogenerated Location url will be in http instead of https.
I could fix manually the xml file generated on fly by the http://localhost:54591/AuthServices endpoint, but how can I modify the value within the saml request?
Is there a way to fix that issue?

**Comment by AndersAbel** [comment]
This is a known problem, see #340.
