### ISSUE TITLE
InCommon federation throws exception on startup

### ISSUE THREAD

**Issue by jpsullivan** [KentorIT/authservices#386]
This is in regards to a [short conversation](https://twitter.com/jaysche_/status/682086874102558720) we had earlier, and I've finally had the time to test this out. Sadly, it seems that setting InCommon as the federation throws an exception relating to a duplicate key entry.

Sample code:
```c#
var spOptions = CreateServiceProviderOptions(settings);
var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
{
    SPOptions = spOptions
};

new Federation(new Uri("http://md.incommon.org/InCommon/InCommon-metadata.xml"), true, authServicesOptions);
```

Throws the following exception on startup.
```
[ArgumentException: An entry with the same key already exists.]
   System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) +52
   System.Collections.Generic.SortedList`2.Add(TKey key, TValue value) +6869689
   System.IdentityModel.Metadata.MetadataSerializer.ReadServiceProviderSingleSignOnDescriptor(XmlReader reader) +703
   System.IdentityModel.Metadata.MetadataSerializer.ReadEntityDescriptor(XmlReader inputReader, SecurityTokenResolver tokenResolver) +350
   System.IdentityModel.Metadata.MetadataSerializer.ReadEntitiesDescriptor(XmlReader reader, SecurityTokenResolver tokenResolver) +275
   System.IdentityModel.Metadata.MetadataSerializer.ReadMetadataCore(XmlReader reader, SecurityTokenResolver tokenResolver) +71
   System.IdentityModel.Metadata.MetadataSerializer.ReadMetadata(XmlReader reader, SecurityTokenResolver tokenResolver) +67
   Kentor.AuthServices.Metadata.MetadataLoader.Load(Stream metadataStream) +149
   Kentor.AuthServices.Metadata.MetadataLoader.Load(Uri metadataUrl) +77
   Kentor.AuthServices.Metadata.MetadataLoader.LoadFederation(Uri metadataUrl) +26
   Kentor.AuthServices.Federation.LoadMetadata() +75
   Kentor.AuthServices.Federation..ctor(Uri metadataUrl, Boolean allowUnsolicitedAuthnResponse, IOptions options) +91
   SCLIntraWebMVC.Startup.CreateAuthServicesOptions(Saml2Settings settings) in ...
```

From a quick glance, the exception is being thrown from MetadataSerializer.cs found within the System.Identity namespace. At this point, I'm not entirely sure if this is an AuthServices issue or a System.Identity one. Nonetheless, since nobody else has really mentioned using InCommon, I figured it would be nice to get a conversation going.

Thanks for all your support and for releasing such a great library!

**Comment by AndersAbel** [comment]
Thanks for the error report. We have a few real life metadata files as part of the unit tests, so I'll add the incommon metadata too to that set and find out why it doesn't work.

I assume it's the metadata listed on https://spaces.internet2.edu/display/InCFederation/Metadata+Aggregates as main that's the current one?

It looks like an issue in System.IdentityModel, but it can probably be fixed. The MetadataSerializer has a few issues that we've worked around. We have overridden a few virtual methods to fix most things, but there is also a filter that drops part of the XML that the MetadataSerializer can't handle.

**Comment by AndersAbel** [comment]
I had a brief look and I think there's an SP in the metadata that has two AssertionConsumerServices with the same index. Since we really don't care about the other SPs in a federation I think we could just filter out the offending XML.

**Comment by jpsullivan** [comment]
Agreed, that sounds like a fine solution to me. Thanks for the quick response!

**Comment by AndersAbel** [comment]
There's indeed an EntityDescriptor in there that contains two AssertionConsumerService entries with the same index:

````
<md:AssertionConsumerService xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://pcardstage.finance.ucla.edu/Shibboleth.sso/SAML2/POST" index="2"/>
<md:AssertionConsumerService xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://pcardstage.finance.ucla.edu/Shibboleth.sso/SAML2/POST" index="2"/>
````

According to the SAML metadata spec section 2.2.3 that's not allowed:

> A required attribute that assigns a unique integer value to the endpoint so that it can be referenced in a protocol message. The index value need only be unique within a collection of like elements contained within the same parent element (i.e., they need not be unique across the entire instance).

It's probably possible to work around it, but I'd prefer to not have to introduce workarounds because someone else is not following the standard. But I do understand that InCommon is not any "someone else". Nevertheless I think it would be great to get in touch with InCommon and ask about that particular entry. Would you mind doing that?

If I comment out one of those lines there's still an issue with an idp that has no compatible sso service endpoint. I'll commit a fix to that bug together with the incommon tests shortly.

**Comment by jpsullivan** [comment]
I can definitely assist with that. I'll reach out to one of our InC contacts and see what they can do. I'll ping back as soon as I hear something back. 

Thanks again!

**Comment by AndersAbel** [comment]
Great, I'll wait for your response then. The fix for when the Idp has no compatible SSO Service endpoint is included in version 0.15.0 that I released yesterday.

**Comment by jpsullivan** [comment]
Excellent, I'll test that out asap. As for InCommon themselves, I have sent an email their way. I'll be sure to ping back once they respond.

**Comment by jpsullivan** [comment]
Here's a response from Tom Scovo, Operations Manager at InCommon regarding this issue:

> Thank you for bringing this to our attention. I have confirmed that you are correct, there is a bug in metadata. We are looking into it now. I will get back to you.

**Comment by AndersAbel** [comment]
That's great news. I assume that means that we can now close this issue?

**Comment by jpsullivan** [comment]
Yeah, I think it's safe to say we're in the clear here. Thanks again for all your help with this!

**Comment by jpsullivan** [comment]
Hey Anders,

So it seems that InCommon just did a major migration to their infrastructure to support their "eduGain" protocol. I'm unsure of the specifics, but it seems that this problem just started popping up again. At face value, the metadata has now grown from 17MB to nearly 32MB.

I've been trying to figure out what key is being duplicated, but I can't seem to get any information from the exception, and .NET source stepping seems to be failing on my machine. Any tips for what you did to find the previous duplicate AssertionConsumerService entry?

Thanks again for all your help.

**Comment by AndersAbel** [comment]
As this issue contained a fix, I'm closing it and opening another one (#408) for handling the duplicate index endpoints.
