### ISSUE TITLE
The specified network password is not correct.

### ISSUE THREAD

**Issue by ajit136** [KentorIT/authservices#387]
[CryptographicException: The specified network password is not correct.
]
   System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr) +33
   System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromFile(String fileName, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx) +0
   System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags) +218
   System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName) +61
   System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName) +55
   Kentor.AuthServices.Configuration.CertificateElement.LoadCertificate() +156
   Kentor.AuthServices.IdentityProvider..ctor(IdentityProviderElement config, ISPOptions spOptions) +337
   Kentor.AuthServices.Configuration.IdentityProviderCollection.RegisterIdentityProviders(IOptions options) +182
   Kentor.AuthServices.Configuration.Options.get_FromConfiguration() +114
   Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.Init(HttpApplication context) +191
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +418
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): The specified network password is not correct.
]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9913572
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254

**Comment by explunit** [comment]
@ajit136 does it seem like your scenario could be like this? http://stackoverflow.com/questions/9951729/x509certificate-constructor-exception

Perhaps you could try the IIS load user profile setting (the first answer in the link above) to see if that resolves it? 

If so, we may want to make a code change here:
https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/Configuration/CertificateElement.cs#L113

To specify `X509KeyStorageFlags.MachineKeySet` when loading from file?

**Comment by AndersAbel** [comment]
@ajit136 Where are you hosting this? Is it some kind of shared environment? Do you get the same problem when running locally on a development machine? Also, do you have a password on the pfx file?

**Comment by ajit136** [comment]
Yeah there is a password on the pfx file and this error is coming in development machine.

**Comment by AndersAbel** [comment]
There is no support for having passwords on the .pfx file. If you want to store the certificate securely, you should use the certificate manager and add it to a store with proper access rights for the application pool user.

**Comment by shashank24** [comment]
I am unable to export the certificate from windows server with out password. How would I handle this scenario to work with kentor? Should I choose owin implementation and use the following code to get the certificate

![image](https://cloud.githubusercontent.com/assets/8527578/15726440/c981ff22-2805-11e6-808f-bfd9cb628f14.png)

![image](https://cloud.githubusercontent.com/assets/8527578/15726443/cf90e41e-2805-11e6-8530-616bd7167f83.png)

Also posted my question in stack over flow
http://stackoverflow.com/questions/8286110/asp-net-the-specified-network-password-is-not-correct

**Comment by AndersAbel** [comment]
@shashank24 For a production environment you should use the certificate store and not a pfx file.
