### ISSUE TITLE
No Saml2 Response found

### ISSUE THREAD

**Issue by cornem** [KentorIT/authservices#390]
@AndersAbel Continued from #379 

In my fork I noticed I had added this to the request (by default):

    x.AddAttributeIfNotNullOrEmpty("ProtocolBinding", Saml2Binding.HttpPostUri);

I guess I did that on purpose, because I think the IdP just redirects with query string parameters.
This is what I get back from the IdP:

    HTTP/1.1 302 Found
    Date: Wed, 20 Jan 2016 10:43:32 GMT
    Server: Apache
    Strict-Transport-Security: max-age=31536000
    Cache-control: no-cache, no-store
    Pragma: no-cache
    Location: https://my.serviceprovider.com/AuthServices/Acs?SAMLResponse=fZFba8JAEIXf%2ByvCvueqFVlMRCrFUAv1Uot9KWsyjaHJbLoz0dZf33ij4oOPA2fOme9Mr%2F9TFtYGDOUaQ%2BE7nrAAE53mmIXidf5od0U%2FuuuRKougklOgSiOBNQTiHBUfttbMFUnXXeui3Gqdkg1pBo7a1Qa2sKKcgRwEdgc1r2dgNnkC5A4SElY8DMXHNB79ehOK36bdTy8dw2T1xC%2BjZZZ9LxsFUQ0xEivkUASe37E93w68ue%2FJdku2Aqd933kX1uLMEOwZGiokebw6FLVBqRXlJFGVQJITORs8j2UjlZXRrBNdiOgIKQ%2BB5tLhtoEiArMvQkSKoICEbXIA2QA4X4CYU4PuYNFzL%2F2jc6UzVlzT1figU7AWqqjhdjYd1Ke3pGCEG51i%2Fo3dq99Ffw%3D%3D&RelayState=bvJrSBbyydEperAFWXvSEqoy0gdTflFYgseQO3sqQXb-UjGUcIASu09s&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=vMRvJE3aY2GZ7DxgawC30kr4m1KuMy7i9ZUavb3TiiG6o8GMcSriA9AfRlwCA9qG10W8GR77ERN6XFFHbZG29uI1zuuJUlYsGTVZikCKboRjGF4OCOverZF54k2Aqh3qtOGLUnkJol%2FGplJCp8SLMtEddixw20LoBrymo6%2FCuIk%3D
    Content-Length: 0
    Keep-Alive: timeout=5, max=1000
    Connection: Keep-Alive

Am I missing something here or is the IdP not honoring my metadata (`<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://my.serviceprovider.com/AuthServices/Acs" index="0" isDefault="true" />`)?

**Comment by AndersAbel** [comment]
Looks like that might be needed in this case.

The response you show is using the Saml2Redirect binding. That is not supported by AuthServices for incoming Saml2Response. The problem with Redirect is that using a URL param limits the length of the response, so it is not recommended to use for responses.

AuthServices does support POST or (from 0.15.0) Artifact binding for the incoming response.

It indeed looks like the idp is not honoring your metadata. Adding the binding to the AuthnRequest would require some config option to be done. With no binding specified in the AuthnRequest, the idp is free to choose among those listed in the metadata. Adding a hard coded HttpPostUri would prohibit use of artifact binding.

In the first place I think you should check with your idp why it doesn't honor your metadata.

**Comment by cornem** [comment]
I have contacted the IdP and will report back if they have anything
interesting to share.

I'm not recommending hard-coding HttpPostUri for the same reason you're
suggesting. That's also one of the reasons I never made a pull request with
my own changes. A config option is probably the best solution if the IdP
cannot or will honor our metadata.

Kind regards,

Corné Meerkerk



KvK: 08164242

**Comment by AndersAbel** [comment]
Added the config option to #396 which is about enabling bindings. Closing this as done.
