### ISSUE TITLE
Integration with Active Directory Federation Services

### ISSUE THREAD

**Issue by mnaoumov** [KentorIT/authservices#392]
I am using the library to provide SAML SSO capabilities in my work project and I could successfully integrate it with Okta using your documentation.

Other client asked to integrate with their AD FS 2.0 (Active Directory Federation Services) and provided a metadata.xml and asked me to provide some file back to them. The only metadata url I found so far is https://my-server/AuthServices which downloads browser-unfriendly version of some metadata.

```
<?xml version="1.0" encoding="UTF-8"?>
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_7f22d257-4c07-4293-9ec3-527543446a07" entityID="https://my-server/AuthServices/" cacheDuration="PT1H">
  <SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://my-server/AuthServices/Acs" index="0" isDefault="true" />
  </SPSSODescriptor>
</EntityDescriptor>
```

but when I tried to import this file into our staging AD FS 2.0 server I get the error

![adfs-error](https://cloud.githubusercontent.com/assets/735878/12523615/9c0fa7f8-c160-11e5-800d-d86236f90820.png)

Also customer said that this metadata file misses signing-cert or assertion/logout endpoints configured.

What am I missing?

**Comment by explunit** [comment]
Request signing (and showing the configured keys in the metadata) was adding in v0.15, released several days ago. What version are you running?

**Comment by mnaoumov** [comment]
@explunit Thanks for an immediate feedback. I was using 0.13 version. I will try to switch to 0.15 version and recheck it shortly

**Comment by mnaoumov** [comment]
Thanks, this helped! The only thing is missing is logout endpoint, but as far as I understand this requires #29

**Comment by AndersAbel** [comment]
Single Logout is in progress, should be released within a week.
