### ISSUE TITLE
NamedId format

### ISSUE THREAD

**Issue by Bidou44** [KentorIT/authservices#394]
I saw that the *nameidformat* is not yet implemented on the AuthnRequest. In my current project, I have to set it as *persisent*, so that my IdentityProvider gives a unique NameIdentifier back. I implemented this functionality and then created a pull request: https://github.com/KentorIT/authservices/pull/393.

This pull request does not work because I didnt write Unit Test for now. I cannot invest too much time for this integration, so my question is: what are the condition so that you merge this pull request to the main branch? Or could you write the test yourself? Since you know the code better that I do, it would probably get a lot faster...

**Comment by AndersAbel** [comment]
This is actually on my todo list for today, as I need it for a customer. I think your code looks nice and clean so I'll add make the required adjustments and merge it.

**Comment by AndersAbel** [comment]
This is a duplicate to #365,

**Comment by AndersAbel** [comment]
The test coverage for your code is really good - it's just the lookup function for enums to strings that lacks coverage. It's som simple that it's not worth doing tests for it, so I marked it with [ExcludeFromCodeCoverage]. Problem solved.
