### ISSUE TITLE
Ignore SPSSODescriptor on metadata parsing

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#408]
There's been issues with the parsing the InCommon metadata (#386), one of them is due to SPs having duplicate index numbers on their AssertionConsumerServices. Since we're not interested in the other SPs anyways we could just skip over them when parsing metadata.

Duplicate indexes is actually a violation of the SAML standard:
>A required attribute that assigns a unique integer value to the endpoint so that it can be referenced in a protocol message. The index value need only be unique within a collection of like elements contained within the same parent element (i.e., they need not be unique across the entire instance).

But if other implementations can handle duplicate indexes it looks like we're asking for too much trouble if we start blocking when they are found.

Override the `ReadServiceProviderSingleSignOnDescriptor()` method in `ExtendedMetadataSerializer` and loop the reader until an end SPSSODescriptor element is found.

**Comment by jpsullivan** [comment]
I've begun working on this. So far, I have an implementation for the `ReadServiceProviderSingleSignOnDescriptor()` method, but I'm now seeing that adding an Organization URL is now throwing the same error within the `ReadOrganization()` method. I'd like to avoid copying the entire method and adding a check when inserting new organization URL's, but I'm not entirely sure what the alternative would be.
