### ISSUE TITLE
CheckSignature with SHA256 

### ISSUE THREAD

**Issue by liwerants** [KentorIT/authservices#412]
I have a ServiceCertificate which is the StubIdp you provide for test, an Identity Provider with a signing SHA256 certificate, and I added the Options.GlobalEnableSha256XmlSignatures(). In the zip in attachments, you can find an example of a samlp response from my IDP.
Unfortunately, I can't pass through the CheckSignature, and I have a CryptographicException in the Saml2Response.retrieveAssertionElements method. 
To be sure, I tried to decrypt the response with the private key of the StubIdp certificate and it works fine (https://www.samltool.com/attributes.php). 
Is there something I miss?

Thanks for your help !

[test_serviceprovider.zip](https://github.com/KentorIT/authservices/files/141734/test_serviceprovider.zip)

**Comment by AndersAbel** [comment]
Decrypting and checking signature are two different operations. Just because one works doesn't mean the other will work.

The samlresponse.xml in the zip file looks pretty printed. Have you done that after you received the response? The signature on the response will only validate if the XML is formatted exactly the same as when the signature was added.

**Comment by liwerants** [comment]
Thanks for your response. My description was maybe not very clear but **I have two problems** on the signature and the decryption. I did some debug on the .NET framework and I think the problems are with it. 

For the signature : the signedXML have a sha256 signature method but the keyIdentifier is a RSACryptoServiceProvider which have always a sha1 signature method. So the deformatter can't work. If I force the sha1 on the signedXML, it works perfectly. I must conclude that this method can't work with sha256 signature.
For the decryption : the method DecryptDocument of the EncryptedXml class search for enc:EncryptedData node (http://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/encryptedxml.cs,32634f0d8234cc25). But the encryptedassertion of my response have a xenc prefix (and not enc) as it is defined in the SAML 2.0 specifications. 

==> Unfortunately, in that version, I think your library can't work for my context :-(.

**Comment by AndersAbel** [comment]
The prefix of XML doesn't matter - the important thing is the namespace. Internally it uses the prefix `enc` but it registers that prefix at http://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/encryptedxml.cs,608.

The algorithm of the keyidentifier is irrelevant - it's the actual algorithm of the signature that is used.

As I said previously, it looks like the xml you show is pretty printed. Is that something that has been done **after** the signature was added? In that case it won't very work as the XML has been changed (which is exactly what a signature should warn about)

**Comment by liwerants** [comment]
Yes ok, you're right for the signature. I will try again in a real saml process. 
But I don't understand why the decryption does not work. I have an indexoutofrange exception in the decryptdocument `foreach (XmlNode encryptedDataNode in encryptedDataList)`

**Comment by liwerants** [comment]
It's my debug of the list, never mind :-)

**Comment by liwerants** [comment]
I still have a CryptographicException during the decryption of the EncryptedKey : incorrect key. I'm 100% sure of my certificate.

**Comment by liwerants** [comment]
According to my google search, it has to be with the key usage of the certificate : "X509v3 Key Usage: 80", only for signature purpose. I am a beginner in cryptography...

**Comment by AndersAbel** [comment]
Looks like you might have found an issue in the encrypted xml handling.

What is the exact exception message and stack trace of the exception?

**Comment by liwerants** [comment]
Hi @AndersAbel, I don't think it's an issue, but an exception message which could be more dev-friendly :-). My first service certificate was a one only for signature purpose. If you want a certificate for encryption/decryption, you must create it with the rights options (key usage). If you use a certificate with only signature key usage (X509v3 Key Usage: 80), you will have a CryptographicException with a "bad key" message. You can find more information on the specification page (http://tools.ietf.org/html/rfc5280#section-4.2.1.3). 

The exception is thrown from the extern method DecryptKey of the RSACryptoServiceProvider class (http://referencesource.microsoft.com/#mscorlib/system/security/cryptography/rsacryptoserviceprovider.cs,2dadef9c9933fa7c).

Again, thanks for your help, and your very helpful library !

**Comment by AndersAbel** [comment]
This should be checked when the configuration is loaded. I think that the best place would be a check in the setters of ServiceCertificate so that Use cannot be set to a value that is inconsistent with the certificate's usage flags.

Thanks for tracking down the error!

**Comment by explunit** [comment]
I spent some time on how we would know that a given certificate is not valid for encryption/decryption, and so far have not found anything definitive. See my StackOverflow question here: http://stackoverflow.com/questions/35816205/verify-certificate-is-valid-for-encryption-decryption

**Comment by explunit** [comment]
I suppose another hack would be to immediately encrypt & decrypt some simple xml during the cert configuration step and make sure it works.

**Comment by AndersAbel** [comment]
@explunit That's a brilliant way to handle it. I have suggestion for an xml document to use as an example: `<xml/>`
