### ISSUE TITLE
How to delete Cookies (Ping Federate)

### ISSUE THREAD

**Issue by Battozxz** [KentorIT/authservices#413]
I'm currently working on a project (as a SP) and need to delete a persistent cookie that the idP store in the WebBrowser, FederatedAuthentification.SessionAuthenticationModule.SignOut() doesn't delete that cookie. What can i do?

**Comment by albinsunnanbo** [comment]
You should call the Logout authservices command with the /Logout Url on 0.17.0
This invokes the CommandResultHttpExtension.SignInOrOutSessionAuthenticationModule that does the heavy lifting of removing cookies and stuff.

**Comment by Battozxz** [comment]
I've tried calling /Logout but the cookie doesn't get deleted from my browser. The cookie itself (a non-persistent cookie) is issued by the IDP which is not on the same domain as the SP I'm working on. Is there any other way to remove this cookie? (I'm aware of the same-origin policy browsers use to prevent these operations)

**Comment by albinsunnanbo** [comment]
Ah, sorry, I read to quickly.
Removing the IDP cookie is not possible in general.
However if your IDP supports Single Logout you could probably use the newly (Authservices 0.17.0) introduced Single Logout functionality to tell the IDP to remove it's cookie.

**Comment by AndersAbel** [comment]
Single Logout is used to solve this. It makes the SP redirect to the Idp, so that the Idp cookie can be removed in the Idp's context. To enable SLO, you need to have a service certificate configured in AuthServices and the Idp metadata should contain at least one SingleLogoutService endpoint. You can also add the logout endpoint manually, but it's so fresh so it's not in the documentation yet.

**Comment by Battozxz** [comment]
My idp provider just confirmed that they don't have SLO enabled on their side.

Thank you very much for your help. This library is amazing

**Comment by hungleon2112** [comment]
Hi @AndersAbel ,

I'm using Okta as IDP, and I enabled Single Log Out then I received the Identity Provider Single Logout URL.

I'm trying to use Log Out functionality in Kentor, but the Cookies wasn't removed. After Log Out, when I tried to click Login, it login automatically with the old credential.

Please help!

**Comment by AndersAbel** [comment]
@hungleon2112 Open a new issue instead of continuing on an old, closed one. And describe more in detail what you are trying and where you are stuck.
