### ISSUE TITLE
Retrieve email from OneLogin

### ISSUE THREAD

**Issue by shuppert** [KentorIT/authservices#414]
The newly added SampleIdentityServer3 is great and helped me locate my configuration issues.  I was able to get everything working with OneLogin and the client-side path.  I can see in the IdentityServer log that the email address is being sent back with the SAML in the <saml:NameID>  node of the XML.  Is there something built into the AuthServices library to extract values from the SAML and convert them into claims or would this require customization?  I see the generic OpenID values (sid, sub, auth_time, idp, but not the email).

-Scott

**Comment by AndersAbel** [comment]
The Subject NameID is converted to a claim of type `ClaimType.NameIdentifier`. I assume that IdentityServer3 is not preserving it as it doesn't expect to find an email there.

You can register a [ClaimsAuthenticationManager](https://github.com/KentorIT/authservices/blob/master/doc/ClaimsAuthenticationManager.md) with AuthServices to inspect and modify the incoming claim. Use that to add a new claim to the identity with type `ClaimType.Email`, where you just copy the address from the `ClaimType.NameIdentifier` claim. That should make IdSrv3 pick up the email.

**Comment by shuppert** [comment]
I tried what you recommended and struggled with creating a ClaimsAuthenticationManager and registering a custom IHttpModule that called it but it was only called when the IdentityServer was instantiated and not after the SAML authorization was returned.

I was able to retrieve the email address I was looking for by modifying my UserService.  The email address I expected was in the user.Logins.FirstOrDefault().ProviderKey.

-Scott

**Comment by AndersAbel** [comment]
Great that you found a solution on the identity server side. But it looks like you took a wrong turn somewhere with the ClaimsAuthenticationManager. No custom IHttpModule is needed. The ClaimsAuthenticationManager should be registered with he IdentityModel configuration used by AuthServices. Then AuthServices will automatically call it when processing incoming claims.

**Comment by shuppert** [comment]
The way I implemented it seemed like the hard way.  I can access the email address but I'm having issues getting to the other claims.  Last week I tried registering the ClaimsAuthenticationManager in the web.config and it was never called which was why I tried the IHttpModule.  I'll try registering the ClaimsAuthenticationManager again in code.
-Scott

**Comment by AndersAbel** [comment]
If you are after the other claims a `ClaimsAuthenticationManager` won't help you. I suggested it as a way to handle that the e-mail wasn't found in the normal e-mail claim. To get the other claims you should use a mechanism in IdentityServer3 for transforming the incoming claims.

**Comment by shuppert** [comment]
That's interesting.  I figured out how to register my ClaimsAuthenticationManager in code but I was only able to influence the email claim but not the other identity claims.  It seems like I should be able to manipulate them all there.  I'm trying to override the preferred_username that shows up in the ID Token with something more meaningful as it appears to contain a GUID that IdentityServer is assigning.
