### ISSUE TITLE
Loading web.config in OWIN and using with Identity Server

### ISSUE THREAD

**Issue by parkinsona** [KentorIT/authservices#415]
Hi,

I've seen that there is an options to load the Kentor config from web.config which would be really helpful. I have a few questions regarding this.

1. When I setup the KentorauthServicesAuthenticationOtpions in code, I set SignInAsAuthenticationType, AuthenticationType and Caption. I cant' see where I can add these in web.config.

``` c#
            var oktaAuthServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
            {
                SPOptions = new SPOptions()
                {     
                     
                    AuthenticateRequestSigningBehavior = SigningBehavior.Never,
                    EntityId = new EntityId("https://myentityid") // Audience Restriction
                     ,                
                },
                 
                SignInAsAuthenticationType = signInAsType,                 
                AuthenticationType = "okta", // this is the "idp" - identity provider - that you can refer to throughout identity server
                Caption = "Okta",  // this is the caption for the button or option that a user might see to prompt them for this login option             
            };
```

2. I don't quite understand how multiple identity providers are supposed to work. From what I've played with, it looks like it will just pick the first provider that is added. 

What I'm wanting to do is add 2 different SAML providers and in identity server I want these 2 appear as 2 separate external login options. Am I supposed to do something like this:

``` c#
  var oktaAuthServicesOptionsProv1 = new KentorAuthServicesAuthenticationOptions(false);
  var oktaAuthServicesOptionsProv2 = new KentorAuthServicesAuthenticationOptions(false);
// Add extra options for the providers
 app.UseKentorAuthServicesAuthentication(oktaAuthServicesOptionsProv1);
 app.UseKentorAuthServicesAuthentication(oktaAuthServicesOptionsProv2);
```
Or am I supposed to just add 1 authOptions object with different identity providers.
If its the later, how do you request the different providers via their idp value?

**Comment by AndersAbel** [comment]
Those three options (SignInAsAuthenticationType, AuthenticationType and Caption) are specific to the Owin middleware and are not possible to set from the config file. You can however combine them:

````
new KentorAuthServicesAuthenticationOptions(true) // loads from file
{
  // Set owin specific config in code.
  SignInAsAuthenticationType = signInAsType,
  AuthenticationType = "okta",
  Caption = "Okta"
}
````

IdentityServer only renders one button for each middleware. If you want IdSrv to show two different Idps as different login alternatives you have to instantiate the middleware twice, with two different options objects. That will have to be done in code.

It should also be possible to have one middleware instance and register two identity providers with it. But unfortunately that's not possible until #182 is solved.

For a more detailed discussion IdSrv3 and multiple Okta instances, see #356.

**Comment by parkinsona** [comment]
Thanks for the link on the multiple Okta instances, that was very helpful. I'm now able to set up 2 providers through code by setting the ModulePath in SPOptions for each of the separate middleware instances.

Is there a way to store 2 different configs? One for IDP 1 and another for IDP 2?
The main settings that would need to be different are the ModulePaths and the list of Identity Providers added.

**Comment by AndersAbel** [comment]
The config file format only supports one instance, so if you want multiple instances you will have to do it in code.

A combination is also possible: Put the common stuff in the config file, then instantiate two options with `new KentorAuthServicesAuthenticationOptions(true)`. Finally set the modulepath and add the idp to each of the instantiated objects.

**Comment by parkinsona** [comment]
Thanks again. I had a feeling that was the approach I would have to take. Good to have it confirmed.
