### ISSUE TITLE
Restrict ReturnUrl to be local

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#417]
The ReturnUrl query parameter of the SignIn and Logout commands has no validation. That can be used as an open redirect. They should be limited to only allow local URLs. Note that when using the owin module and the ReturnUrl is specified in AuthenticationProperties non-local urls should be allowed as those are not directly set by the user but from code.

**Comment by JuraGHH** [comment]
How to limit ReturnUrl to local URLs only?

**Comment by squak** [comment]
As a workaround

In the global.asax add following to Application_Start()

```
Options.FromConfiguration.Notifications.AcsCommandResultCreated = (cr, c) => ForceRelativeUri(cr);
Options.FromConfiguration.Notifications.LogoutCommandResultCreated = ForceRelativeUri;
Options.FromConfiguration.Notifications.SignInCommandResultCreated = (cr, c) => ForceRelativeUri(cr);
```

Create following static void:
```
private static void ForceRelativeUri(CommandResult cr)
{
    if (cr.Location != null && cr.Location.IsAbsoluteUrl())
    {
        var pathAndQuery = cr.Location.MakeAbsoluteUri().PathAndQuery; // Call MakeAbsoluteUri because cr.Location contains relative Path

        cr.Location = new Uri(pathAndQuery, UriKind.Relative);
    }
}
```

Please your opinion.

**Comment by doormalena** [comment]
@AndersAbel 
Is there a possibility that you can implement this enhancement? We have an security audit finding for this which we need to resolve. We currently use the HTTP Module and MVC, not OWIN.

**Comment by squak** [comment]
Just to be complete create the following extension method
```
public static class UriExtensions
{
   /// <summary>
   /// Determine whether given Uri is an absolute Url or not
   /// </summary>
   /// <param name="uri">Uri to check</param>
   /// <returns>True of Uri contains an absolute Url otherwise false</returns>
   public static bool IsAbsoluteUrl(this Uri uri)
   {
	   return CheckRelativeAbsoluteUri(uri, UriKind.Absolute);
   }

   /// <summary>
   /// Determine whether given Uri is an relative Url or not
   /// </summary>
   /// <param name="uri">Uri to check</param>
   /// <returns>True of Uri contains an relative Url otherwise false</returns>
   public static bool IsRelativeUrl(this Uri uri)
   {
	   return CheckRelativeAbsoluteUri(uri, UriKind.Relative);
   }

   private static bool CheckRelativeAbsoluteUri(Uri uri, UriKind urikind)
   {
	   Uri result;
	   return Uri.TryCreate(uri.ToString(), urikind, out result);
   }

   /// <summary>
   /// Creates an absolute Uri
   /// </summary>
   /// <param name="uri">Uri to check</param>
   /// <returns>Absolute Uri</returns>
   public static Uri MakeAbsoluteUri(this Uri uri)
   {
	   Uri result;
	   Uri.TryCreate(uri.ToString(), UriKind.Absolute, out result);
	   return result;
   }
}
```

Notifications can also be used with OWIN:

In the sample project add following to CreateAuthServicesOptions()

```
...

authServicesOptions.IdentityProviders.Add(idp);

authServicesOptions.Notifications.AcsCommandResultCreated = (cr, c) => ForceRelativeUri(cr);
authServicesOptions.Notifications.LogoutCommandResultCreated = ForceRelativeUri;
authServicesOptions.Notifications.SignInCommandResultCreated = (cr, c) => ForceRelativeUri(cr);
	
...

return authServicesOptions;
```

**Comment by plequang** [comment]
Hi,

We have a problem with the way this issue has been solved.

I don't know if our application configuration is common or not, but this might interest other people.

Our application is made of an ASP.Net Web Api backend and a Single page web application, hosted at 2 different URLs.

The authentication flow is as follow : 

1. User agent load frontend from https://frontend.domain.com
2. Logon calls https://backend.domain.com/AuthServices/Signin?ReturnUrl=https://frontend.domain.com
3. User authenticate
4. User agent post to https://backend.domain.com/AuthServices/Acs
5. AcsCommand returns a redirect to http://frontend.domain.com

With latest fix, this doesn't work anymore, as frontend URL is not relative to backend.

One solution to fix our app could be to redirect to a backend URL, that will then redirect to the frontend, adding an extra redirection. 

Another solution could be to add a list of allowed return URLs in SPOptions, and check this list in the SignInCommand.

In the configuration, this could look like that:

```
<kentor.authServices returnUrl="xxxx" ...

    <returnUrls>
      <add url="https://frontend.domain.com" />
      <add url="https://frontend2.domain.com" />
    </returnUrls>
 
```

I can work on a PR to implement this second solution, if you think this is acceptable to have such a configuration.

I guess I should keep the `SPOptions.ReturnUrl` property as the default return URL.

**Comment by explunit** [comment]
If you do create a PR, the way we've been handling "compatibility" kind of things lately is to add a notification hook rather than another configuration setting. For example see https://github.com/KentorIT/authservices/pull/636/files

**Comment by AndersAbel** [comment]
I also think a notification is better than to further bloat the configuration. What need to be discussed though is how that notification would look. A simple function that gets the url as input and returns a bool does the trick, but there is considerable risk that ppl would just implement it as "return true". I like to design APIs so that they are hard to use wrong, but in this case I can't really come up with something that is both elegant and flexible. So unless someone else has a better idea I vote for a notification that returns a bool. And then that the current implementation is moved to be the default implementation of that notification.

**Comment by plequang** [comment]
After @explunit comment, I started to work on something that looks like what you vote for

```
        /// <summary>
        /// Notification called by the SignIn command to validate the ReturnUrl before initiating the SignIn sequence.
        /// Return true to indicate that you accept the ReturnUrl, false otherwise.
        /// Default validation accept only relative URLs.
        /// When false is returned, the SignIn command will throw an <see cref="InvalidOperationException"/>.
        /// </summary>
        public Func<string, bool> ValidateReturnUrl { get; set; }
```

Another approach could be inspired by CORS permissions: if the URL is relative, accept it without going through the notification. Else call the notification to validate an absolute URL, so something like :
```
public Func<string, bool> ValidateAbsoluteReturnUrl { get; set; }
```

**Comment by explunit** [comment]
I think either approach would work but I like your idea of allowing relative URLs and calling notification for absolute ones. With the notifications it becomes difficult to know where the code for the default implementation should live, and your idea bypasses that problem. We don't want AuthServicesNotifications.cs to be littered with "default" implementations for things that belong elsewhere in the codebase. We want it to have just the "do nothing" placeholder implementations. @AndersAbel please correct me if I'm wrong on this.

Note that it's not just the SignIn command that needs to call this.

**Comment by AndersAbel** [comment]
@explunit I was thinking of putting the default implementation in the notifications - I never saw the issue with things being in the wrong  place. But I think you're right. Having a default implementation that does too much might be a bit too much of magic. In this case I think the suggestion from @plequang is good - to only call the notification if it is an absolute URL. That will keep the default implementation to a simple "return false".
