### ISSUE TITLE
ADFS error when importing the Kentor-generated metadata

### ISSUE THREAD

**Issue by in10se** [KentorIT/authservices#419]
When I try to import the metadata into ADFS I get this error:

> An error occurred during an attempt to read the federation metadata.  Verify that the specified URL or host name is a valid federation metadata endpoint.
> 
> Verify your proxy server setting. For more information about how to verify your proxy server setting, see the AD FS Troubleshooting Guide (http://go.microsoft.com/fwlink/?LinkId=182180). 
> Error message: ID3276: The signing credentials cannot be resolved because signed XML does not contain a SecurityKeyIdentifier.

Note that my Kentor-enabled app works if I add it manually using the RP wizard.

Here's the metadata:

```
<?xml version="1.0" encoding="UTF-8"?>
<EntityDescriptor ID="_ae2dd083-d663-43a3-bd52-2dca818295e1" entityID="https://myapp.mydomain.com/auth" cacheDuration="PT1M" validUntil="2016-03-09T04:27:00Z">
   <Signature>
      <SignedInfo>
         <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
         <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
         <Reference URI="#_ae2dd083-d663-43a3-bd52-2dca818295e1">
            <Transforms>
               <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
               <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            </Transforms>
            <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
            <DigestValue>yu6VfuELlBlC6LdCX168xA/CwEk=</DigestValue>
         </Reference>
      </SignedInfo>
      <SignatureValue>[...]</SignatureValue>
   </Signature>
   <SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
      <KeyDescriptor>
         <KeyInfo>
            <X509Data>
               <X509Certificate>[...]</X509Certificate>
            </X509Data>
         </KeyInfo>
      </KeyDescriptor>
      <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://myapp.mydomain.com/auth/AuthServices/Acs" index="0" isDefault="true" />
      <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://myapp.mydomain.com/auth/AuthServices/Acs" index="1" isDefault="false" />
      <AttributeConsumingService index="0" isDefault="true">
         <ServiceName xml:lang="en">SP</ServiceName>
         <RequestedAttribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" isRequired="true" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="E-Mail Address" />
         <RequestedAttribute Name="http://schemas.xmlsoap.org/claims/Group" isRequired="true" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="Group" />
      </AttributeConsumingService>
   </SPSSODescriptor>   
</EntityDescriptor>
```

Any ideas?

**Comment by AndersAbel** [comment]
ADFS obviously expects the keyinfo to be present in the signature, which it currently isn't. It's a simple flag that needs to be added in the metadata generation. I can fix it for the next release. If you want to make a privat build with a fix you can pass an extra `true` value to `xmlDoc.Sign()` in `MetadataBaseExtensions.ToXmlString()`.

When we're at it, we should add keyinfo to the stub idp metadata signature as well.

**Comment by in10se** [comment]
Wow! Thank you for the swift response. I'll go ahead with the private fix then.

**Comment by AndersAbel** [comment]
Please let us know if it works or if there are further issues with ADFS compatibility.

**Comment by in10se** [comment]
It worked like a charm. Thanks again!

**Comment by IncoFB** [comment]
Today a customer tried importing our metadata on ADFS by calling the metadata url.
It generates an error :
ADFS CData elements not valid at top level of an XML document. Line 1, position 3

According to customer, when comparing to other supported SPs, it could come from the missing xml tag in generated metadata (<?xml version="1.0" encoding="UTF-8"?>), as the metadata immediately starts with "EntityDescriptor" tag.

Surprisingly, when first downloading the XML file from any browser, and then importing manually this file into ADFS, it works.
The problem seems to be only when downloading metadata from the link (that we define in entityId attribute of <sustainsys.saml2> tag

Any solution ?

**Comment by IncoFB** [comment]
Hello,
After additional research, we found that the <xml> tag was not the problem.
It is the download method that ADFS does not support.
With sustainsys, the file is downloaded as an attachment with content-type set to application/samlmetadata+xml
When extracting the file (from any browser) and publishing it as a content on another web site (with content-type:application/xml) there is no problem with ADSF
Question : how to change this download method ??
