### ISSUE TITLE
AuthnRequest failing with Azure active directory IDP

### ISSUE THREAD

**Issue by ksgopal4** [KentorIT/authservices#420]
Within the latest master branch, of Kentor Authservices, AuthnContextComparisonType can be specified as part of an AuthnRequest. The possible values are Exact, Minimum, Maximum, Better.

The above values are rendered exactly as above, when generating an AuthnRequest, by Kentor AuthServices. e.g.

```
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="***" Version="2.0" IssueInstant="2016-03-02T07:25:55Z" Destination="https://login.microsoftonline.com/****/saml2" AssertionConsumerServiceURL="http://localhost:4283/AuthServices/Acs">
        <saml2:Issuer>http://localhost:4283/</saml2:Issuer>
        <saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" AllowCreate="true" />
        <saml2p:RequestedAuthnContext Comparison="Exact">    <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml2:AuthnContextClassRef>
        </saml2p:RequestedAuthnContext>
</saml2p:AuthnRequest>
```
Of specific interest is this...
   `<saml2p:RequestedAuthnContext Comparison="Exact">`
But when using Azure active directory as IDP, Azure rejects these values as it requires Comparison values in lowercase.

The specifications do seem to emphasise lowercase values for 'Comparison' attribute.
https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

> "Comparison [Optional]
> Specifies the comparison method used to evaluate the requested context classes or statements, one
> of "exact", "minimum", "maximum", or "better". The default is "exact".
> "

The specifications also state that values specified be treated as case sensitive.

Based on this information, I suggest that the serialization of the enum needs to use lowercase values (within Saml2AuthenticationRequest.cs), alternatively refactor the enums to have lowercase values.

Do welcome other thoughts.

**Comment by AndersAbel** [comment]
You're right. It's a bug, it should be serialized to lower case.

I'll set it on the todo-list. If anyone wants to look into this and submit a PR it should be fairly simple. Remember tests.

**Comment by ksgopal4** [comment]
Thanks, I should be in a position to pick this up, on Friday, if no one else has grabbed it.

**Comment by ksgopal4** [comment]
Hi Anders, I have committed and fix and submitted a pull request for this. #422
