### ISSUE TITLE
Include Format etc. in LogoutRequest NameId

### ISSUE THREAD

**Issue by dmeierotto** [KentorIT/authservices#425]
Hi Anders, got it almost working with a shibboleth IdP. The shib IdP requires the SLO nameid message to include Format, NameQualifier and SPNameQuallifier. For example, currently the Kentor authservice is sending this as the nameid element:
`<saml2:NameID>JSMITH</saml2:NameID>`

but theh IdP expects this:

```
<saml:NameID
        Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
        NameQualifier="http://idp.mydomain.org/"
        SPNameQualifier="aip-emitter">JSMITH</saml:NameID>
```

I get this error message: 

` Idp returned status "Requester", indicating that the single logout failed`

**Comment by AndersAbel** [comment]
I expected that `Format` would show up sooner or later... the other attributes are nothing I've heard of before (I had to look them up in the spec). I assume that they are part of the NameID of the subject in the original assertion? In that case they just need to be kept around and copied over. It looks like the `Saml2SecurityTokenHandler` carries over the attributes and puts them in the property dictionary of the claim.

Solving this contains three steps:
1. Add tests (and possibly implementation) to make sure the attributes are carried over when copied to LogoutNameId.
2. Serialize them in outgoing LogoutRequest (including tests of course).
