### ISSUE TITLE
Multiple SP Entities

### ISSUE THREAD

**Issue by lindea** [KentorIT/authservices#426]
Hi,

I have an application instance with multiple sites, each assigned to their own DNS:
site1.domain.com
site2.domain.com
etc

The SAML authentication request looks fine, and mirrors the current domain for AssertionConsumerServiceURL (as in https://<current-domain>/AuthServices/Acs), but the Issuer does not. It remains the same no matter what domain I'm on. What's even stranger is that, even if I'm hard coding the EntityID in the CreateSPOptions function, the Issuer remains the same.
Can it be some caching involved? Is it possible to have multiple SPs?

At startup I create SP instances like this:
`foreach(var domain in domains)
{
 app.UseKentorAuthServicesAuthentication(CreateAuthServicesOptions("kentor", domain));
}`

and

```
private static KentorAuthServicesAuthenticationOptions CreateAuthServicesOptions(string authType, string domain)
        {
            var spOptions = CreateSPOptions(domain);
            var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
            {
                SPOptions = spOptions,
                Caption = "My Caption",
                AuthenticationType = domain + "_" + authType

            };

            var idp = new Kentor.AuthServices.IdentityProvider(new EntityId(WebConfigurationManager.AppSettings["Idp.EntityID"]), spOptions)
            {
                MetadataLocation = WebConfigurationManager.AppSettings["Idp.MetadataLocation"],
                LoadMetadata = true,
                Binding = Saml2BindingType.HttpPost,
                SingleSignOnServiceUrl = new Uri(WebConfigurationManager.AppSettings["Idp.SingleSignOnServiceUrl"])
            };

            authServicesOptions.IdentityProviders.Add(idp);

            return authServicesOptions;
        }
        private static SPOptions CreateSPOptions(string domain)
        {
            
            var spOptions = new SPOptions

            {
                EntityId = new EntityId("https://" + domain+"/"),
                ReturnUrl = new Uri("https://" + domain)
            };
          
            return spOptions;
        }
    }

```

**Comment by AndersAbel** [comment]
The library is designed to have one EntityId (which is used as the Issuer).

What you want is two logical SP instances. It can be used as you describe, with one important addition: You must assign each SP/middleware instance a different ModulePath.

**Comment by lindea** [comment]
Thanks for the response, that worked well.

**Comment by mustantriveni** [comment]
How should i use ModulePath?
i am confused
