### ISSUE TITLE
CryptographicException "The data protection operation was unsuccessful"

### ISSUE THREAD

**Issue by stevescc** [KentorIT/authservices#427]
I'm trying to get the sample MVC application deployed to Azure and using Okta as the IDP, with a view of doing the same thing for our custom applications, but am receiving the CryptographicException "The data protection operation was unsuccessful".

When this occurs the URL in the browser is https://mysite.azurewebsites.net/AuthServices/Acs

I am using Kentor.AuthServices.Mvc nuget package, v0.17.0.

Below is the kentor section of my web.config. I don't have an identity server so removed all the federation config..
```
<kentor.authServices entityId="https://mysite.azurewebsites.net/AuthServices"
               returnUrl="https://mysite.azurewebsites.net/"
               authenticateRequestSigningBehavior="Never">
<identityProviders>
  <add entityId="http://www.okta.com/1111111"
       allowUnsolicitedAuthnResponse="true" binding="HttpRedirect" 
       metadataLocation="https://dev-11111.oktapreview.com/app/1111111/sso/saml/metadata"
       loadMetadata="true">
    <signingCertificate fileName="~/App_Data/okta.cert" />
  </add>
</identityProviders>
```

And here is the stacktrace

> [CryptographicException: The data protection operation was unsuccessful. This may have been caused by not having the user profile loaded for the current thread's user context, which may be the case when the thread is impersonating.]
>    System.Security.Cryptography.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope) +405
>    System.IdentityModel.ProtectedDataCookieTransform.Encode(Byte[] value) +51
> 
> [InvalidOperationException: ID1074: A CryptographicException occurred when attempting to encrypt the cookie using the ProtectedData API (see inner exception for details). If you are using IIS 7.5, this could be due to the loadUserProfile setting on the Application Pool being set to false. ]
>    System.IdentityModel.ProtectedDataCookieTransform.Encode(Byte[] value) +160
>    System.IdentityModel.Tokens.SessionSecurityTokenHandler.ApplyTransforms(Byte[] cookie, Boolean outbound) +57
>    System.IdentityModel.Tokens.SessionSecurityTokenHandler.WriteToken(XmlWriter writer, SecurityToken token) +661
>    System.IdentityModel.Tokens.SessionSecurityTokenHandler.WriteToken(SessionSecurityToken sessionToken) +85
>    System.IdentityModel.Services.SessionAuthenticationModule.WriteSessionTokenToCookie(SessionSecurityToken sessionToken) +146
>    System.IdentityModel.Services.SessionAuthenticationModule.AuthenticateSessionSecurityToken(SessionSecurityToken sessionToken, Boolean writeCookie) +81
>    Kentor.AuthServices.HttpModule.CommandResultHttpExtension.SignInOrOutSessionAuthenticationModule(CommandResult commandResult) +159
>    Kentor.AuthServices.Mvc.AuthServicesController.Acs() +63
>    lambda_method(Closure , ControllerBase , Object[] ) +62
>    System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
>    System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
>    System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
>    System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
>    System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
>    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
>    System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
>    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
>    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
>    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
>    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
>    System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
>    System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
>    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
>    System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
>    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9644037
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
> 
> Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

**Comment by AndersAbel** [comment]
That's a limitation in Azure Web Sites that doesn't allow the default session authentication manager encryption. Please see http://www.cloudidentity.com/blog/2013/01/28/running-wif-based-apps-in-windows-azure-web-sites-4/ for a workaround.

It should work with AuthServices, but please confirm if it does.

**Comment by stevescc** [comment]
That did it, as per your link, I added the following the web.config and it worked:
```
<system.identityModel>
    <identityConfiguration>
      <securityTokenHandlers>
        <add type="System.IdentityModel.Services.Tokens.MachineKeySessionSecurityTokenHandler, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
        <remove type="System.IdentityModel.Tokens.SessionSecurityTokenHandler, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
      </securityTokenHandlers>
    </identityConfiguration>
  </system.identityModel>
```
Thanks Anders

**Comment by albinsunnanbo** [comment]
Alternatively you can turn on profile loading on the AppPool in IIS

**Comment by AndersAbel** [comment]
@albinsunnanbo Is that possible with Azure web sites?

**Comment by chcalder** [comment]
I ran into the same error and config publishing my solution in Azure Websites. The addition in the web.config got it working.

**Comment by suwatch** [comment]
To turn on user profile, do add Site's appSettings `WEBSITE_LOAD_USER_PROFILE = 1`.   See if that helps.

**Comment by AndersAbel** [comment]
I just love open source. I just ran into this issue and of course had no memory of this ever happening. Googling for the error message I ended up here, on an issue in my own project, with the solution clearly documented. Thanks @stevescc for taking the time to report back and providing the copy-paste-ready web.config additions.

**Comment by ysodiqakanni** [comment]
> WEBSITE_LOAD_USER_PROFILE = 1

This worked for me. easy-peasy!
