### ISSUE TITLE
Audience For Multiple Providers

### ISSUE THREAD

**Issue by parkinsona** [KentorIT/authservices#428]
Hi,

If I configure a separate Identity Provider for each of my clients, should I use a difference Audience Restriction for each of them or is it safe to use the same value for each.

**Comment by AndersAbel** [comment]
I'm not that familiar with using the Audience restriction, but usually I think that it is made up of the Entity Id of the SP. So if you have one SP instance (i.e. one AuthServices module/middleware) you should use the same audience even though you connect to different Idps.

**Comment by parkinsona** [comment]
Thanks Anders. I will have 1 SP instance that connects to different Idps.
I'll keep the 1 audience for now.
