### ISSUE TITLE
Possible removal of ISPOptions interface

### ISSUE THREAD

**Issue by explunit** [KentorIT/authservices#431]
Since #358 was merged, there is no case in AuthServices itself where an `ISPOptions` is implemented except for the main `SPOptions`. Should we consider removing `ISPOptions` so that the kind of validation discussed in #429 can be done centrally? Or are there cases where people have implemented their own class with this interface, e.g. as a way of adapting to a different underlying configuration system?

**Comment by AndersAbel** [comment]
Looks like there's no objections. I suggest we go ahead with removing the `ISPOptions` interface. I'd prefer to have that done first (I can do it, but not today) and then update and merge #429. @explunit what do you think about that?

**Comment by explunit** [comment]
Sounds fine to me.

**Comment by AndersAbel** [comment]
Ok, I couldn't keep my fingers off the code, so now it's done.
