### ISSUE TITLE
External Provider callback is not HTTPS when AWS elastic load balancer terminates the HTTPS connection

### ISSUE THREAD

**Issue by jaydinslage** [KentorIT/authservices#432]
I had initially initiated an issue with the Identity Server folks about this issue: https://github.com/IdentityServer/IdentityServer3/issues/2741 However, they have determined that the issue resides with Kentor.  

The issue is that when Kentor initiates the callback for identity server, the request is HTTP when the site is behind a load balancer that terminates the HTTPS there.  Identity Server provides the relative URL to Kentor through the OWIN authentication challenge.  Kentor then uses the current HTTP scheme, which would be HTTP because of the termination at the load balancer.  This is problematic because the cookies that are set will not come across.

I don't see any way to have AuthServices to force HTTPS in this instance.  Everything else works fine and HTTPS except for this single redirect.

Is this a bug, or is there some way that I can make that redirect HTTPS?  Our current workaround was to create a URL rewrite outbound rule for just that URL.

**Comment by explunit** [comment]
Can you use the PublicOrigin property to solve this?
https://github.com/KentorIT/authservices/blob/master/doc/Configuration.md#publicorigin-attribute

**Comment by jaydinslage** [comment]
I already have that set.  In this case, AuthServices just echos the URL given to it by identity server, which is a relative URL.  It doesn't appear to use the PublicOrigin when redirecting back to identity server.

**Comment by AndersAbel** [comment]
Looks like this might be a bug, where PublicOrigin is not properly used in this case. Will have to look into it.

**Comment by AndersAbel** [comment]
It's a bug. The relative path created by AuthServices is expanded to an absolute URL and that is done without properly checking PublicOrigin.
