### ISSUE TITLE
Issue related to 0.17.1 and callback

### ISSUE THREAD

**Issue by dmeierotto** [KentorIT/authservices#436]
Hi Anders, there is an issue with this [commit ](https://github.com/KentorIT/authservices/commit/be09e417471ad3ff8869988b0ee99ffc989f059f) I think. I just upgraded to 0.17.1 and I am using the spmetadata public origin property. I am using the Identity Server as well, and the IdSvr origin is something like https://id.domain.org. My idsvr is running in a virtual directory named cpauh and has a root path "core". So the root of the idsvr is https://id.domain.org/cpauth/core. I was setting the public origin of spmetadata to https://id.domain.org/cpauth/core. With your commit you are appending this "cpauth/core" on the sign in call back, so I should be able to now use the same origin as the IdSvr, but I am not seeing where you are handling this on the generation of the AssertionConsumerServiceURL for example. Am I missing something? If I remove the "cpauth/core" from the spmetatdata orgin, my AssertionConsumerServiceURL is not generated correctly, and if I leave it the SignInCommand duplicates the cpauth/core, so the callback looks like https://id.domain.org/cpauth/core/CPAuth/core/callback

Maybe I am doing something wrong.

For now I rolled back to 0.17.0. 

Thanks, 

Dan

**Comment by AndersAbel** [comment]
You're probably right that there is an issue with that commit. There are many combinations to handle in the URL expansion, so I might have done something wrong.

I'll take a look.

**Comment by AndersAbel** [comment]
You're right, it even gets the same problem for the Sample application in the repo...

**Comment by AndersAbel** [comment]
Fixed in version 0.17.2 that I just pushed to Nuget.
