### ISSUE TITLE
Saml2 status code needs more mapping

### ISSUE THREAD

**Issue by federicobarera** [KentorIT/authservices#442]
While processing logout from okta:

![image](https://cloud.githubusercontent.com/assets/6658124/14241150/5a718b66-fa8d-11e5-8101-edd88383603b.png)

**Comment by AndersAbel** [comment]
That's definitely a bug. There permissible top level status codes are listed in the [core spec](http://www.oasis-open.org/committees/download.php/56776/sstc-saml-core-errata-2.0-wd-07.pdf) section 3.2.2.2 and there are many more than those four in the code. They need to be added. If you have time submit a PR that would be appreciated.

**Comment by federicobarera** [comment]
Seems easy enough. I'll try to put together a pr for tonight

**Comment by albinsunnanbo** [comment]
Maybe an Enum is not the right format for this if the value set is not bounded by the core specification.
Maybe introduce the Enum value "Custom" and make sure the raw status string is exposed.

**Comment by AndersAbel** [comment]
It's a fixed list. But for some reason I had only included four of them in the original code.
