### ISSUE TITLE
Issue with Single Logout and NameIdFormat

### ISSUE THREAD

**Issue by dmeierotto** [KentorIT/authservices#448]
Single logout is close to working, however, the NameId policy still does not seem to be applied to the logout request. 

Maybe I have misconfigured something. Here is the config code:

```
var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
            {
                SPOptions = new SPOptions
                {
                    EntityId = new EntityId(SPEntityId),   
                    PublicOrigin = new System.Uri(origin),
                    NameIdPolicy = new Kentor.AuthServices.Saml2P.Saml2NameIdPolicy(true, Kentor.AuthServices.Saml2P.NameIdFormat.X509SubjectName)                    
                },
                
                SignInAsAuthenticationType = signInAsType,
                AuthenticationType = UniteConstants.ProviderName,
                Caption = UniteConstants.Caption                                       
            };
```

and the logout request saml message:
```

<saml2p :LogoutRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
        xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
        ID="id2f54bb78ce3348228695a8417b7dc944"
        Version="2.0"
        IssueInstant="2016-04-14T10:36:59Z"
        Destination="https://idp.my-domain.org/oamfed/idp/samlv20">
  <saml2:Issuer>http://conferences-local.my-domain.org</saml2:Issuer>
  <saml2:NameID>JOHNDOE</saml2:NameID>
  <saml2p:SessionIndex>id-BzZPtIN6qAYfwJqcQhFk9xoLcdWPppN3uZAPEk05</saml2p:SessionIndex>
</saml2p:LogoutRequest>
```

The NameID element should include the format. 
`Format="urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName"`

I can see the format being included on other messages(e.g. the authnrequest). Am I missing a config?

I am running Kentor.Authservers+Owin 0.17.2 and IDServer3 v2.4.0

Thanks!
Dan

**Comment by AndersAbel** [comment]
Thanks for the feedback.

The NameIdPolicy in the configuration only affects the generated AuthnRequests so for the LogoutRequest it doesn't matter what you put there.

The entire NameId (including format and other attributes) in the LogoutRequest is taken from the NameId of the Assertion that established the session. Can you check what it looks like in there? Use e.g. the SAML DevTools extension for Chrome to show the messages directly in the browser.

**Comment by dmeierotto** [comment]
Hi Anders, everything there is correct:

the auth request:

```
<saml2p :AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
        xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
        ID="id4ab2eb55d8f64dc2a4032a51fc6d734d"
        Version="2.0"
        IssueInstant="2016-04-18T09:26:07Z"
        Destination="https://some.domain.org/oamfed/idp/samlv20"
        AssertionConsumerServiceURL="https://some.domain.org/cpauth/core/AuthServices/Acs">
  <saml2:Issuer>http://some.domain.org</saml2:Issuer>
  <saml2p :NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName"
          AllowCreate="true" />
</saml2p:AuthnRequest>
```
then the response 
<samlp :Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
       xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"
       xmlns:enc="http://www.w3.org/2001/04/xmlenc#"
       xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
       xmlns:x500="urn:oasis:names:tc:SAML:2.0:profiles:attribute:X500"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       Destination="https://some.domain.org/cpauth/core/AuthServices/Acs"
       ID="id-SofcgCP8tOdZHgTJq7k6aD76ANGyLxgsGCDVQ1tg"
       InResponseTo="id4ab2eb55d8f64dc2a4032a51fc6d734d"
       IssueInstant="2016-04-18T09:26:18Z"
       Version="2.0">
  <saml :Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://some.domain.org/oam/fed</saml:Issuer>
  <samlp:Status>
    <samlp :StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
  </samlp:Status>
  <saml :Assertion ID="id-HJznC-XSJHdCs2YywRY73CjNf7rHGBd3Ffxh2el4"
        IssueInstant="2016-04-18T09:26:18Z"
        Version="2.0">
    <saml :Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://some.domain.org/oam/fed</saml:Issuer>
    <dsig:Signature>
      <dsig:SignedInfo>
        <dsig :CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
        <dsig :SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
        <dsig :Reference URI="#id-HJznC-XSJHdCs2YywRY73CjNf7rHGBd3Ffxh2el4">
          <dsig:Transforms>
            <dsig :Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
            <dsig :Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
          </dsig:Transforms>
          <dsig :DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
          <dsig:DigestValue>2nRFbEcAEzZzuBR5GOrfe6CzEdbkC3eysCtcfBvk0WY=</dsig:DigestValue>
        </dsig:Reference>
      </dsig:SignedInfo>
      <dsig:SignatureValue>lOKbgkuajc6/ZsaOLwG8ENvqC/niM4OUfyETng01n91UC6nmtRDpfUd+7y87Gd6ujRDcqLNhg0LMMmZcbpIXFqLPuIAFTzqp1NJRE13UWmC96IDY9qyztTv3++9crhMh5RGv4Z7IU9SbNhH1jghH+lbkThJn48tVXz2/gY9h5q0=</dsig:SignatureValue>
    </dsig:Signature>
    <saml:Subject>
      <saml :NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName">DMEIEROT</saml:NameID>
      <saml :SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml :SubjectConfirmationData InResponseTo="id4ab2eb55d8f64dc2a4032a51fc6d734d"
              NotOnOrAfter="2016-04-18T09:31:18Z"
              Recipient="https://some.domain.org/cpauth/core/AuthServices/Acs" />
      </saml:SubjectConfirmation>
    </saml:Subject>
    <saml :Conditions NotBefore="2016-04-18T09:26:18Z"
          NotOnOrAfter="2016-04-18T09:31:18Z">
      <saml:AudienceRestriction>
        <saml:Audience>http://some.domain.org</saml:Audience>
      </saml:AudienceRestriction>
    </saml:Conditions>
    <saml :AuthnStatement AuthnInstant="2016-04-18T09:26:18Z"
          SessionIndex="id-RD1DnMxedDoUMwsf-hjclxgzSwZgmSdvEkdNoUaJ"
          SessionNotOnOrAfter="2016-04-18T10:26:18Z">
      <saml:AuthnContext>
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
      </saml:AuthnContext>
    </saml:AuthnStatement>    
  </saml:Assertion>
</samlp:Response>

**Comment by AndersAbel** [comment]
Looks right in those messages. Any chance you can see the claims of the CurrentPrincipal? The nameid-format is stored in the property dictionary of the NameIdentifier or LogoutNameIdentifier claim. Is it properly present at the time when the logout is initiated?

**Comment by dmeierotto** [comment]
OK, that makes sense, I am debugging this now. The issue is that this claim gets dropped between the IdentityServer and my app, but it is probably a claims mapping issue somewhere. I do see the claim and property on the IDserver side, but the logout happens from my app, and the claim is not present at this point.

**Comment by AndersAbel** [comment]
Are you issuing the logout directly from your app to AuthServices? But the login flow is through IdSrv3?!?

If your app is an OIDC client to IdSrv3 it should do an OIDC logout to IdSrv3, which in turn will trigger the AuthServices logout mechanism.

**Comment by dmeierotto** [comment]
I am triggering the logout from my app with Request.GetOwinContext().Authentication.SignOut(). I will follow up here in a bit once I have fully debugged it.

**Comment by AndersAbel** [comment]
That's the right way to trigger it, but AuthServices shouldn't run in the main app pipeline. It should run in the IdSrv3 pipeline, which will have different claims.
If you check the redirect sequence with browser dev tools you should see something like your app->IdSrv3/logout->SAML2 Idp->IdSrv3/logout(->your app).

**Comment by dmeierotto** [comment]
Right, I spoke to soon earlier! OK, I found a good hook on the IdSrv3 side to debug the claims. I have a kentor name id claim(http://kentor.se/AuthServices/LogoutNameIdentifier) is there but the properties are empty.  I do not see the actual http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier claim which had the format prop(it was there after authentication)

**Comment by AndersAbel** [comment]
The NameIdentifier claim is probably overriden/lost somewhere along the way. That's why AuthServices makes a backup in the LogoutNameIdentifier claim. But the properties should be there. If you insert a debugging middleware (see https://coding.abel.nu/2014/06/understanding-the-owin-external-authentication-pipeline/) right before the `UseIdentityServer` call in your startup, and set a breakpoint after next.Invok() you should be able to see what the claims sent to the cookie middleware looks like. It would be interesting to see if the properties are present at that time and lost in the cookie, or already lost before that.

For reference, the relevant code that adds the LogoutNameIdentifier claim is in https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices.Owin/KentorAuthServicesAuthenticationHandler.cs#L140.

**Comment by dmeierotto** [comment]
Yes, this is what I am debugging now, they are definitely being overridden, I had some old claim mapping code to force the NameId, but that has been removed and they are still overridden. I am fairly sure it is an issue on my side, I will report back once it is solved.

**Comment by dmeierotto** [comment]
OK, today I had a few minutes to dig into this a bit more. 
It appears I am losing the property somewhere inside the IdSvr, I will have to get the code and step through to be certain. But the property exists inside the ClaimsAuthenticationManager.Authenticate but when I get to AspNetIdentityUserService.AuthenticateExternalAsync the ExternalAuthenticationContext.ExternalIdentity no longer has the property.

the LogoutNameIdentifier claim is there, but not the property indicating the format.

Any ideas? In the meantime I will pull down the ID server source and just step through it to get this over with...

**Comment by AndersAbel** [comment]
I've had a look and I think I've found the problem: The cookie middleware doesn't serialize the properties of the identity. See the Write method in [TicketSerializer.cs](http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security/DataHandler/Serializer/TicketSerializer.cs).

I think we'll have to fix this on the AuthServices side by converting the properties into claims. Or the format information can be encoded in the same string as the rest in the LogoutNameIdClaim. Maybe even the SessionId should go there - putting everything in one claim and call it Saml2LogoutInformation.

Thanks @dmeierotto for investigating so far, I've marked this as a bug to have it solved (when I get time).

**Comment by dmeierotto** [comment]
Great, I thought also serialization somewhere as well as it was just the props being dropped. 

Can you recommend a way to handle this exception better? Right now I just get an exception on logout. can I disable the call to the single logout somewhere until this gets fixed?

**Comment by AndersAbel** [comment]
There's a new property on the `IdentityProvider` class (available in web.config too) to disable outgoing logout requests from being generated.

In the long term I think that it's best to change the behaviour and put the name id format in the value of the claim. Requiring everyone using AuthServices to have a custom auth middleware is probably not feasible.
