### ISSUE TITLE
SHA256 support for in outgoing Redirect Bindings

### ISSUE THREAD

**Issue by HeikoLux** [KentorIT/authservices#452]
On ADFS I configured Endpoint with POST Binding and everything worked, but with a little workaround on my own. When signature is added in class Saml2RedirectBinding, I coded sha256 hash string on myself (with sha256 support in Global.asax GlobalEnableSha256XmlSignatures):
Original code
`queryString += "&SigAlg=" + Uri.EscapeDataString(SignedXml.XmlDsigRSASHA1Url);
var signatureDescription=SignatureDescription)CryptoConfig.CreateFromName(SignedXml.XmlDsigRSASHA1Url);`

My workaround
`queryString += "&SigAlg=" + Uri.EscapeDataString("http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");
var signatureDescription = (SignatureDescription)CryptoConfig.CreateFromName("http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");`

Without this, it is not possible to verify Signature because SHA1 is used.
What can I do without modifying code?

/Heiko

**Comment by AndersAbel** [comment]
There's currently no built in support for anything but Sha1 for signing (both for Redirect bindings and normal XML signatures). It would be great to add it.
