### ISSUE TITLE
Receiving error Invalid URI: on the response

### ISSUE THREAD

**Issue by techbits00** [KentorIT/authservices#456]
Hello,
I am receiving an Invalid URI exception when process the response on /AuthServices/Acs and I have gone through every configuration to understand what am I doing wrong but i am stuck on it. 

Based on the metadata of IP I have from our network admins the configuration looks like this. 

`  <add entityId="http://adfs.example.com/adfs/services/trust" 
           signOnUrl="https://adfs.example.com/adfs/ls/" allowUnsolicitedAuthnResponse="true" 
           binding="HttpRedirect"
           loadMetadata="true"
           metadataLocation="https://adfs.example.com/FederationMetadata/2007-06/FederationMetadata.xml">
        <signingCertificate fileName="~/App_Data/example.cer"/>
      </add>`

The Metadata of the service also has the entityId as specified above so I am not sure what am I doing wrong here. Any feedback is appreciated. 

Full exception is here. 

`[UriFormatException: Invalid URI: The format of the URI could not be determined.]
   System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) +6675677
   System.Uri..ctor(String uriString) +20
   Kentor.AuthServices.Saml2P.Saml2PSecurityTokenHandler.GetAudienceRestriction(ISPOptions spOptions) +179
   Kentor.AuthServices.Saml2P.Saml2PSecurityTokenHandler..ctor(ISPOptions spOptions) +87
   Kentor.AuthServices.Configuration.SPOptions.get_Saml2PSecurityTokenHandler() +32
   Kentor.AuthServices.Saml2P.<CreateClaims>d__53.MoveNext() +264
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +381
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options) +90
   Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState) +36
   Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) +143

[BadFormatSamlResponseException: The SAML Response did not contain valid BASE64 encoded data.]
   Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) +230
   Kentor.AuthServices.Mvc.AuthServicesController.Acs() +54
   lambda_method(Closure , ControllerBase , Object[] ) +62`

**Comment by albinsunnanbo** [comment]
`[BadFormatSamlResponseException: The SAML Response did not contain valid BASE64 encoded data.]` might be the clue. Can you catch the SAML-data with https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace or https://addons.mozilla.org/sv-se/firefox/addon/saml-tracer/ ?

**Comment by techbits00** [comment]
Thank you for replying, I was able to get it sorted by entityID to a URL

**Comment by dunghill** [comment]
Hi,
I have the same error but not resolved, can you show me?
"<sustainsys.saml2 entityId="tknb.ssc.vn"
                    returnUrl="http://tknb.ssc.vn:8080/Default.aspx" minIncomingSigningAlgorithm ="sha1"
                    authenticateRequestSigningBehavior="Always">
    <identityProviders>
      <add entityId="http://sso.tinhvan.vnet:80/oam/fed"
           signOnUrl="http://sso.tinhvan.vnet/oamfed/idp/samlv20" 
          allowUnsolicitedAuthnResponse="true"
           binding="HttpRedirect" 
          loadMetadata="true" 
          metadataLocation="http://sso.tinhvan.vnet/oamfed/idp/metadata"> 
      <signingCertificate fileName="~/metadata/saml.cer"/> </add>    
    </identityProviders>
    <federations>
      <add metadataLocation="http://sso.tinhvan.vnet/oamfed/idp/metadata" allowUnsolicitedAuthnResponse = "false" />
    </federations>
    <serviceCertificates>
      <add fileName="~/metadata/saml2.pfx"   />
    </serviceCertificates>
  </sustainsys.saml2>"


Thanks!
