### ISSUE TITLE
The specified network password is not correct when loading pfx through web.config

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#457]
Using web.config to load a pfx to be added as a service certificate gives a "The specified network password is not correct" exception.

Looks like we should pass a `MachineKeySet` flag when loading the cert: http://stackoverflow.com/questions/8286110/asp-net-the-specified-network-password-is-not-correct/8291956#8291956.

**Comment by lballena** [comment]
Hello @AndersAbel  I verified that I had the latest version of sustainsys.  I'm using the httpmodule for my asp.net webforms.  Cert has been imported, pfx has been installed with password entered.  And i reference the pfx file in the serviceCertificate element as follows:
<add use="Signing" fileName="~/App_Data/traqs-aws-servicecert-saml.pfx"  />
And I'm still getting the error.
Should I be referencing the cert via storename?   In the documentation, i know that can be done for the signingCertificate element of the IDP, but its not mentioned for the serviceCertificate.
Any help would be really appreciated.
thanks.
