### ISSUE TITLE
Repeating error if metadata loading fails

### ISSUE THREAD

**Issue by Christfigure** [KentorIT/authservices#458]
I had a situation where the metadataurl for a client threw a 404 error.  In our error logs we see the initial error, but then about every 2 minutes or so after the initial error we are seeing another error that repeats forever until I recycle the application pool for our website.  This is the error:

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
at System.Net.WebClient.OpenRead(System.Uri address)
at Kentor.AuthServices.Metadata.MetadataLoader.Load(System.String metadataLocation)
at Kentor.AuthServices.IdentityProvider.DoLoadMetadata()
at System.Threading.Tasks.Task.Execute()
--- End of inner exception stack trace ---

If the metadata loading task fails, will it keep retrying every few minutes?  If the metadataurl no longer throws a 404 after the initial failure, will these errors go away on their own?

**Comment by AndersAbel** [comment]
If the metadata load fails, it will retry every few minutes. Once it succeeds it will go back to an interval that is derived from the CacheDuration attribute in the metadata. If none is found I think that the default refresh time is 30 minutes (I don't remember exactly).
