### ISSUE TITLE
Single Log out - what is required to be implemented in SSO Logout endpoint

### ISSUE THREAD

**Issue by kb99** [KentorIT/authservices#459]
We are currently implementing SSO using IdentityServer3 and Kentor

We are investigating what is required to implement Single Signout.

I am a little unclear at the moment about what  we need to implement for single logout. I am using the Kentor IDP stub for testing. I can successfully initiate a SSO login from the stub to our app. Then when I log out of our app, I am redirected to the Signout page of the stub - the  SP Single Logout Url is defaulted to http://localhost:55555/identity/AuthServices/Logout. 
Currently this endpoint does not exist  in our app -  is there any specific logic that we need to implement in this endpoint or can we just use our existing Logout endpoint that users would use via our app?

Does the logout endpoint need to do anything specific with the SAML response that is sent to it?

**Comment by AndersAbel** [comment]
You need to have a service certificate configured, as the LogoutRequest message must be signed. Once you add a service certificate to the config, the metadata will start exposing the SLO endpoints.

**Comment by kb99** [comment]
Thank you for the quick reply. Yes it is working now end to end with the IDP stub.

I'm now testing with a Okta dev account but I get an error when I try to log out of my app. It appears that Okta is not appending any SAML Response when it sends a request to the /identity/AuthServices/Logout endpoint. I will need to do more investigation to see what the issue is.

**Comment by AndersAbel** [comment]
Can you share what you found? Or did you give up?

**Comment by kb99** [comment]
I have not been able to resolve the issue yet. Under time pressure here and  SLO is not a required feature that we need to implement so have to park it for a while. Will update ticket if I get a chance to re-investigate.
