### ISSUE TITLE
SubjectConfirmation missing SubjectConfirmationData

### ISSUE THREAD

**Issue by tgardner** [KentorIT/authservices#461]
Hi,

I've noticed that the SAML response tokens generated by the StubIdP, have a SubjectConfirmation with a method of `urn:oasis:names:tc:SAML:2.0:cm:bearer`, however they're missing a SubjectConfirmationData child element. I'm aware that you're providing a Conditions element to accompany it, but I believe this is still in conflict with the [SAML specification](http://docs.oasis-open.org/imi/identity/cs/imi-saml2.0-profile-cs-01.html#_Ref248548678). The reference in particular is 

> In the case of bearer assertions, the `<saml:SubjectConfirmation>` element **MUST** include a `<saml:SubjectConfirmationData>` element containing a NotOnOrAfter XML attribute to limit their use, typically to a very short window of time, although the exact duration may be use case dependent.

Am I misreading something?

Also, all response tokens generated by the StubIdp are failing to [pass validation](https://www.samltool.com/validate_response.php).

I came across this when attempting to integrate SSO with Tableau (Which are using Spring Framework) is rejecting responses with an error 

> Assertion invalidated by subject confirmation - can't be confirmed by the bearer method

Any insight would be appreciated.

Thanks,

Trent

**Comment by AndersAbel** [comment]
Thanks for noticing and for submitting a fix. I'm busy with a deadline right now and will review as soon as I find time.

**Comment by tgardner** [comment]
Thanks @AndersAbel, let me know if there's any issues and I'll be happy to fix.
