### ISSUE TITLE
Include Binding in AuthnRequests

### ISSUE THREAD

**Issue by rascboy** [KentorIT/authservices#466]
I'm having an issue with authservices loading custom metadata configurations. I've tried providing the xml via local file and also a given url but when I decode the AuthnRequest none of the custom metadata is loaded.

I've been wrestling with this for a couple of days but maybe I just have the config incorrect? This is how I currently have the idp configured in the web.config:
`
<identityProviders>     
    <add entityId="https://some.url.com"
         loadMetadata="true"
         metadataLocation="~/App_Data/metadata.xml"
        // Tried this as well: metadataLocation="https://some.url.com/auth/metadata/metadata.xml"
         allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
    </add>
</identityProviders>
`

**Comment by AndersAbel** [comment]
Both configuration looks correct. If AuthServices wouldn't find the metadata there would be an exception (try introducing a typo in the file name/url to see what happens).

What do you expect to find in the AuthnRequest based on the metadata?

**Comment by rascboy** [comment]
Oh you're right, adding the typo does cause an exception. 

I was trying to figure out why the metadata in the authnrequest didn't contain an attribute for protocol binding. I assumed that was configured from the metadata url. Forgive me if I sound ignorant as I've just recently begun working with SAML.

**Comment by AndersAbel** [comment]
SAML is complicated, so there's no need for excuses.

The metadata of the idp instructs AuthServices on what binding to use when sending requests to the Idp.

If a binding is included in the AuthnRequest, it instructs the Idp what binding to use when returning the response to the SP (i.e. AuthServices). Since AuthServices supports both Http POST and Artifact bindings for incoming requests none is specified in the generated AuthnRequests.

**Comment by rascboy** [comment]
Thanks for the explanation, it makes complete sense. The issue that I'm having is that I've identified authservices as an SP to the IDP but it's returning a 403, which i'm assuming means that it doesn't recognize authservices as an authorized SP. The following is what the SP metadata looks like. I've checked that the entityID on the IDP matches and also made sure the required nameIDPolicy is the same. It seems like I've set up everything correctly but maybe I missed something that you can see?

`<?xml version="1.0" encoding="UTF-8"?>
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_fc1b154e-5615-4835-a541-292d7f93cba6" entityID="https://my.app.com/AuthServices/" cacheDuration="PT1H">
   <SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
      <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://my.app.com/AuthServices/Acs" index="0" isDefault="true" />
      <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://my.app.com/AuthServices/Acs" index="1" isDefault="false" />
   </SPSSODescriptor>
</EntityDescriptor>`

AuthNRequest
`<?xml version="1.0" encoding="UTF-8"?>
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="id4f54ab9286d54265b7b9c6a03c6947cd" Version="2.0" IssueInstant="2016-05-09T17:30:16Z" Destination="https://idp.myapp.com/affwebservices/public/saml2sso" AssertionConsumerServiceURL="https://my.app.com/AuthServices/Acs">
   <saml2:Issuer>https://my.app.com/AuthServices/</saml2:Issuer>
   <saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" />
</saml2p:AuthnRequest>`

**Comment by rascboy** [comment]
On a similar same note, is there a way to set the protocol binding manually? It seems the IDP may be set up in a way that it requires the protocol binding to be set in the outgoing authnrequest...

**Comment by AndersAbel** [comment]
There is currently no way, but it should be quite simple to add. First there should be a `Saml2BindingType? Binding` property on the `Saml2AuthenticationClass` that is added to the Xml generated by `ToXElement()`. Then the caller can use the `AuthenticationRequestCreated` notification to set the `Binding` property on the generated AuthnRequests.

**Comment by rascboy** [comment]
That did the trick. Thanks for the pointers!

**Comment by AndersAbel** [comment]
Reopning this as I want the feature to be in the main release. Any chance you could submit a PR?

**Comment by rascboy** [comment]
I don't mind submitting a PR but I set the binding as a string. I'm not sure if that's the way you had in mind for the implementation.

**Comment by AndersAbel** [comment]
@rascboy You're setting it as a hard coded string? In that case it's not what I had in mind - it's a perfectly viable workaround for your situation, but not flexible enough for the official release.

**Comment by rascboy** [comment]
@AndersAbel Yea, I set it as a hard coded string. We needed to test the application asap and that was the fastest way we could get everything set up and tested

**Comment by AndersAbel** [comment]
@rascboy I understand. It's a working fix for your case, but as you understand we need a better fix for a PR. I'll leave this issue open as a bug until someone has time to look at it.

**Comment by Alk3m1st** [comment]
This is exactly the issue I am facing currently. The IdP in my organisation requires the ProtocolBinding attribute on the AuthNRequest. Can I ask when you expect to update the NuGet package with this addition?

**Comment by blubinsky** [comment]
@AndersAbel Anders, I have the same issue, and the new property on Saml2AuthenticationRequest gets me about halfway there.

* I'm using KentorAuthServicesAuthenticationMiddleware. 
* This uses KentorAuthServicesAuthenticationHandler as the AuthenticationHandler.  
* For an auth request, ApplyResponseChallengeAsync is called. 
* This calls the static method SignInCommand.Run, which in turn calls InitiateLoginToIdp, which then calls CreateAuthenticateRequest on the IdentityProvider instance passed in.
*  CreateAuthenticateRequest on the IdentityProvider does not set the new Binding property on the request instance.

Easy fix for me locally, but would be good to get into a Nuget release. 

My preferred solution would have been to inherit from IdentityProvider and override the method.
