### ISSUE TITLE
Issue with Internet Explorer

### ISSUE THREAD

**Issue by Vanhalessio** [KentorIT/authservices#469]
Hi and thanks for your work, very appreciated.
I'm testing your library into a Web Site application (non MVC).

On returning from your idpstub for the assertion response, I get a "Received message contains unexpected InResponseTo "XXX". No RelayState was detected so message was not expected to have an InResponseTo attribute" error from the SP server.

This is the incoming request
`<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="idea7106f6cc9d4a5f90302bf6c3155d67" Version="2.0" IssueInstant="2016-05-06T10:43:14Z" Destination="http://stubidp.kentor.se/" AssertionConsumerServiceURL="http://test_saml/AuthServices/Acs">
  <saml2:Issuer>http://test_saml/SamplePath/AuthServices</saml2:Issuer>
  <saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" AllowCreate="true" />
  <saml2p:RequestedAuthnContext Comparison="minimum">
    <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml2:AuthnContextClassRef>
  </saml2p:RequestedAuthnContext>
</saml2p:AuthnRequest>
`

Attached you can find the screen of the IdP received data.

I tried sniffing on the client to check if the post request to http://AuthServices/Acs cointains the RelayState and it does. The dialogue scheme between client, idp and sp seems correct to me (you can see it attached, the RelayState code is different from the one on the idp from the other image because they have been taken from different sessions).

The problem seems to appear only with Internet Explorer (8 and 11), while with Firefox and Chrome works! Tried on different PCs.

System description:
- the SP is deployed into a windows server 2012 machine
- the client request have been made both from the machine itself or from a different one connected on the same LAN

Thank you very much for your help!

![idp session](https://cloud.githubusercontent.com/assets/19210727/15071024/e2753bde-1388-11e6-9ffa-0995b6a6e5cd.png)
![test ie](https://cloud.githubusercontent.com/assets/19210727/15071025/e2756adc-1388-11e6-8d8d-ebe5855cb6b0.png)

**Comment by AndersAbel** [comment]
When AuthServices redirects the user to the Idp (the second line in the trace where it replies with 302 Found) it should set a cookie with a name that corresponds to the RelayState. Can you check if the Set-Cookie header is present? Can you check if the cookie is listed in the browser as set?

**Comment by Vanhalessio** [comment]
Here I am again.
Did some testing on cookies management
- the set-cookie header is always present, with the correct RelayState
- the cookie is set in Mozilla and Chrome, while for IE we have two different cases
1. the application works if the web server used is the Visual Studio one (debug), with the correct cookie set
2. if I call the same application (just ports and machine name changes) deployed on the IIS server (v8.5) on the LAN the problem still persists (I can't find the cookie
![cookie](https://cloud.githubusercontent.com/assets/19210727/15154363/722975ae-16dd-11e6-979f-842c840659bc.png)
)
On the attached image you can see the cookie state for this two cases.
Once again, thanks.

**Comment by AndersAbel** [comment]
This looks fishy. Are you using the HttpModule, the MVC controller or the Owin middleware? If you're using the Owin middleware there are some [cookie issues](https://coding.abel.nu/2014/11/catching-the-system-webowin-cookie-monster/) that might have something to do with this.

But just to be sure I understand this correctly: When deployed on the web server and using IE, you see the Set-Cookie header, but no cookie is added in the outgoing requests? Can you post the complete set-cookie header value?

**Comment by Vanhalessio** [comment]
I'm using the HttpModule.
When deployed on the web server and using IE, you see the Set-Cookie header, but no cookie is added in the outgoing requests? 
correct. To be sure that I checked correctly, this are the steps I made on IE to check for the cookie
1) clear the cookie cache on IE
2) contact my server home page, with just the link for the rediction to the stub IdP via httpmodule
3) once on the stub, the cookie must have been already created. So I just manually pointed to the server home page on the IE address bar and checked with IE dev tools (F12) if the cookie existed but, as you can see from the "Real IIS Server" part of the previously attached image, it does not (no cookie on the request)
Please note that following the same procedure on the local visual studio web server, the cookie was present (see the other part of the attached image), so even if I'm not checking correctly, something seems to change between the two cases.

Can you post the complete set-cookie header value?
of course, there it is
Kentor.GqMPx5nPzZY7NvlE4KZMbHsOJ4cU8HtY2xKez9T_Z-HMCbxDFyvHLqu9=69Dbs8O3ZLbx7hiMvFVOq4tkjo8BMm1ClT2ZXm9Crdb23aZOVVNh6wHd9g6kxNCqushqAC8ZD-F4jIsrgyy-tAgAkXXa10O4smEQ6kKWsOQTU3PcKElp7hvCZgP3yBPPvALuL2-SvbM2TIJs3OjapXL_QyAAfikxYLN_0luocPk.; path=/; HttpOnly

**Comment by AndersAbel** [comment]
I get a "this bug shouldn't be possible" feeling from this. Which probably means there's something I'm missing.

When running on the real IIS server, can you use the dev tools or fiddler to verify that the set-cookie header is actually correctly sent by the server?

**Comment by Vanhalessio** [comment]
I think it should be related to the enterprise policies (such as compatibility mode) specified via GPO to all the IE clients of the organization. In fact, IE works for the localhost test because this policies shouldn't apply for that special address. Actually is not a problem, but I will let you have some confirmation if I will have the needs for further undestanding of the problem. Thanks a lot!

**Comment by AndersAbel** [comment]
So this issue can be closed now?

**Comment by Vanhalessio** [comment]
Yes, in my opinion. If I'll have further information, of course, I'll let you know. Thanks for the help!
