### ISSUE TITLE
Publish multiple AssertionConsumerService URLs in Metadata

### ISSUE THREAD

**Issue by explunit** [KentorIT/authservices#473]
Was thinking about a PR and wanted to be sure it's a good idea:

The problem: If you have a site that's served up on multiple DNS aliases, the metadata that's published contains the ACS of just one, but the sign-in commands specify the ACS URI based on whatever site was requested, and will thus be rejected by the Idp.

One idea: add a collection on `SPOptions` called `AssertionConsumerServices`. Then when serving the metadata, if this collection has entries, ignore the current request URL and publish the ones from `SPOptions.AssertionConsumerServices` instead.

Sound OK?

Maybe call it `AssertionConsumerServicesOverride` instead to make it more clear that it's not needed in the basic case?

Another approach might be to allow a list of `PublicOrigin` and construct them using that, but it seems problematic to cover ever possible site structure.

**Comment by explunit** [comment]
Something like this:
https://github.com/KentorIT/authservices/compare/master...explunit:acs-metadata?expand=1

Only added the code-based config at the moment.

**Comment by AndersAbel** [comment]
Would it be possible instead to use `PublicOrigin` and set it to one of the DNS names? To always have the SAML flow use a single host name? Then the ReturnUrl could be back to the correct domain name that the client is expected to use to access the services.

**Comment by explunit** [comment]
It becomes an issue of how then does the auth cookie issued during the SAML validation survive the redirection to the other domain.

**Comment by AndersAbel** [comment]
Of course. I didn't think of that. So multiple ACS urls there is... What about going one step further and add a list of alternative host names to the config? Then that list can be used for creating all endpoints. It's not just ACS, but also Logout is affected for the same reason with the cookies.

**Comment by explunit** [comment]
I was suggesting entire Urls because it might not be just the host name that's different between external and internal. But yes, for consistency I could add the collection for LogoutUrls too.

**Comment by explunit** [comment]
As it turns out, the new Notifications feature fills this need quite nicely. Something like this modifies the metadata before it is signed:
```
// ...
	kentorOptions.Notifications.MetadataCreated = MetadataCreated;
// ...

	private void MetadataCreated( ExtendedEntityDescriptor entityDescriptor, AuthServicesUrls urls )
	{
		var ssoDescriptor = entityDescriptor.RoleDescriptors.FirstOrDefault() as ExtendedServiceProviderSingleSignOnDescriptor;
		if ( ssoDescriptor == null ) return;

		var index = ssoDescriptor.AssertionConsumerServices.Count;
		foreach ( var extraUrl in _myExtraUrls )
		{
			var authServiceUrl = new AuthServicesUrls( extraUrl, kentorOptions.SPOptions.ModulePath );

			ssoDescriptor.AssertionConsumerServices.Add( index, new IndexedProtocolEndpoint()
			{
				Index = index++,
				IsDefault = false,
				Binding = Saml2Binding.HttpPostUri,
				Location = authServiceUrl.AssertionConsumerServiceUrl
			} );
		}
	}
```
