### ISSUE TITLE
Stop doing URL expansion

### ISSUE THREAD

**Issue by AndersAbel** [KentorIT/authservices#476]
Currently AuthServices expands return urls when doing login and logout. The idea was to handle cases with non-root-relative return urls, but that's probably never used. The url expansion has been error prone so our suggestion is to remove it.

**Comment by jpsullivan** [comment]
Yeah, I vote yes to this. We did something similar in our own application and eventually did the same thing.

Although rare, some people might still need this. Perhaps adding a setting such as "ApplicationUrl" would work as a potential solution to the problem?
