### ISSUE TITLE
Ability to set the SecurityTokenHandler inside of the SPOptions

### ISSUE THREAD

**Issue by IAmAnHurricane** [KentorIT/authservices#480]
Hi all!

Is there a possibility to create a setter for the token handler inside of the SPOptions class? 
That would be needed to customize SAML responses inside if e.g. ACS endpoints.

It would be enough to make the Saml2PSecurityTokenHandler virtual in SPOptions - I could then derrive for this type to provide own implementation to inject custom handler.

Regards,
Luke

**Comment by AndersAbel** [comment]
It is possible, but I'm a bit reluctant because I'm not entire happy with the current design. I'd like to change the design and if it has been opened up as an extension point it would be harder.

Can you describe what kind of customization you want to do so that I better understand what you are trying to achieve?

**Comment by IAmAnHurricane** [comment]
Hello!

Sure I can. Current implementation is based on the .NET one - so reading the token itself is implemented inside of pretty ugly code delivered within a .NET platform. This implementation does not implement a whole standard thou... Also - my client does have a specific configuration that makes some of the URIs in the assertions relative. Yes, I know that it is not following a standard; that is bad - and I cannot change it... 

Having the ability to inject a token handler - I could override some of the original .NET methods to overcome the issues it have today.

Sounds like the only usage as per today is within the Saml2Response class, where the token is being read and validated. This all is strongly coupled with MSs System.IdentityModel.Tokens namespace and .NET Saml2SecurityTokenHandler class. Having the SPOptions with ability to get/set the handler with this base class could make that open-closed from the library perspective - I could derive from the original code, and provide own handling when needed. 

What is Your vision of refactoring this fragment? 

Regards,
Luke

**Comment by AndersAbel** [comment]
I think you nailed it when you said "so reading the token itself is implemented inside of pretty ugly code delivered within a .NET platform". I'm thinking of moving away completely from WIF and implement the reading myself, but it's a lot of work so it's not anything that will be done within the foreseeable future.

Before we removed the `ISPOptions` interface (see #431) supplying an own handler was indeed possible so I don't think going back to enable that is much of an issue.

If you supply a PR on this I'll merge it.
