### ISSUE TITLE
Use of ClaimsPrincipal.Current in Logout command

### ISSUE THREAD

**Issue by explunit** [KentorIT/authservices#483]
Thinking about a possible PR and wanted to know if it's worth pursuing: it seems there's a mismatch in how `ClaimsPrincipal` is used in the different commands. In AcsCommand, the principle is part of the result object and you can decide what to do with it: use it as-is, discard it, transform it, whatever. 

But in LogoutCommand:
https://github.com/KentorIT/authservices/blob/v0.18.0/Kentor.AuthServices/WebSSO/LogOutCommand.cs#L116

There are three references to `ClaimsPrincipal.Current`. It would seem more consistent if the principal was an input to the command, or perhaps the data that's currently being pulled from the principal (e.g. external username, session id, etc).

Assuming this is worth pursuing, several options come to mind:
 1. Provide an overload for passing a different principal into `LogoutCommand` (and `IdentityProvider.CreateLogoutRequest`)
 2. Same as 1 but pass something like `ExternalUserData` object that has the needed values
 3. Create a new Notification something like `LogoutUserDataObtained` to allow overriding the (maybe null) values obtained from `ClaimsPrincipal.Current`

**Comment by kspearrin** [comment]
This is needed for a AspNet Core implementation since `ClaimsPrincipal.Current` is not set as expected from within the `LogoutCommand`. The correct ClaimsPrincipal is available via `Request.HttpContext.User` though.
