### ISSUE TITLE
For Kentor Authentication with SAML P need information about correct values need to mention for entityId

### ISSUE THREAD

**Issue by hanifmulani** [KentorIT/authservices#488]
Hi, I am connecting to on premises AD via ADFS using OWIN  for azure hosted ASP.NET MVC application.

Here is the snippet from ConfigureAuth.cs
```
 var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
            {
                SPOptions = new SPOptions
                {
                    EntityId = new EntityId("https://xx.xxx.xxx.xx/VirtualDirectory/")
                },

                AuthenticationType = "KentorAuthServices",
                Caption = "ADFS - SAML2p",
            };


            Uri metadataURI = new Uri("https://corp2.sts-dev.xxx.com/FederationMetadata/2007-06/FederationMetadata.xml");

            authServicesOptions.IdentityProviders.Add(new IdentityProvider(
                new EntityId("http://corp2.sts-dev.xxx.com/adfs/services/trust"),
                authServicesOptions.SPOptions)
            {
                MetadataLocation = metadataURI.ToString(),
                LoadMetadata = true,
            });

            app.UseKentorAuthServicesAuthentication(authServicesOptions);
```
I am referring the below blog post,
http://nzpcmad.blogspot.in/2016/01/owin-adpnet-mvc-application-with.html

__Can you please help me to know I am doing any mistake while mentioning the entityId values..?__

**Comment by AndersAbel** [comment]
I don't understand what your question is. Is it not working? In that case, can you describe the error? Or do you just want a confirmation that it looks right?

**Comment by hanifmulani** [comment]
Hi, With code spinet mentioned above I am unable to connect, It does show me login page of identity provider and after entering the credentials it throws error. Unfortunately the error message is very generic,

•Activity ID: 00000000-0000-0000-870c-0080000000fc
•Relying party: AAA
•Error time: Thu, 02 Jun 2016 11:01:29 GMT
•Cookie: enabled
•User agent string: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729)

With this regards I wanted to check what values I need to put in the entity Id fields..?

Now, I put in https://xx.xxx.xxx.xx/VirtualDirectory/  as  'App ID (Wtrealm) which is registered on the ADFS identity server as a Relying Party Trust identifier' and

'http://corp2.sts-dev.xxx.com/adfs/services/trust' as ADFS Identifier.

Can you please help me to know what values I need to configure so that I can check with my Infra team for the same.

Thanks a lot for your time.

**Comment by AndersAbel** [comment]
There are no apparent errors in the config you've shown. This looks more like an ADFS configuration issue which isn't anything I know about. If the blog posts by Nzpcmad is not enough, you need to find someone that knows ADFS better for help on that side.

**Comment by explunit** [comment]
@hanifmulani I'm not an expert on ADFS, but I do know that it supports consuming metadata such as is produced by Kentor.AuthServices, so perhaps using that approach would reduce confusion about which values each end of the integration is using.

**Comment by hanifmulani** [comment]
Thanks explunit and Anders I fixed the issue with the help of my ADFS team.

**Comment by leonardocf83** [comment]
Hi @hanifmulani, how did the ADFS team solved the issue? It was necessary to change anything in kentor configuration?
