### ISSUE TITLE
dynamic acs url question

### ISSUE THREAD

**Issue by Christfigure** [KentorIT/authservices#490]
For our Saml setup, we have an endpoint that we provide our clients that is unique to them (https://example.com/Saml/Sso/{uniqueId}).  I understand that the metadata generated by the plugin will have an ACS url of the format "https://example.com/{moduleName}/Acs".

I want to be able to provide clients with our metadataurl and be done, as opposed to giving custom setup instructions per client.

Is there a recommended way to handle this situation?  Off the top of my head I see two options:

1) Accept incoming saml assertions at the endpoint "/{moduleName}/Acs" and somehow figure out what idp info to use for the request

2) Be able to dynamically generate the ACS url when the metadata is requested based on the request (i.e. https://example.com/{moduleName}/Metadata/{uniqueId})

**Comment by explunit** [comment]
This isn't exactly the same as your situation, but see #473 for an approach I used to customize metadata.

**Comment by Christfigure** [comment]
The metadatacreated callback hook worked for me as well (thanks for the link!).  I ended up following scenario #2 from above and in the metadatacreated callback re-write the AssertionConsumerServices urls based on the uniqueId for the request.

**Comment by l3ender** [comment]
@biddlem - we are wanting to handle a similar scenario. For your solution, were you able to build the ACS URL based on any request properties? For our scenario, we would like to modify the ACS URL based on the hostname of the request which is initiating the SSO attempt.

Thanks!

**Comment by AndersAbel** [comment]
@l3ender The v1 and v2 versions of the library unfortunately has the ACS url hard coded. To make it dynamic, you would need to create a custom version. V3 will offer this flexibility eventually.

**Comment by l3ender** [comment]
I was able to accomplish my need using `GetPublicOrigin` to update the ACS based on properties in the request:

```c#
new Saml2Notifications()
{
    GetPublicOrigin = (request) =>
    {
        string host = request.QueryString["customHost"].FirstOrDefault();
        if (!string.IsNullOrWhiteSpace(host))
        {
            Uri original = request.ApplicationUrl;
            Uri updated = new UriBuilder(original.Scheme, host, original.Port, original.PathAndQuery).Uri;
            return updated;
        }
        return null;
    }
}
```

One suggestion for v3: it would be helpful to have additional original request information such as HTTP headers available in `HttpRequestData`. In our case, we had to have our proxy/load balancer insert a query parameter to accomplish the need.

Thanks!

**Comment by AndersAbel** [comment]
@l3ender That was a cool solution.

For `v3` the full HttpContext will be used directly instead of `HttpRequestData`. So much easier when the code doesn't have to work across three different types of Http contexts.
