### ISSUE TITLE
No RelayState was detected

### ISSUE THREAD

**Issue by CharlieVoid** [KentorIT/authservices#492]
Hi!

My application fails to detect the RelayState in a solicited SAMLResponse. I cannot see what's wrong, it is there according to Chrome DevTools (bottom of screenshot). The response comes from Azure AD and my .NET WebApi application runs in Visual Studio 2013 IIS Express. Kentor.AuthServices and Kentor.AuthServices.Owin 0.17.2.

![image](https://cloud.githubusercontent.com/assets/15904517/15783096/0928892c-29ad-11e6-952e-504d66dfcfde.png)

Best regards

Johan

**Comment by AndersAbel** [comment]
Can you check if a cookie with a name matching the relaystate is properly set when redirecting to the idp?

Does the problem persist if you update to 0.18.0?

**Comment by CharlieVoid** [comment]
No cookie is set.

The problem does not go away with 0.18.0.

**Comment by AndersAbel** [comment]
If the cookie isn't set it might be a cookie monster issue: https://coding.abel.nu/2014/11/catching-the-system-webowin-cookie-monster/

Try adding the cookie saver middleware referenced in that post.

**Comment by CharlieVoid** [comment]
I already use the cookie middleware.

I should be clear on the method of making the redirect to the IdP. I roll it like this:

`var options = new KentorAuthServicesAuthenticationOptions(true);
var idp = options.IdentityProviders[new EntityId("https://NOTFORTHEPUBLICEYE")];
var urls = new AuthServicesUrls(new Uri(options.SPOptions.EntityId.Id), options.SPOptions.ModulePath);
var req = idp.CreateAuthenticateRequest(urls);
var xmlString = req.ToXml();
var bytes = Compress(Encoding.UTF8.GetBytes(xmlString));
var base64String = Convert.ToBase64String(bytes);
var urlEncoded = HttpUtility.UrlEncode(base64String);
var relayState = HttpUtility.UrlEncode(req.RelayState);
return Redirect("https://NOTFORTHEPUBLICEYE?SAMLRequest=" + urlEncoded + "&RelayState=" + relayState);`

The IdP then sends me to my application ACS with SAMLResponse and RelayState in the form data. Then I get the error message "Received message contains unexpected InResponseTo..." before being redirected to the return Url specified in: 
`<kentor.authServices entityId="http://localhost:50825" publicOrigin="http://localhost:50825" modulePath="/saml2/v1" returnUrl="http://localhost:4711/#/sso" discoveryServiceUrl="http://localhost:50825/DiscoveryService">`

I got this flow to work like a year ago, without handling the relay state.

Best regards

Johan

**Comment by AndersAbel** [comment]
Oh, you're not using the owin middleware from Kentor.AuthServices.Owin? If you're using the Kentor.AuthServices package directly you need to update your code. AuthServices used to keep the pending authn request state data in memory, but now uses cookies to store it. You'll have to move over to using a binding (`Saml2Binding.Get(Saml2BindingType.HttpRedirect)`) for your generated AuthnRequest. Then you'll get the cookie info needed in the generated `CommandResult`.

You need to set a cookie from the `CommandResult.SetCookieName` and data in `CommandResult.GetSerializedRequestState`. It's also critical that you encrypt the serialized data before storing it in the cookie. See for example how it is done in `CommandResultHttpExtensions.ApplyCookies`.

Or move over to the Owin middleware instead to avoid having to do this manually.

**Comment by AndersAbel** [comment]
I was a bit too quick in my response. The cookie data is actually created at an higher level in the code. It's done by the `SignInCommand` which is what you should call if you don't want to use the Owin middleware. It is of course possible to use the lower level APIs like you do, but there's a lot more work and plumbing code needed.

**Comment by CharlieVoid** [comment]
Ah, the move of pending requests from in memory makes perfect sense as an explanation for this!

I do use Kentor.AuthServices.Owin for unsolicited responses, but the application cookie is only used transiently to get a OAuth 2.0 token by my WebApi application.

If I were to use AuthServices.Owin, how do I initialize the SP-initiated flow to a specific Idp?

**Comment by AndersAbel** [comment]
When you call `Authentication.Challenge` (typically done in `ChallengeResponse`), you can put the `EntityId` of the Idp in the `AuthenticationProperties` dictionary with key `idp`. Or if you don't have simple access to where `Authentication.Challenge` is called, you can also put it directly in the owin dictionary with a key of `KentorAuthServices.idp`. Then the owin middleware will pick that up and use that Idp.

**Comment by CharlieVoid** [comment]
Thank you for excellent support Anders!

The solution was, as suggested, this:
`owinContext.Environment.Add("KentorAuthServices.idp", new EntityId("https://the-entity-id"));`

and this:

`owinContext.Authentication.Challenge("KentorAuthServices");`

Cheers!

Johan
