### ISSUE TITLE
Logout request RelayState as POST parameter?

### ISSUE THREAD

**Issue by explunit** [KentorIT/authservices#495]
Logout command `HandleResponse()` assumes the RelayState will be in the querystring:
https://github.com/KentorIT/authservices/blob/v0.18.0/Kentor.AuthServices/WebSSO/LogOutCommand.cs#L213

But with one of my Idp's I am seeing it as part of the POST body. And this results in:

```[InvalidOperationException: Sequence contains no elements]
   System.Linq.Enumerable.Single(IEnumerable`1 source) +496
   Kentor.AuthServices.WebSso.LogoutCommand.HandleResponse(UnbindResult unbindResult, HttpRequestData request) +144
   Kentor.AuthServices.WebSso.LogoutCommand.Run(HttpRequestData request, String returnPath, IOptions options) +191```

**Comment by AndersAbel** [comment]
Isn't this a duplicate to #472?

**Comment by explunit** [comment]
Yes, you're right. Closing.
