### ISSUE TITLE
Federated Single Logout

### ISSUE THREAD

**Issue by shuppert** [KentorIT/authservices#503]
What's required to implement SLO?  I'm using OneLogin and they provide an SLO endpoint which I configured in my SPOptions/SingleLogoutServiceUrl but it doesn't appear to be called when my application calls the IdentityServer3 logout.  I looked at the SampleIdentityServer3 project but it looks like it's not logging out of IdSvr and is only logging out of the 3rd party Idp.

**Comment by AndersAbel** [comment]
First you need to make sure that all requirements in AuthServices are satisfied (I should really write some documentation on this).

1. Check that the metadata exposed by AuthServices contains a `SingleLogoutService`. If not, add a service-certificate with use `Both` (default) or `Signing`.
2. Check that you have the `AuthServicesClaimTypes.LogoutNameIdentifier` and `AuthServicesClaimTypes.SessionId`. They are generated by AuthServices, but if you have some kind of claims mapping/translation you will need to carry them over to the actual identity used in the session.

**Comment by shuppert** [comment]
That's good information.  I stepped through the logout code and I don't have an SPOptions.SigningServiceCertificate.  I'm configuring my SPOptions in code and this property is read-only.  What's the secret to setting the Signing Certificate from code?

**Comment by explunit** [comment]
The property itself is read-only, but you can call `.Add()` on it, e.g.

`serviceProviderOptions.ServiceCertificates.Add( myCertificate );`

**Comment by shuppert** [comment]
Good call.  That works to add the certificate.  However the X509 certificate supplied by OneLogin doesn't contain a private key which results in "Provided certificate is not valid because it does not contain a private key." being thrown.

**Comment by explunit** [comment]
Are you sure you're using the right certificate? I would assume OneLogin is giving you their public key for the purpose of validating SAML assertions sent by them, but for signing **outbound** requests (e.g. LogoutRequest) I would guess you'll generate your own certificate and thus have the private key.

**Comment by shuppert** [comment]
Excellent!  Another good call.  I didn't think about that.  Single log out now works with OneLogin.  The only bad thing is that I lose my redirect back to the calling app.  IdentityServer3 has a post logout redirect built-in.  Is there a way to make this work with Kentor Authservices?

**Comment by explunit** [comment]
Sorry, that part I'm not as familiar with. The scenario you're looking for doesn't work with the SampleIdentityServer3 project either?

**Comment by AndersAbel** [comment]
@shuppert The logout flow with IdSrv3 is very complex as there are multiple levels of relying parties/identity providers with app->IdSrv3->Idp. Can you describe what flow you have when the post logout redirect doesn't work? From where do you initiate the logout? Where do you end up? What did you expect?

If you could do some debugging that would of course be very welcome.

**Comment by shuppert** [comment]
My client application is JavaScript/Sencha .  All login/logout requests are initiated by the client application.  I have two configurations:
JS -> IdSvr
JS -> IdSvr -> OneLogin

AuthServices is used in the second configuration to communicate with OneLogin.  I found the AuthServices/Logout endpoint which I configured in OneLogin.  I’m running into issues with the Logout response from OneLogin not being signed: “Received a LogoutResponse from https://app.onelogin.com/saml/metadata/... that cannot be processed because it is not signed”.

Ideally I’d like the behavior to be the same regardless of the configuration.  The user initiates the logout and afterwards is automatically returned to the calling application.

**Comment by shuppert** [comment]
If I comment out this line in LogoutCommand the signout and redirect works as expected.
VerifyMessageIsSigned(unbindResult, options);

There doesn't appear to be a way to get OneLogin to sign the LogoutResponse.  I tried changing WantAssertionsSigned and WantAuthnRequestsSigned but neither have any effect on the LogoutResponse returned.

Is there a way to bypass the signature checking on a LogoutResponse?

**Comment by AndersAbel** [comment]
The SAML profiles specification section 4.4.3.4 states that:

> The <LogoutResponse> message MUST be signed if the HTTP POST or Redirect binding is used. The HTTP Artifact binding, if used, also provides for an alternate means of authenticating the response issuer when the artifact is dereferenced.

AuthServices enforces signing on all incoming `<LogoutResponse>` messages. Which is not entirely correct as if using the Artifact binding it shouldn't (I've filed #511 as a bug on that).

Do you know which binding is used for the logout response from OneLogin?

It is possible to add a compatibility setting to AuthServices to allow unsigned `<LogoutResponse>` messages.

**Comment by shuppert** [comment]
I have SingleLogoutServiceBinding set to HttpRedirect.  I also tested with HttpPost and Artifact and I ran into the same issues without commenting out the signature check.

**Comment by AndersAbel** [comment]
The `SingleLogoutServiceBinding` decides how outgoing logout messages are sent from AuthServices. What matters here is the binding used by incoming messages from the Idp. Use a tool such as SAML Tracer for Firefox or SAML Dev Tools for Chrome to inspect the received messages.

**Comment by shuppert** [comment]
Here's what I was able to capture.  SAML DevTools appears to hang OneLogin.  I don't see anything labeled binding in there.

[samlTraffic.txt](https://github.com/KentorIT/authservices/files/325946/samlTraffic.txt)

**Comment by AndersAbel** [comment]
No, you're right it's not in the actual messages. Try again and check the raw http request contents in the request that generates the exception about missing signature in AuthServices.

* If it's an artifact binding, you'll have a query string param called artifact.
* If it's an http redirect binding you'll have a query string param called SamlResponse.
* If it's an http post binding you'll have a clean query string and some body contents instead.

**Comment by shuppert** [comment]
Thanks for the clarification.  Looks like an HTTP redirect.

The callback looks like this:
https://localhost:44333/core/AuthServices/Logout**?SAMLResponse**=fZI%2Fb4MwEMW....

**Comment by AndersAbel** [comment]
Then there should be a `SigAlg` and a `Signature` query string parameter too. If not, the signature is missing and it is not following the specification.

I assume we could add a Compatibility setting that allows non-signed logout messages.

**Comment by shuppert** [comment]
No, the request has parameters for SAMLRequest, SigAlg, Signature, and RelayState.  But the response only has parameters for SAMLResponse and RelayState.

[Logout-Request-Response.txt](https://github.com/KentorIT/authservices/files/326090/Logout-Request-Response.txt)

**Comment by AndersAbel** [comment]
Then they're missing the required signature. I'd suggest you bring it up with them with the profile reference I mentioned earlier. If you need a fix on the AuthServices side, we can do that as a sponsored development. Mail me if that is interesting.

**Comment by mitsufu** [comment]
Hi @AndersAbel,
I've made my first test from your SampleOwinApplication and my Adfs server.

- I've configured the Relaying Party from the metadata issued from /AuthServices successfully.
- The sample worked directly, Kentor owin extension is passive with ExternalCookie, "KentorAuthServices" appeared on the login page and jumps successfully to the adfs login page. When redirecting back to my service, I had no logininfo in AccountController/ExternalLoginCallback. I've added a custom ClaimsAuthenticationManager implementation and added a correct ClaimTypes.NameIdentifier to the identity based on the incoming claim (upn from adfs).
Then everything went fine in the ExternalLoginCallback and I'm in the end correctly signed on Asp.Net Identities (ApplicationCookie) which is my only identity. Am I right ?

My problem is I don't understand how to call "log off". I tought AuthenticationManager.SignOut("ApplicationCookie", "KentorAuthServices"); would have work.

I've read this up on this discussion but I can't find where to catch those claims during signin and then how to trigger signout:

"Check that you have the AuthServicesClaimTypes.LogoutNameIdentifier and AuthServicesClaimTypes.SessionId. They are generated by AuthServices, but if you have some kind of claims mapping/translation you will need to carry them over to the actual identity used in the session."

I would be very thankful if you could give me some guidance.

Thanks
