### ISSUE TITLE
Can authServices metadata return ACS endpoint in https instead of http

### ISSUE THREAD

**Issue by kb99** [KentorIT/authservices#506]
Below is a snippet of the metadata xml that gets returned when I call my /Authservices endpoint.

```
<SPSSODescriptorAuthnRequestsSigned="true"protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
  <KeyDescriptor>
    <KeyInfoxmlns="http://www.w3.org/2000/09/xmldsig#">
       <X509Data>…</X509Data>
    </KeyInfo>
  </KeyDescriptor>
  <SingleLogoutServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"Location="http://apps.aaaaaa.com/identity/AuthServices/Logout"/>
  <SingleLogoutServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"Location="http://apps.aaaaaa.com/identity/AuthServices/Logout"/>
  <AssertionConsumerServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"Location="http://apps.aaaaaa.com/identity/AuthServices/Acs"index="0"isDefault="true"/>
  <AssertionConsumerServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact"Location="http://apps.aaaaaa.com/identity/AuthServices/Acs"index="1"isDefault="false"/>
</SPSSODescriptor>
```

The Urls for `SingleLogoutServiceBinding` and `AssertionConsumerServiceBinding` are returned as http. All requests to our app server are made via https but our app server is sitting behind a loadbalancer and all https connections terminate at the loadbalancer instead of the app server.

Is it possible to get the metadata document to return the `SingleLogoutServiceBinding` and `AssertionConsumerServiceBinding` endpoints with https instead of http?  Is there a config setting that will allow me to force the urls to include https?

I am trying to integrate our application with a AD FS Idp. I can not successfully import the metadata into AD FS due to the http urls.

**Comment by AndersAbel** [comment]
Metadata is generated with the protocol that you use to access the metadata endpoint. If you use https download it, the addresses will be https.

If that's not a possibility (e.g. https termination in an external proxy) you can use the `PublicOrigin` setting.

**Comment by kb99** [comment]
Excellent - yes that worked.
Thank you for your quick response.
