### ISSUE TITLE
Okta as an External IDP in VS2015/VS2013

### ISSUE THREAD

**Issue by JChaneyGuardian** [KentorIT/authservices#508]
I am failry new to .Net development and VERY new to SAML2.0.  My company is currently using Okta as our IDP.
I've been trying to setup Okta as an external IDP for a couple days.   I want to be able to allow users outside of Okta to create accounts but those within the company to simply connect using Okta.

I found Kentor.AuthServices and Kentor.AuthServcies.OWIN.  THANK YOU!  I installed the assemblies from Nuget and started setting up my configuration.  

Everything was working fairly well except for one thing. When my app would go to the login page it would immediately go to the Okta login.  I searched online for answers but they all came back with telling me how to setup Okta as SSO.  I tried setting my apps login as the Discovery page but then when I chose Kentor/Okta it just took me back to the login page.

Finally I downloaded the source from github so I could debug and see what was happening and found it was not compatible with my VS2013.   I downloaded the Tag v0.13.0 source made a few adjustments to my configuration to fit the old configuration API and it started working as intended.  Basically I had to switch back to loading the configuration values directly rather than through meta data and the X509 cert used to be configured under the idp as a single value rather than using AddConfigurationKey().

When I asked for an [Authorize] action I was immediately taken to my apps login page.  I could login locally or with Google or Kentor/Okta and assocate the external ids with my local users.

I don't know if I was doing something wrong, if there was a "feature" change or if this is a bug.

We will be going to VS2015 in a few weeks and I'm wondering if we are going to see this issue again when we upgrade.

This is the configuration I was using in Startup.Auth before switching to v0.13.0
` 
```
       private static KentorAuthServicesAuthenticationOptions CreateAuthServicesOptions()
        {
            var spOptions = CreateSPOptions();
            var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
            {
                SPOptions = spOptions
            };

            // IdentityProvider comes from Okta under the application SAML information
            var idp = new IdentityProvider(new EntityId("http://www.okta.com/xxxxxxxxxxxxxxx"), spOptions)
            {
                MetadataLocation = "https://xxxxxxxxxx.oktapreview.com/app/xxxxxxxxxxxxxx/sso/saml/metadata",
                LoadMetadata = true

                // ***********************************************************************************
                // NOTE:  By switching to LoadMetaData=true it will read the Okta configuration directly from Okta
                //AllowUnsolicitedAuthnResponse = true,
                //Binding = Saml2BindingType.HttpRedirect,
                //// SingleSignOnServiceUrl comes from Okta under the application SAML information
                ////SingleSignOnServiceUrl = new Uri("https://xxxxxxxxx.oktapreview.com/app/xxxxxxxxxx_testappjac_1/xxxxxxxxxxxxxxxx/sso/saml")
                // ***********************************************************************************
            };

            // ***********************************************************************************
            // NOTE:  By switching to LoadMetaData=true it will read the Okta configuration directly from Okta
            //idp.SigningKeys.AddConfiguredKey(
            //    new X509Certificate2(
            //        HostingEnvironment.MapPath(
            //            // Changed to the file that contains my cert that came from Okta App info
            //            "~/App_Data/OktaPreview.cer"))); 
            // ***********************************************************************************

            authServicesOptions.IdentityProviders.Add(idp);


            // ***********************************************************************************
            // NOTE I'm not using Federation so I don't think I need to configure this
            //      Furthermore, when I simply changed the port of this webapp the start up time
            //      for the app was attrocious.  When I removed that the performance hit went away.
            // It's enough to just create the federation and associate it
            // with the options. The federation will load the metadata and
            // update the options with any identity providers found.
            //new Federation("http://localhost:52071/Federation", true, authServicesOptions);
            // ***********************************************************************************
            

            return authServicesOptions;
        }

        private static SPOptions CreateSPOptions()
        {
            var swedish = CultureInfo.GetCultureInfo("sv-se");

            var organization = new Organization();
            organization.Names.Add(new LocalizedName("Kentor", swedish));
            organization.DisplayNames.Add(new LocalizedName("Kentor IT AB", swedish));
            organization.Urls.Add(new LocalizedUri(new Uri("http://www.kentor.se"), swedish));

            var spOptions = new SPOptions
            {
                //EntityId = new EntityId("http://localhost:57294/AuthServices"),
                //ReturnUrl = new Uri("http://localhost:57294/Account/ExternalLoginCallback"),
                //DiscoveryServiceUrl = new Uri("http://localhost:52071/DiscoveryService"),

                // I just changed to https and the port to my apps port
                EntityId = new EntityId("https://localhost:44301/AuthServices"),
                ReturnUrl = new Uri("https://localhost:44301/Account/ExternalLoginCallback"),
                // ****************************************************************************************
                // NOTE: Discovery Service is NOT working.  It keeps going here to sign onto Okta even
                //       when the user has gone to the login screen and choosen Okta to be used for login
                // NO!! The discovery service sounds like it allows the user to pick which IDP they want to use
                // DiscoveryServiceUrl = new Uri("https://localhost:44301/Account/Login"),
                // ****************************************************************************************
                Organization = organization
            };

            var techContact = new ContactPerson
            {
                Type = ContactType.Technical
            };
            techContact.EmailAddresses.Add("xxxxxx@xxxxxx.com"); // <= changed to my email
            spOptions.Contacts.Add(techContact);

            var supportContact = new ContactPerson
            {
                Type = ContactType.Support
            };
            supportContact.EmailAddresses.Add("xxxxxxx@xxxxxxxx.com"); // <= changed to my email
            spOptions.Contacts.Add(supportContact);

            var attributeConsumingService = new AttributeConsumingService("AuthServices")
            {
                IsDefault = true,
            };

            //attributeConsumingService.RequestedAttributes.Add(
            //    new RequestedAttribute("urn:someName")
            //    {
            //        FriendlyName = "Some Name",
            //        IsRequired = true,
            //        NameFormat = RequestedAttribute.AttributeNameFormatUri
            //    });
            attributeConsumingService.RequestedAttributes.Add(
                new RequestedAttribute("urn:firstName")
                {
                    FriendlyName = "First Name",
                    IsRequired = true,
                    NameFormat = RequestedAttribute.AttributeNameFormatUri
                });
            attributeConsumingService.RequestedAttributes.Add(
                new RequestedAttribute("urn:lastName")
                {
                    FriendlyName = "Last Name",
                    IsRequired = true,
                    NameFormat = RequestedAttribute.AttributeNameFormatUri
                });
            attributeConsumingService.RequestedAttributes.Add(
                new RequestedAttribute("urn:email")
                {
                    FriendlyName = "E-Mail",
                    IsRequired = true,
                    NameFormat = RequestedAttribute.AttributeNameFormatUri
                });

            attributeConsumingService.RequestedAttributes.Add(
                new RequestedAttribute("Minimal"));

            spOptions.AttributeConsumingServices.Add(attributeConsumingService);

            // Optional so I removed it
            //spOptions.ServiceCertificates.Add(new X509Certificate2(
            //    // Changed to the file that contains my cert that came from Okta App info
            //    AppDomain.CurrentDomain.SetupInformation.ApplicationBase + "/App_Data/OktaPreviews.pfx"));

            return spOptions;
        }
`

**Comment by AndersAbel** [comment]
I don't understand what the problem was in the first place. The `DiscoveryService` is an advanced concept that you should leave to `null` to have it disabled.

You can use the latest nuget packages even if you only run VS2013. They are runtime compatible. An alternative is to download VS2015 community edition which is free to use (even for large organization when doing open source work)

**Comment by mkhatuntcov** [comment]
Thanks Anders for yours amazing work!
I was trying to make Okta works with OWIN Sample and didn't noticed DiscoveryService. I will probably will add this into your docs if you Ok about it.

**Comment by AndersAbel** [comment]
@mkhatuntcov Does Okta supply a `DiscoveryService`? In most cases it should be left as `null` - it's usually a mistake when someone sets it (which they do because the sample applications use them).

**Comment by JChaneyGuardian** [comment]
Thank you for the interest in my issue.  The problem isn't the Discovery Service.  The issue is that when I download the newest Kentor AuthServices assemblies from NuGet and go to my site I am ALWAYS redirected to Okta and not my Login Page.  That's great for Single Sign On but not when I want to be able use Okta as one option for Authentication.

I don't have Visual Studio 2015 yet so I downloaded the source for Tag v0.13.0 of Kentor.  When I removed the NuGet assemblies and started using the Tag v0.13.0 source it worked as I originally wanted.

**Comment by AndersAbel** [comment]
@JChaneyGuardian The changed behaviour is because AuthServices is now by default an "Active" middleware, intercepting any response with a 401 status code. Being active is needed to get single logout when issuing a logout without specifying AuthType. Set the type to passive in the KentorAuthServicesAuthenticationOptions and you should get the 0.13.0 behaviour in the latest release.

**Comment by JChaneyGuardian** [comment]
Thanks Anders.  I finally got back to this project and your suggestion worked.  

For others reading this later the actual setting is called AuthenticationMode and it's part of the Microsoft.Owin.Security.AuthenticationOptions class which is the parent class of KentorAuthServicesAuthenticationOptions.

This is the code from Startup.Auth.cs  Startup.ConfigureAuth() that I used to set it.

>            app.UseKentorAuthServicesAuthentication(new KentorAuthServicesAuthenticationOptions(true)
>             {
>                 AuthenticationMode = Microsoft.Owin.Security.AuthenticationMode.Passive,
>             });

**Comment by AndersAbel** [comment]
I'm actually considering changing back to having the middleware as passive by default - but to still do federated log out if enabled. @JChaneyGuardian do you have any thoughts on that?

**Comment by JChaneyGuardian** [comment]
I am sorry.  I am very new to using OWIN, SAML2.0 and Kentor AuthServices, so, I don't have much of an opinion.  However I can tell you how I'm using it and hop that helps.

The main project I am using Kentor AuthServices in uses Okta for SSO so the fact that it defaulted to always using Okta worked well for me.  However, a co-worker of mine is working on a project that requires people accessing his system from within our WAN to authenticate to Okta but people outside the WAN to use a local account.   Your answer actually went to helping his project.

The systems I write for work are accessed from machines that are assigned to individuals so there is no need to sign-out.  I think for my co-workers system it most likely will not be accessed from a public PC and so sign-out is not needed.

**Comment by AndersAbel** [comment]
The change mentioned above, is now in master and will be part of the next (v0.20.0) release.
