### ISSUE TITLE
unexpected InResponseTo, No RelayState was detected issue

### ISSUE THREAD

**Issue by jaydinslage** [KentorIT/authservices#518]
I've been researching this issue for quite some time now and want to get your take on it:

On our production servers, we get the following error:
`Kentor.AuthServices.Exceptions.Saml2ResponseFailedValidationException: Received message contains unexpected InResponseTo "idd8d95374ce064adcbcc578ea350fbc14". No RelayState was detected so message was not expected to have an InResponseTo attribute`

The issue, obviously, is that the Kentor cookie is not in the HTTP POST. Well, it should be, lol. I am unable to reproduce this issue on our local machines and we receive quite a few every day.

 What I do know is that the "Set-Cookie" header **is** being set on the 303 redirect (the Kentor cookie). It does not, however, come back when the user has authenticated with the external system and they post to us (the HTTP POST to the Acs endpoint). This has happened on all browsers (Firefox, Chrome, and IE).

The post contains a valid SAMLResponse. In fact, the response the send looks perfect, except that the cookie is not there. I cannot determine any thing that is weird or wonky with the outgoing request that might be what is causing the issue.

Any ideas, I'm at a loss.

**Comment by hmarcelodn** [comment]
I am experiencing same issue.

**Comment by hmarcelodn** [comment]
https://github.com/KentorIT/authservices/issues/517

**Comment by AndersAbel** [comment]
Looks like #517 describes exactly the same problem, closing this issue as a duplicate. Please check comments on #517 for suggestion of how to debug.

**Comment by Coderrob** [comment]
Seeing this too with 0.19 but not in 0.18.1 release packages.
