### ISSUE TITLE
Can I use it With okta? I GetExternalIdentity retuns null.

### ISSUE THREAD

**Issue by hmarcelodn** [KentorIT/authservices#519]
Hi guys,

Can I use differents Idp like Okta and Kentor Stub Idp and then choose one of them by using a ChallengeResult("Okta") ChallengeResult("Kentor") then login at different places according  a condition?

I have to do something like that using Azure Cloud SSO and Okta. Is it possible to do?

Thanks and regards.

**Comment by AndersAbel** [comment]
Yes, it's possible to chose Idp based on the provider parameter to the `ChallengeResult`. To do that you need to load multiple instances of the AuthServices owin middleware and assign each of them a unique AuthenticationType (remember to set a unique ModulePath too.)

**Comment by hmarcelodn** [comment]
Abel, I am doing like this:          

  var providers = DependencyConfig.Get<IAppIdentityProvider>().Get();
            foreach (var provider in providers)
            {
                if (provider.ProviderType.Equals("saml2", StringComparison.CurrentCultureIgnoreCase))
                {
                    app.UseKentor(
                        authenticationType: provider.Name,
                        providerId: new EntityId(provider.ProviderId),
                        providerUrl: provider.ProviderUrl,
                        metadataUrl: provider.ProviderMetadataUrl,
                        certificate: new System.Security.Cryptography.X509Certificates.X509Certificate2(provider.X509Certificate2));
                }
            }

**Comment by hmarcelodn** [comment]
Abel let me show you some code. 

Here is my HomeController:

	[Authorize]
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}

It requires authorization since it is a single page application. Here I found a 401 and it should send me to /Account/Login per Owin configuration. So I would like to raise a ChallengeResult and decide which Idp to use.

            app.UseCookieAuthentication(new CookieAuthenticationOptions
			{
				AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
				LoginPath = new PathString("/Account/Login"),
                Provider = new CookieAuthenticationProvider
                {
                    // Enables the application to validate the security stamp when the user logs in.
                    // This is a security feature which is used when you change a password or add an external login to your account.  
                    OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, ApplicationUser, int>(
                                   validateInterval: TimeSpan.FromMinutes(30),
                                   regenerateIdentityCallback: (manager, user) => user.GenerateUserIdentityAsync(manager),
                                   getUserIdCallback: (user) => user.GetUserId<int>())
                }
            });

So the way I register the different instances of the middleware are:

            var providers = DependencyConfig.Get<IAppIdentityProvider>().Get();
            foreach (var provider in providers)
            {
                if (provider.ProviderType.Equals("saml2", StringComparison.CurrentCultureIgnoreCase))
                {
                    app.UseKentor(
                        authenticationType: provider.Name,
                        providerId: new EntityId(provider.ProviderId),
                        providerUrl: provider.ProviderUrl,
                        metadataUrl: provider.ProviderMetadataUrl,
                        certificate: new System.Security.Cryptography.X509Certificates.X509Certificate2(provider.X509Certificate2));
                }
            }

By default it is always sending me to Kentor Idp by default, and it does not send me to /Account/Login which is what I am expecting to choose which provider I want to use.

Is there something wrong with my configiuration?

Thanks!

**Comment by AndersAbel** [comment]
This is a too complex issue to solve here on the issue tracker. Please refer to our e-mail conversation about commercial support options.
