### ISSUE TITLE
Selecting Home Realm when using ADFS 3.0 SAML endpoints

### ISSUE THREAD

**Issue by JFerretti** [KentorIT/authservices#522]
First off apologies if this is the wrong place to post this question.

I have successfully used authservices to authenticate the SAML endpoint of our ADFS 3.0 server using the OWN middleware configuration option.

We want to make it such that we can skip the Home Realm Discovery page of ADFS where the user initially selects the Claims Provider to authenticate against.

We know the provider each user logging in will use so this should be simple.

From what I can see there is no "out of the box" way of doing this with ADFS' SAML implementation - the documentation discusses idp selection but it seems to me this isn't the right thing - please correct me if I'm wrong.

So my question is is it possible to pre-select the Home Realm using authservices in this kind of set up?

My current proposed solution would be to create a cookie to store the selected home realm upon the user typing their email address in to our app and then adding to ADFS's onload.js to pull the cookie out and use it to select the home realm. Whilst I think this would work it feels like quite a brittle hack.

Is there another way to send data on the home realm with the authentication request using authservices and OWIN? This would be at the point you call `GetOwinContext().Authentication.Challenge` ideally.

Thanks,
James

**Comment by AndersAbel** [comment]
Home realm is an ADFS thing. I don't know if there is any way/extension to SAML2 to set the realm in the AuthnResponse. To be able to do anything from AuthServices, there must be support in ADFS (either built in or customized) to receive a home realm selection in the SAML2 AuthnRequest.

**Comment by JFerretti** [comment]
Thanks for the response, it would seem not easy with ADFS 3.0. Previous to this you could add a "whr" clause to the querystring when requesting but that is now deprecated.

I'm going to go ahead with the cookie hack and see if it will work.

Thanks,,
James
