### ISSUE TITLE
Problem with singnature on Assertions

### ISSUE THREAD

**Issue by janobrestad** [KentorIT/authservices#523]
I'm trying to use a Saml2 provider with Identity Server using the Kentor.AuthServices.Owin plugin. 

I can login with the provider, but the validation of the signature fails.

Using the SAML Dev tools I can see that there is a signature on the Response node. 

But the xml that is passed to the IsSignedByAny method in the XmlHelpers class, is just the assertion without the signature, and that fails for obvious reasons.

Is there a setting I might have forgotten that can cause this?

**Comment by AndersAbel** [comment]
First the Response signature is checked. If no signature is detected on the response all assertions are checked. Can you see when debugging if it detects the signature on the Response?

**Comment by janobrestad** [comment]
Where should I put a breakpoint to check this?

**Comment by janobrestad** [comment]
I found out a bit more. 
The structure of the data I receive is like this: 

<ArtifactResponse>
<Signature>
</Signature>
<Status>
</Status>
<Response>
</Response>
</ArtifactResponse>

And it is only the Response element that is passed to the Saml2Response class.

It seems the IDP is using HTTP Artifact Binding, is that supported?

**Comment by janobrestad** [comment]
Found out more details about this and opened a new issue #539 describing the problem in a better way.
