### ISSUE TITLE
Transient SSO Authentication Failure (Shibboleth)

### ISSUE THREAD

**Issue by jbenzshawel** [KentorIT/authservices#526]
I am working on a Shibboleth implementation that is not working consistently. Sometimes the following exception occurs before the ExternalLoginCallback: 

  Type: System.Collections.Generic.KeyNotFoundException
  Message: The given key was not present in the dictionary.
  Source: Kentor.AuthServices
  Target Site: get_Item | Kentor.AuthServices.dll
  Class Name: IdentityProviderDictionary
  Method Name: get_Item
 Stack Trace 
 at Kentor.AuthServices.Configuration.IdentityProviderDictionary.get_Item(EntityId entityId)

Other times the same users can login without issue. I noticed when a login fails and this exception occurs there is a cookie called Kentor.[some encrypted stuff] set. When the login is successful the cookie is not present. 

Has anyone else ran into an issue like this?

**Comment by jbenzshawel** [comment]
The same 302 / 303 redirect from the issue below is occur as well: 
https://github.com/KentorIT/authservices/issues/226

When it works the redirect is a 303 and for failures it is a 302

**Comment by AndersAbel** [comment]
I assume that the `KeyNotFoundException` is thrown when hitting `~/AuthServices/ACS`. In that case it's because the idp entity id is unknown to AuthServices.

How do you configure the Idp? Are you loading metadata?

**Comment by jbenzshawel** [comment]
Yes I am loading metadata. The application is configured to use a few different SSO options so realm/metadata are stored in a db then loaded depending on SSO type. 

```C#
var english = CultureInfo.GetCultureInfo("en-us");
var organization = new Organization();
var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
{
    SPOptions = new SPOptions
    {
        EntityId = new EntityId(org.Realm),
        ReturnUrl = new Uri(org.Realm),
        Organization = organization,
    },
    AuthenticationType = org.AuthenticationType,
    Caption = org.Caption,
    SignInAsAuthenticationType = "ExternalCookie"
};

authServicesOptions.IdentityProviders.Add(new IdentityProvider(
new EntityId(org.IDPProvider), authServicesOptions.SPOptions)
{
    MetadataLocation = org.MetadataUrl,
    LoadMetadata = true,
    SingleLogoutServiceUrl = new Uri(org.Realm)
});
app.UseKentorAuthServicesAuthentication(authServicesOptions);
```

**Comment by jbenzshawel** [comment]
@AndersAbel 

We forked and put logging around the IdentityProviderDictioanry and were able to determine that the entityId is coming back different when we are getting failures. 

I think at this point we can say there is a configuration issue with the relying party we are working with and this issue can be closed.
