### ISSUE TITLE
Kentor AuthService HTTPModule- ADFS Login Exception

### ISSUE THREAD

**Issue by rajsekharr83** [KentorIT/authservices#527]
In our ASP.Net project, I am using 'Kentor.AuthServices.HTTPModule' and have configured ADFS.

Have given the SAML Assertion Consumer Binding as "redirect" and Trusted-URL as "ourSiteUrl". If the user is not signed in, it will automatically redirect to ADFS login page. When login is successfull, it will redirect to "ourSiteURL/AuthServices/Acs?SAMLResponse=..." and it throws an Exception in the page :**"Kentor.AuthServices.Exceptions.InvalidSignatureException: Cannot verify signature of message from unknown sender win-3obaenpbsol.dc10.inapp.com/adfs/services/trust."**

Please help...

**Comment by albinsunnanbo** [comment]
If you check the source: https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/WebSSO/Saml2RedirectBinding.cs#L130
you can see that the win-3obaenpbsol.dc10.inapp.com/adfs/services/trust is not a loaded IDP. Have you loaded your IDP from configuration or metadata?
Can you check your configuration that the entityId of the IDP is the same as above. The entityId may not be the same as the metadata url. But they often match, including http[s]:// first in the entityId.

**Comment by rajsekharr83** [comment]
Hi, 
Many Thanks.

Could you please check our below given  web config and suggest what changes we need to make? 

**<modules>
      <add name="SessionAuthenticationModule" type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" preCondition="managedHandler" />
      <add name="Saml2AuthenticationModule" type="Kentor.AuthServices.HttpModule.Saml2AuthenticationModule, Kentor.AuthServices.HttpModule" />
    </modules>

  </system.webServer>
  <kentor.authServices entityId="https://app1.dc10.inapp.com/AuthServices/metadata/" returnUrl="https://app1.dc10.inapp.com/"  discoveryServiceUrl="http://localhost:52071/DiscoveryService">
    <identityProviders>
      <add entityId="https://ADFS.dc10.inapp.com" signOnUrl="https://ADFS.dc10.inapp.com/adfs/ls/" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate fileName="~/App_Data/Kentor.AuthServices.StubIdp.cer" />
      </add>
    </identityProviders>
    <federations>
      <add metadataLocation="http://localhost:52071/Federation" allowUnsolicitedAuthnResponse="true" />
    </federations>
    
  </kentor.authServices>

  <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" name="SampleMvcApplicationAuth" />
    </federationConfiguration>
  </system.identityModel.services>**

Thanks

**Comment by albinsunnanbo** [comment]
It looks like you have copied way to much from the sample applications

1) Remove the "federations" tag if you are not sure that you actually need it. It looks like you just have the localhost configuration from the sample projects.

2) Use `win-3obaenpbsol.dc10.inapp.com/adfs/services/trust` as entityId in `add entityId="`

3) remove discoveryServiceUrl

4) Change `entityId="https://ADFS.dc10.inapp.com"` to `win-3obaenpbsol.dc10.inapp.com/adfs/services/trust`

5) Consider not using StubIdp.cer for signing certificate.

If the ADFS exposes SAML2 metadata you should consider using that for configuration instead of wiring everything up yourself.

**Comment by rajsekharr83** [comment]
Thank You ! It worked.

We are working on the Log Out functionality. Do we need to manually redirect to ADFS login page or does the Kentor Saml2AuthenticationModule do all the work?

**Comment by AndersAbel** [comment]
AuthServices handles SAML2P logout, but you need to configure a ServiceCertificate to enable it.

**Comment by AndersAbel** [comment]
Closing due to long time since last comment. Please leave a new comment to reopen.
