### ISSUE TITLE
LogOut from the application using Kentor

### ISSUE THREAD

**Issue by rajsekharr83** [KentorIT/authservices#530]
In our ASP.Net project, I am using 'Kentor.AuthServices.HTTPModule' and have configured ADFS. We need to implement the logout functionality. we found the code "~/AuthServices/Logout?ReturnUrl=" + Uri.EscapeDataString(Page.ResolveUrl("~/?Status=LoggedOut")) from the samples. But when we implement in our code it does not work as expected. (we believe the session cookies are not clearing).

On logout we need to redirect to ADFS login page. We configured the SAML logout endpoints in ADFS and there is no encryption certificate installed. What could be the reason for this issue?

Please find the ADFS Bindings image provided below. Thanks

![ken1](https://cloud.githubusercontent.com/assets/20515697/16974812/f2a5638e-4e5d-11e6-8597-79665bd3a4a8.png)

**Comment by AndersAbel** [comment]
This is not the right place to get support for ADFS config.

**Comment by rajsekharr83** [comment]
Sorry for the confusion. We were mentioning about the Kentor Logout. Once we logout, it is redirecting to ADFS signout page because in config we have mentioned the ADFS logout URL as provided:

 **<identityProviders>
      <add wantAuthnRequestsSigned="true" entityId="http:/ADFS DOMAIN/adfs/services/trust" logoutUrl="https://ADFS DOMAIN/adfs/ls/?wa=wsignout1.0" signOnUrl="https://ADFS DOMAIN/adfs/ls/" allowUnsolicitedAuthnResponse="true" binding="HttpPost">

        <signingCertificate fileName="~/App_Data/Sign.cer" />
      </add>
    </identityProviders>**


But when we open the application in next tab in the same browser, it is not asking for the ADFS login page. Instead it is automatically entering into the application. The correct behavior should be once we sign out, it should ask for the ADFS login credentials.

Also is there any way to redirect to ADFS login page once we click the Signout?

**Comment by AndersAbel** [comment]
Looks like this is something that need to be debugged, which goes beyond the scope of what we can offer for free here on the issue tracker. I'd be happy to help out with this as a consultancy service. If that's interesting, please mail me at anders.abel@kentor.se.

**Comment by rajsekharr83** [comment]
Thank you Anders!
 We will mail you this issue.

**Comment by saqibmushtaq** [comment]
Hi Rajesh, was this every resolved. I am also getting exactly the same behaviour as you described above. Any suggestion? Thanks.
