### ISSUE TITLE
signingCertificate fails for cert without private key

### ISSUE THREAD

**Issue by tonesnotes** [KentorIT/authservices#537]
I'm trying to load an idP provided certificate using xml like this in web.config:

        <signingCertificate storeName = "AddressBook" storeLocation="LocalMachine" x509FindType="FindByThumbprint" findValue="‎eb 6a 96 fb 08 3d fb 2e 5e ab 56 dc 3e a2 df 86 82 c7 c8 39" />

Which works for the usual Kentor cert (which includes a private key, thumbprint="d3 41 8d bf fd 46 e0 e4 b8 a9 bb 2f 43 c4 ac d4 7a ef be 52"), but not for the client's cert (which does not include a private key).

The error is the usual: Finding cert through FindByThumbprint in LocalMachine:AddressBook with value ‎eb 6a 96 fb 08 3d fb 2e 5e ab 56 dc 3e a2 df 86 82 c7 c8 39 matched 0 certificates. A unique match is required.

Is this supported? Are there other differences between certs that explain why one works and the other doesn't?

**Comment by explunit** [comment]
You only need the public key from the Idp, so the lack of private key should not be the issue. Some other things to check:
 1. Invisible unicode character in your thumbprint https://support.microsoft.com/en-us/kb/2023835
 1. That the store name is correct for the location where you imported the cert

**Comment by tonesnotes** [comment]
I have both certs (the kentor cert and the client cert) imported to the same store LocalMachine / AddressBook (which Windows calls Local Machine / Other People).

Retyped the thumbprint by hand (and used Notepad++ to check for invisible characters).

It works when I use the Kentor cert's thumbprint for findValue and fails when I use the client cert's thumbprint.

Any debugging suggestions?

**Comment by tonesnotes** [comment]
Thanks for the reply btw :-)

**Comment by explunit** [comment]
Sorry can't think of much else. Just for sanity check you might try loading from file or loading with a different findType e.g. FindBySubjectDistinguishedName. It looks like the code that loads it is using standard X509Certificate2Collection code:
https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/Configuration/CertificateElement.cs#L106

**Comment by tonesnotes** [comment]
Loading from file works with the client's cert (but runs into issues with needing to enable Load User Profile) within the IIS App Pool which causes problems across load balanced servers.

Thanks for the code pointer. I'll try a test program to just load the cert from the store.

**Comment by tonesnotes** [comment]
The issue was in fact the INVISIBLE character copied out of the cert details.

Notepad++ (version Jan 10 2015 - 17:20:21) DOES NOT display it as a question mark (which is why if moved on to other possibilities). Using the cursor and arrow keys did however confirm an extra character at the start of the string.

Got back to this when debugging the configuration load code showed a string length of 41 instead of 40.

Latest version of Notepad++ (6.9.2, May 18 2016) also does not show a question mark character by default. Even with "Show All Characters" checked it remains invisible. Possibly a zero width space character.

**Comment by spanout** [comment]
HI Anders 

I have tried many approaches on this and please forgive me if this is a simple question. I have an x509 cert from the IDP, I am the SP and they want my auth requests signed. I am pointing to their x509 cert using the storename and find by thumbprint, but i get the error as the guy above gets:  _Provided certificate is not valid because it does not contain a private key._

Do I have to create my own signing certificate to sign the request or should I use the IDP public key? I am sorry if this is an amateur question

**Comment by explunit** [comment]
You have to create/obtain your own certificate to sign the requests that you send. The IDP public key is just for validating responses that you receive.

**Comment by spanout** [comment]
thanks... that's what I was thinking but just needed confirmation.

**Comment by spanout** [comment]
I have no idea what I am doing wrong.. I created a signing cert using powershell and get the same message when I try to access it either by FindByThumbprint or FindBySubjectDistinguishedName. The cert is in localMachine\Other People on my workstation . My webconfig is:

<signingCertificate  storeName="AddressBook" storeLocation="LocalMachine" findValue="RequestSigning" x509FindType="FindBySubjectDistinguishedName" />
I can export the cert with or without the privatekey, so there is one in there. Is there any other diagnostic that I can do?

Thanks in advance for any assistance :)

**Comment by albinsunnanbo** [comment]
Right click on cert in management console. Choose "All Tasks" -> "Manage private keys"
Make sure permissions allow your application pool account to use the private key.

**Comment by albinsunnanbo** [comment]
Also make sure you don't have found the nasty bug that if you copy the thumb print from certificate properties includes window it includes an invisible character as the first character.
Click before the first character after `findValue="‎` and go left and right with the keyboard arrows and make sure the insertion point moves one character for every arrow press you make.

**Comment by spanout** [comment]
Thanks again for your response, but this still does not fix it. Moving my cursor with the arrow key definitely now moves one character at a time as expected, but I still get the error:

> [ArgumentException: Provided certificate is not valid because it does not contain a private key.]
>    Kentor.AuthServices.Configuration.ServiceCertificateCollection.InsertItem(Int32 index, ServiceCertificate item) +160
>    System.Collections.ObjectModel.Collection`1.Add(T item) +98
>    Kentor.AuthServices.Configuration.ServiceCertificateElementCollection.RegisterServiceCertificates(SPOptions options) +133
>    Kentor.AuthServices.Configuration.SPOptions..ctor(KentorAuthServicesSection configSection) +695
>    Kentor.AuthServices.Configuration.Options.LoadOptionsFromConfiguration() +32
>    Kentor.AuthServices.Configuration.<>c.<.cctor>b__17_0() +5
>    System.Lazy`1.CreateValue() +417
>    System.Lazy`1.LazyInitValue() +152
>    System.Lazy`1.get_Value() +75
>    Kentor.AuthServices.Configuration.Options.get_FromConfiguration() +27
>    Kentor.AuthServices.HttpModule.Saml2AuthenticationModule..cctor() +8
> 
> [TypeInitializationException: The type initializer for 'Kentor.AuthServices.HttpModule.Saml2AuthenticationModule' threw an exception.]
>    Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.get_Options() +14
>    Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e) +147
>    System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

**Comment by AndersAbel** [comment]
Make a small test program (or use linqpad) to read out the X509Ceritificate2. That's usually a better debugging experience than trying to work through AuthServices.
