### ISSUE TITLE
Register Identity Provider after App Startup

### ISSUE THREAD

**Issue by nfang001** [KentorIT/authservices#540]
Hi,

I am currently using the Owin middleware to implement SAML SSO for our application.
I am saving identity provider configurations to our database and these configurations will be used to register the IdPs and to select IdP for a specified entity. In `Startup.Auth.cs`, I registered all known IdPs using the configurations to `SPOptions` and in `SelectIdentityProvider` notification, I am constructing and returning an IdP using specified configuration. 

If a new client wants to set up SSO, can I register the client's IdP pragmatically so it can be validated when our application receives response from the IdP?

Thanks!

**Comment by AndersAbel** [comment]
You should keep a reference to the IOptions instance around (which is KentorAuthServicesAuthenticationOptions when using owin). Then you can add Idps dynamically to the configuration and they will be used directly.

I'd also recommend to not create a new `IdentityProvider` object in `SelectIdentityProvider` but rather return one from the existing IdentityProvider collection.

**Comment by nfang001** [comment]
Thanks @AndersAbel !

**Comment by AndersAbel** [comment]
Looks like problem is solved, please leave a new comment to reopen.

**Comment by rossiter10** [comment]
> You should keep a reference to the IOptions instance around

So....how would one do this? I would like to add/remove IdPs in a controller action later on.

**Comment by AndersAbel** [comment]
@rossiter10 No, there is no Owin best practice as the Owin context is instantiated per request. In most cases you can just put it in a static property somewhere. If you have multiple instances of the owin middleware you need something more specific, but that's a quite rare case.

**Comment by rossiter10** [comment]
@AndersAbel Thanks for the response! I think I have this working, but wanted to clarify something(and maybe it helps others). It wasn't working when I tried to just simply find the existing IdentityProvider and modify the EntityId and MetadataLocation. I think I was getting "unknown idp" errors.  What did work though was creating a new IdentityProvider instance and replacing the existing one, does that sound right? Is there some kind of "re-initialize" function I might be missing?

**Comment by AndersAbel** [comment]
@rossiter10 Changing the entity id of an existing IdentityProvider object would confuse things, as the EntityID that is used as the key to the dictionary wouldn't get updated. I never thought of the option that someone would do that.... Is it a bug that it is possible to do that?

**Comment by rossiter10** [comment]
Well, here's the use case I'm experimenting with, which probably is pretty uncommon. We want to add/remove providers on the fly, so we have a form where we can manage SAML providers, which includes the entity id and metadata location. So maybe someone enters or pastes the wrong value for entity id and needs to update it. So my first quick attempt was just simple upsert logic where I update the EntityId.Id property. 

I guess if anything, maybe a private set or something on EntityId.Id?

**Comment by AndersAbel** [comment]
A private set of the EntityId on the IdentityProvider would make initialization harder. What might work is an internal freeze flag that sets the EntityId to non mutable once it's been added to the IdentityProviders colleciton.
