### ISSUE TITLE
Issue with Okta X.509 certificate

### ISSUE THREAD

**Issue by rajeevas** [KentorIT/authservices#544]
I have some issue when integrating Okta Idp, When I try to run with okta.cert X.509 certificate this gives me an error saying "Provided certificate is not valid because it does not contain a private key". Can someone please help me to fix this issue.

**Comment by explunit** [comment]
You might be confused about which certificate you are configuring.

For the Idp (e.g. Okta) certficates you do not need the private key. For Service Certificates, these certificates would typically be created by you or your IT department, not something that would come from Okta.

If this does not clear up the issue for you, please reopen this issue by providing the snippet of configuration/code you are asking about.
