### ISSUE TITLE
How to implement a Proxy SP for multiple SPs

### ISSUE THREAD

**Issue by jaideepvr** [KentorIT/authservices#554]
Hi,
I am new to SAML and SSO. We have a few web sites developed in C# which we would like to bring into SSO for authentication. I was able to successfully integrate Kentor with one of my sample application. But what we are trying to implement is some kind of a proxy web site that will site between the actual web sites(SP) and the ID Provider(IdP).
Our thought process for achieving this is:
1) Develop a web site that wraps the Kentor AuthServices library and implements MVC APIs for SignIn and Acs commands
2) In the actual SP for authentication, redirect the user to the Proxy site's SignIn url which again redirects to the IdP for authentication
3) Post IdP authentication, the Proxy site receives the SAML response and re-directs to the actual SP.

My question is:
1) Is this possible?
2) I did try implement the above mentioned process, I was able to get all the way till the response comes to the SP. But the SP does not get the authentication and it goes and redirects to the proxy for authentication and goes into an infinity loop.

Any help is appreciated.

Thanks
Jaideep

**Comment by explunit** [comment]
I apologize for not responding more quickly. I am not sure I fully understand the question, but it seems like you are describing something similar to what Identity Server handles. There is a sample project in the repo for integrating with Identity Server 3 (https://github.com/IdentityServer/IdentityServer3)
