### ISSUE TITLE
Single Identity Provider with Federation Metadata

### ISSUE THREAD

**Issue by MichaelHausherr** [KentorIT/authservices#568]
I'm trying to configure Kentor.AuthServices in web.config for a scenario with a single Identity Provider, but would like that the details regarding SignOnUrl, Certificate, Binding, etc. are taken from the Federation metadata. Is this scenario supported? Issue #164 seems to suggest it is ...

From the documentation it seems that the <identityProviders> section is optional, but specifing only the federation metadata location in the <federations> section leads to a redirect to the first Identity Provider listed in the federation metadata. This could most likely be avoided through the use of a discovery service, but as only one IdP is relevant in this case, we don't want the users having to go through this step.

If I specify the IdP explicitly in the <identityProviders> section with loadMetadata=true, Kentor.AuthServices seems to always load the metadata from the IdP directly (entityID Url) or from the configured metadataLocation. But this is not considered best practice in our federation. If loadMetadata is set to false, Kentor.AuthServices seems to expect that all details regarding the IdP are specified directly in the web.config.

Any help is very much appreciated. Thanks in advance.

**Comment by AndersAbel** [comment]
There's a notification you can hook and implement called `SelectIdentityProvider`. The default implementation (as you've found out) is to use the first idp listed.

Another option is to add the entityid of the idp to the authenticationProperties, if you can control those (i.e. unless the login is initiated by some external code like IdSrv3).
