### ISSUE TITLE
Get User ID

### ISSUE THREAD

**Issue by tforde1974** [KentorIT/authservices#571]
Hi,

I am trying to pull the user ID from the claim so I can log it when they log in.  But for the life of me I cannot see where I get it from.  Looking at your sample I can loop through the System.Security.Claims.ClaimsPrinciple.Current.Claims to grab it.  But in my implementation of SAML the value node is empty.  Is there another method that I may not be seeing for me retrieve it.

**Comment by dilyandimitrov** [comment]
Hi,

I also use Kentor library for SSO (ASP.NET Core 1.0) so I get the Claims from the external provider in the `ExternalLoginCallback` MVC action, which is the address where the Identity Provider will make a GET after successful authentication.
So I use
`var info = await SignInManager.GetExternalLoginInfoAsync();`
to get the external login info. In the `info` variable you have `info.Principal.Claims`

Hope this helps.

**Comment by tforde1974** [comment]
I am not using Owin, so I don't have access to the SignInManager.  I did try to include owin through nuget and then add it to my solution.  But the signinmanager requires a type "Signinmanager<>" so I don't think that is what I am looking for.  There has to be a simpler method to get the user identity from Kentor AuthServices.

**Comment by tforde1974** [comment]
If call the System.Security.Claims.ClaimsPrincipal.Current.Identity.GetUserID() it returns a value that looks like this _904e77d431fe0d859b11b1b2cefbc2bb0a2f.  Is there a way to decode that value?

**Comment by Thaoden** [comment]
If your user is authenticated, you should have him in the `Controller.User` property. From there, you can access the SAML claims of your user like this:

    ((ClaimsIdentity)User.Identity).Claims.Single(c => c.Type.Equals("urn:oid:0.9.2342.19200300.100.1.1"))

which should give the uid of your logged in user.
