### ISSUE TITLE
CS0433: Conflict between mscorlib.dll & Antlr3.Runtime.dll

### ISSUE THREAD

**Issue by Rajati** [KentorIT/authservices#572]
Hi Guys,

I am using Kentor.AuthServices.HttpModule and using the sample web.config with addition for my application. When I load the website, I receive the below error:

**CS0433: The type 'System.Runtime.Serialization.SerializationInfo' exists in both 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll' and 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\application\949e9d7e\b191f7bf\assembly\dl3\d2d30dad\003578ee_723fce01\Antlr3.Runtime.DLL'

Source Error:

Line 47:                 /// </remarks>
Line 48:                 void System.Runtime.Serialization.ISerializable.GetObjectData(
Line 49:                                 System.Runtime.Serialization.SerializationInfo info, 
Line 50:                                 System.Runtime.Serialization.StreamingContext context)
Line 51:                 {

Source File: e:\directore1\directory2\abcd.cs    Line: 49**

If I comment out "Using System" from the .cs file giving error then application fails with missing reference.

I have done iisrest, cleared the "c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files" and tried again, did a "Clean" then "Build" but still receive the above error.

Any help will be appreciated.

It is on Windows 2008 R2 Enterprise, SQL 2008 R2 Enterprise, WIF is installed on the Server for WS-Fed also. Let me know if you need more information.

**Comment by explunit** [comment]
This seems unrelated to AuthServices since the AuthServices.HttpModule package does not reference Antlr. Please comment/reopen if I'm wrong about this.
