### ISSUE TITLE
MVC - 404 accessing AuthServices

### ISSUE THREAD

**Issue by cngrindstaff** [KentorIT/authservices#576]
I have a problem similar to what is described here: https://github.com/KentorIT/authservices/issues/268

I'm trying to integrate Kentor.AuthServices.Mvc into my MVC application. When downloading Kentor.AuthServices.Mvc from Nuget, it also automatically installs Kentor.AuthServices and Kentor.AuthServices.HttpModule. 

I installed the nuget packages, and set up my web.config the same as the Mvc Sample Application, but my program 404s when trying to find AuthServices/SignIn. 

As the user did in Issue 268, I also added the Saml2AuthenticationModule module to my web.config, going against your instructions in your documentation (https://github.com/KentorIT/authservices/blob/master/doc/Configuration.md)

When I do that, the program no longer 404s, but it sends me to a Kentor.AuthServices.StubIdp Discovery Service. Of course, that doesn't help me either, because I need the program to go to a sign in page so that my users can actually use the service. 

How can I make my program properly work with Kentor.AuthServices.Mvc?

**Comment by rharting** [comment]
cngrindstaff, I am having similar issue. Did you get yours resolved? I am not using MVC, but trying to get the included SampleApplication to work with our identity provider. It seems to be close to working on my development server, which I am using IIS Express (Visual Studio 2015 debug). But when published to our DMZ server using IIS 7, I receive the 404 error when I click SignIn. I am assuming something is not setup right in IIS or web.config but cannot figure out what. Thanks

**Comment by AndersAbel** [comment]
@rharting Might be a RAMFAR issue (RAMFAR = RunAllManagedModulesOnAllRequests setting, which probably need to be set to true to get IIS to fire the HttpModule that handles the request)
