### ISSUE TITLE
Kentor:[KeyNotFoundException: No Idp with entity id “http://adfs.domain.com/adfs/services/trust” found.]

### ISSUE THREAD

**Issue by sajithtgs** [KentorIT/authservices#583]
Hi,

We have a requirement to enable SAML SSO login, we are implementing SSO using Kentor HttpModule. I'm facing an issue when the Idp calls my application. The kentor service throws The given key was not present in the dictionary. Here the idp is ADFS.

We tried using the stubidp and it works fine.

Below is my Saml configuration 

` 
    private static IdentityProvider CreateAuthServicesOptions()
    {
        var spOptions = GetServiceProviderOptions();

        var idp = new IdentityProvider(new EntityId("http://Test.domain.com/adfs/services/trust/"), spOptions)
        {
            AllowUnsolicitedAuthnResponse = true,
            Binding = Saml2BindingType.HttpPost,
            WantAuthnRequestsSigned=true,
            //LoadMetadata = true,
            SingleSignOnServiceUrl = new Uri("https://Test.iqtrackdev.com/adfs/ls/")
        };

        idp.SigningKeys.AddConfiguredKey(
                new X509Certificate2(AppDomain.CurrentDomain.SetupInformation.ApplicationBase + "/ADFSService.cer"));

        return idp;
    }

    private static SPOptions GetServiceProviderOptions()
    {
        var cultureInfo = CultureInfo.GetCultureInfo("en-US");

        var spOptions = new SPOptions
        {
            EntityId = new EntityId("https://app.domain.com/AuthServices/"),
            ReturnUrl = new Uri("https://app.domain.com"),

            AuthenticateRequestSigningBehavior=SigningBehavior.Always

        };
        X509Store store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
        store.Open(OpenFlags.ReadOnly | OpenFlags.OpenExistingOnly);
        X509Certificate2Collection cers = store.Certificates.Find(X509FindType.FindByThumbprint, "‎FDDAF5EAA6E2B232E0012C0E77955C13246D2DF4", false);

        Kentor.AuthServices.ServiceCertificate ser = new Kentor.AuthServices.ServiceCertificate();
        ser.Certificate = cers[0];
        ser.Use = Kentor.AuthServices.CertificateUse.Signing;
        spOptions.ServiceCertificates.Add(ser);

        //spOptions.ServiceCertificates.Add(new X509Certificate2(
        //        AppDomain.CurrentDomain.SetupInformation.ApplicationBase + "/ADFSService.cer"));

        return spOptions;
    }

    protected void OnAuthenticateRequest(object sender, EventArgs e)
    {
        var application = (HttpApplication)sender;

        // Strip the leading ~ from the AppRelative path.
        var appRelativePath = application.Request.AppRelativeCurrentExecutionFilePath;
        appRelativePath = (!string.IsNullOrEmpty(appRelativePath))
            ? appRelativePath.Substring(1)
            : string.Empty;          

        if (application.Request != null)
      {

            Kentor.AuthServices.Configuration.Options op = new Options(GetServiceProviderOptions());

            op.IdentityProviders.Add(CreateAuthServicesOptions());
            Options = op;
        }

        var modulePath = Options.SPOptions.ModulePath;

        if (appRelativePath.StartsWith(modulePath, StringComparison.OrdinalIgnoreCase))
        {
            var commandName = appRelativePath.Substring(modulePath.Length);

            var command = CommandFactory.GetCommand(commandName);
            var commandResult = command.Run(
                new HttpRequestWrapper(application.Request).ToHttpRequestData(),
                Options);

            if (!commandResult.HandledResult)
            {
                commandResult.SignInOrOutSessionAuthenticationModule();
                commandResult.Apply(new HttpResponseWrapper(application.Response));
            }
        }
    }`

**Comment by explunit** [comment]
Note that the entity ID lookup is case-sensitive. Could that be the problem in this case?

**Comment by sajithtgs** [comment]
Thanks for the reply.
My Entity id was correct, Am not sure why it is not returning the SigningKeys when the correct key is supplied. So i modified the code and returned the SigningKeys using index.

      private void ValidateSignature(IOptions options)
        {
            //var idpKeys = options.IdentityProviders[Issuer].SigningKeys;

             var idpKeys = options.IdentityProviders[0].SigningKeys; //Modified code

            if (!xmlElement.IsSignedByAny(idpKeys, options.SPOptions.ValidateCertificates)
                && GetAllAssertionElementNodes(options)
                .Any(a => !a.IsSignedByAny(idpKeys, options.SPOptions.ValidateCertificates)))
            {
                throw new Saml2ResponseFailedValidationException("The SAML Response is not signed and contains unsigned Assertions. Response cannot be trusted.");
            }
        }

**Comment by explunit** [comment]
I'm glad that you have found a solution, but just wanted to say "for the record" that the above code does not seem like the right approach. `options.IdentityProviders[somevalue]` is a fairly simple dictionary lookup, case-sensitive as I mentioned earlier. 

Closing for now, but if you believe that the lookup is not working correctly can you provide a unit test or a sample project where it fails?
