### ISSUE TITLE
Encrypted Assertions encountered but Service Certificate was not provided.

### ISSUE THREAD

**Issue by sajithtgs** [KentorIT/authservices#585]
Hi,
Iam Implementing SSO using Kentor HTTP module and my IDP is ADFS. I have given encryption certificate for relying party in ADFS , after returning from idp to application throws an error . Could you help me to resolve the issue.
The code :
`   Kentor.AuthServices.ServiceCertificate ser = new Kentor.AuthServices.ServiceCertificate();
            ser.Certificate = store.Certificates[0];
            ser.Use = Kentor.AuthServices.CertificateUse.Encryption;
`

**Comment by explunit** [comment]
Do you add this configured ServiceCertificate variable to your myOptions.SPOptions.ServiceCertificates?

**Comment by sajithtgs** [comment]
We tried the above code also, i throws
Provided certificate is not valid for encryption/decryption. If you only want to use it for signing, set the Use property to Signing (CertificateUse.Signing).

**Comment by explunit** [comment]
Two possibilities come to mind:
 1. If you're loading this from windows certificate store, perhaps the application pool user does not have access to the private key of the certificate? The error message is misleading in that case.
 1. The certificate doesn't have the correct usage flags to be able to use for encryption

**Comment by explunit** [comment]
For more on the second possibility, see #412

**Comment by explunit** [comment]
Logged #589 regarding the misleading error message. If your issue was not one of these two mentioned above, please comment/reopen.

**Comment by msekkappan** [comment]
This message pops up for "Encrypted Assertions encountered but Service Certificate was not provided." as well
