### ISSUE TITLE
Single Sign Out in Kentor

### ISSUE THREAD

**Issue by sajithtgs** [KentorIT/authservices#586]
Hi,

  For sign out i use to call "https://Test/adfs/ls/?wa=wsignout1.0" in my application and it logs out.
How is that different from Single Sign Out .

**Comment by explunit** [comment]
At least two things:
 1. If you give a signed logout request to ADFS then it can use it to potentially sign out *other* applications that were part of that same session
 1. The signout can be initiated from within ADFS (potentially from one of those other applications mentioned above), telling your application to log out a particular user

In both cases the requests are signed so you know it's not mischief from some other site making your users log out when they didn't intend to.
