### ISSUE TITLE
Why are the claims retrieved encrypted?

### ISSUE THREAD

**Issue by Louhike** [KentorIT/authservices#597]
I use authservices in a MVC project. I can authenticate with the IDP, but the claims which are retrieved seem to be encrypted (example: AAdzZWNyZXQxwsOYwAdOOSoZVXq84etTP+Z+VXWyulWJv+rUfb3fqGokDBH4Ddh0oTZE1Gl1QMo+B1q+QC0PLFhz/EEhQMkgh7qKypm3KG5CaNSoLVpiq+8vSBSWjh1TrTR0TbX+aBZMFJ4LyqfrIBNKfGvq3FLKiQ==).

I thought they would be decrypted automatically. I tried to decrypt it manually but I have errors by doing so.

Am I missing/misunderstanding something? And do I have a problem with my configuration?

**Comment by albinsunnanbo** [comment]
Yes, they should.
Can you capture the SAML2 response with https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace and check if the `EncryptedAssertion` contains the exact "encrypted" value you get on the claims.

Could it be be that the values have another encryption "on top" of the saml2 encrypted assertions?

**Comment by albinsunnanbo** [comment]
You could also download the source and put a breakpoint at https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/SAML2P/Saml2Response.cs#L375 and have a look at what is happening.

**Comment by AndersAbel** [comment]
Are all claims "encrypted"? That one looks like a BASE64-encoded value, which might be a bearer token. The NameIdentifier claim is also an opaque value if you are using Persistent or Transient name identifier types.

**Comment by Louhike** [comment]
@AndersAbel, you are right, it was a misunderstanding on my part. I checked the SAML response with the Chrome extension and it seems to be fine.

Thanks for the responses.
