### ISSUE TITLE
Kentor authservice okta integration in ASP.Net MVC

### ISSUE THREAD

**Issue by seemadas123** [KentorIT/authservices#604]
I'm using kentor authservice package in order to implement SSO with Okta as an IDP. Have followed the same asp.net mvc application code which is available in github. My doubt here is are we suppose to get session token back from Idp once user is authenticated?

I do get these as identity claims. 
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant http://kentor.se/AuthServices/LogoutNameIdentifier http://kentor.se/AuthServices/SessionIndex

My understanding is we need to get session token back from Idp and store this in session. At application level we need to check this session value at every request. 
Please correct me if my understanding is incorrect.

Also how do we get additional user information as claim. For ex: Now I'm getting only email id in NameIdentifier claim. I need to get full profile details (firstname, lastname, address) as claim value. Can anyone guide me on how to do this.

**Comment by AndersAbel** [comment]
The AuthServices.Mvc package automatically calls the SessionAuthenticationModule to establish a session. Just check `HttpContext.Current.User` to get the identity on subsequent requests. Or use the `[Authorize]` attribute that will do the check for you.

AuthServices transforms all attributes in the incoming Assertion into Claims. If you need more, you need to configure your Idp to send that data.

**Comment by alenjose007** [comment]
I used [Authorize] attribute. But it is Infinite loop on login page and login url.

Could you please advice.

**Comment by AndersAbel** [comment]
What did you configure for `ReturUrl`?

**Comment by alenjose007** [comment]
We have set the returnUrl as the applications home page https://server ip/name/Home.
Note: We are using MVC4

**Comment by AndersAbel** [comment]
Do you have any web.config-based authorization settings? Sometimes those are set to deny non-logged-in access to /AuthServices/Acs which casues issues.

**Comment by alenjose007** [comment]
No. We did not give any config based authorization.
We have used [Authorize] attribute in home page itself. When we browse it is redirect loop. But we browse directly that home page we can get.

**Comment by AndersAbel** [comment]
Can you use the browser dev tools, or fiddler to see the entire redirect chain?

**Comment by alenjose007** [comment]
Yes, We are using.

We have noticed one thing. In the web config we are giving the return url as https://ip/CBMETE/Home

but in the redirected signing url it is like  CBMETE/AuthServices/SignIn?ReturnUrl=%2fCBMETE.

Is the only place to configure return url is SP's web.config?

![image](https://cloud.githubusercontent.com/assets/24954448/22785199/5c55c44a-eef9-11e6-93b6-eb41a33754f7.png)

**Comment by alenjose007** [comment]
![image](https://cloud.githubusercontent.com/assets/24954448/22785732/896e96f8-eefb-11e6-840b-824506cf9138.png)

**Comment by AndersAbel** [comment]
The ReturnUrl is normally automatically generated by the forms authentication system that generates the redirect to the login sequence if you are not authorized.

Try logging in by accessing https://10.58.33.146/CBMETE/AuthServices/SignIn?ReturnUrl=%2fCBMETE/Home, to check if it works.

**Comment by GerwinNL** [comment]
I had 'Loop' issues, when users where authenticated, but not authorised (ie, login in Okta was valid, just the role/claim needed was missing. You (c/sh)ould override the HandleUnauthorizedRequest. (see http://stackoverflow.com/questions/238437/why-does-authorizeattribute-redirect-to-the-login-page-for-authentication-and-au)

**Comment by AndersAbel** [comment]
Looks like this is solved, closing issue.
