### ISSUE TITLE
Request "authentication" programmatically

### ISSUE THREAD

**Issue by Wilsonmg** [KentorIT/authservices#605]
Is it possible to send an authentication request (authnrequest) to an external Idp provider, after been logged in?  I have a particular escenario with an external Idp who demands session expiration and single logout. The user session expires in 30 minutes, so they demand a new authentication request in order to keep the session open. The user won't need to enter credentials as long as he/she has an active session _(it's kind of silent authentication)_.
I'm using IdentityServer3 + Kentor authservices and I'm planning to send the new authentication requests  when refreshing my token (for instance, every 25minutes) but **I'm trying to discover how to trigger/handle the authentication request in kentor authservices**.
Best regards

**Comment by AndersAbel** [comment]
There is no built in support in AuthServices for this, but I think that just triggering another SignIn-flow would make it work.

**Comment by Wilsonmg** [comment]
The challenge to trigger another sign-in-flow is that IdentityServer respond immediatelly if the user is already authenticated so there is no chance to call the external Idp again. I handled this problem adding an owin middleware and it worked for the server side. Then the problem moved to the frontend, because the new signin-flow changes the session state in the client side, and the singlelogout mechaninsm (oidc-token-manager) is having problems with it. I'm not sure if there is a nicer solution in the server side, but I think it's mostly related to IdentityServer the the token manager.
Thank you.
