### ISSUE TITLE
How to dynamically add Identity Provider metadata in KentorAuthServicesAuthenticationOptions IdentityProvider Dictionary

### ISSUE THREAD

**Issue by svetlichniymax** [KentorIT/authservices#608]
Hi,
I have a problem using Kentor Authentication Services library with Identity Server. 
The problem is in update KentorAuthServicesAuthenticationOptions IdentityProvider Dictionary dynamically after IdentityServer started.
I have configuration of IdentityProviders in Startup class like this:
![image](https://cloud.githubusercontent.com/assets/11835334/21018566/00651672-bd76-11e6-9b3e-657b88d2eae0.png)

I want to add another IdentityProvider (for example "One Login provider 4") and grab this config without restarting IdentityServer or recycle pool.
Is it possible to notified IdentityServer or create a specific request to IdentityServer and handle this request to update KentorAuthServicesAuthenticationOptions IdentityProvider Dictionary?
Thanks.

**Comment by explunit** [comment]
I think this question might be about OWIN startup and IdentityServer3 in general. If they don't support dynamic load of these after startup then there's nothing AuthServices can do, right?

**Comment by svetlichniymax** [comment]
Yes, right, that's why I'm asking, maybe it's possibly to configure it on Owin or IdwntityServer layer, btw I'm using IdwntityServer 3.

**Comment by explunit** [comment]
I don't know how to do that and my suspicion is that it's not possible, but perhaps also ask on the IdentityServer3 issue board or their stackoverflow tag.

**Comment by AndersAbel** [comment]
AuthServices handles a dynamically added Idp. The problem is that the Katan/OWIN middleware model isn't built for multiple Idps. IdentityServer creates one button for each middleware loaded, not for each Idp. You might be able to work around it by using a discovery service as an intermediate step. But that requires some updates to the AuthServices library to properly handle state across the discovery service call.

**Comment by ash23** [comment]
We are not using Identity Server and we do not need each identity provider to be represented as a button on some common login page for all users. We are building an MVC 5 application using OWIN / ASP.Net Identity where each customer organisation using our application (acting as a SP) may setup one optional identity provider (at runtime) and hence we need to register this identity provider dynamically with AuthServices.  

As I understand it the KentorAuthServicesAuthenticationOptions instance provided to KentorAuthServicesAuthenticationMiddleware can only be configured only once during application startup, is this true?

Given that we do not need to use the built in feature where an button is rendered for each external login provider middleware but we DO need to support multiple identity providers is there any other way i can dynamically add/remove identity providers to/from AuthServices when using the middleware? (I would prefer to avoid having to implement some form of discovery service and update the AuthServices library proposed above).
