### ISSUE TITLE
Integration with MVC Controller (Question)

### ISSUE THREAD

**Issue by adibPlaybuzz** [KentorIT/authservices#615]
Hi,
I'm struggling with embed the MVC controller (i would like to implement sp).
I think that i didn't understand the flow. After a successful login, a cookie (named Kentor...) has been set.
I would like to get the email of the authenticated user and make a login (create our own cookie) - is there an hook that i can create (web.config)? or maybe should I read the kentor cookie on the response redirect, decode it and get the user mail?

**Comment by explunit** [comment]
Once it has returned from the Idp and validated the claims you should be able to access the claims using `System.Web.HttpContext.Current.User.Identity`, as shown in this sample:
https://github.com/KentorIT/authservices/blob/v0.19.0/SampleMvcApplication/Controllers/HomeController.cs#L20
