### ISSUE TITLE
@Html.AntiForgeryToken() Error

### ISSUE THREAD

**Issue by piermorosini** [KentorIT/authservices#624]
Hi
I have this error

A claim of type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier' or 'http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider' was not present on the provided ClaimsIdentity. To enable anti-forgery token support with claims-based authentication, please verify that the configured claims provider is providing both of these claims on the ClaimsIdentity instances it generates. If the configured claims provider instead uses a different claim type as a unique identifier, it can be configured by setting the static property AntiForgeryConfig.UniqueClaimTypeIdentifier.

Thanks
Pierluigi

**Comment by explunit** [comment]
This is unrelated to AuthServices, but you can set the property `AntiForgeryConfig.UniqueClaimTypeIdentifier` to whatever claim uniquely identifies the user in the values you are getting back from your IDP. E.g. if there was a claim type called "UserId" you would do `AntiForgeryConfig.UniqueClaimTypeIdentifier = "UserId";` during the startup phase of your application.

**Comment by piermorosini** [comment]
Thanks
