### ISSUE TITLE
nothing happens after login being redirect to AuthServices/Acs 

### ISSUE THREAD

**Issue by alenjose007** [KentorIT/authservices#628]
I am using webseal, and using kentor in our SP side. I hosted my application in https://10../ABC/ and from the webseal it is redirect to to the Assertion Consumer Url https://10../ABC/AuthServices/Acs

It shows error in our browser

The website cannot display the page...................

![image](https://cloud.githubusercontent.com/assets/24954448/21805149/45a6d1f6-d73b-11e6-8d7f-72f41f919331.png)

Could you please anyone help on this?

**Comment by explunit** [comment]
Closing for now, but please reopen with more information (e.g. stack trace) if this is still a problem.
