### ISSUE TITLE
Attributes mapping

### ISSUE THREAD

**Issue by piermorosini** [KentorIT/authservices#630]
Hi,
from attributes in my response, the only mapped in kentor Claim is emailaddress.
How to add others?

Thanks for help
Pierluigi

<saml:AttributeStatement xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" 
	  
      <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn" 

      <saml:Attribute Name="http://schemas.auth0.com/identities/default/user_id" 
	  
      <saml:Attribute Name="http://schemas.auth0.com/identities/default/provider" 
	  
      <saml:Attribute Name="http://schemas.auth0.com/identities/default/connection" 
	  
      <saml:Attribute Name="http://schemas.auth0.com/identities/default/isSocial" 
	  
      <saml:Attribute Name="email_verified" 
	  
      <saml:Attribute Name="user_id" 
	  
      <saml:Attribute Name="clientID" 
	  
      <saml:Attribute Name="picture" 
	  
      <saml:Attribute Name="nickname" 
	  
      <saml:Attribute Name="identities" 
	  
      <saml:Attribute Name="updated_at" 
	  
      <saml:Attribute Name="created_at"

**Comment by AndersAbel** [comment]
Please check the XML, it looks very broken when you've pasted it.

**Comment by AndersAbel** [comment]
All attributes should be converted into Claims, did you check the Claims collection? Email might be exposed directly as a property (e.g. `.Name`) on the identity, but for the others you need to enumerate the claims.

**Comment by robertpmansion** [comment]
Question: in my claims, I'm getting the email of a user, but how do I populate the Email (see the below image) from the External LoginInfo from attributes in my response?

![screenshot 2017-03-17 02 22 24](https://cloud.githubusercontent.com/assets/18090549/24012466/05cbf8f2-0ab9-11e7-8524-50aea314e66b.png)

**Comment by AndersAbel** [comment]
@robertpmansion Please see #665 which is exactly the same problem (although phrased a bit differently)
