### ISSUE TITLE
Overriding metadata through configuration

### ISSUE THREAD

**Issue by eddietisma** [KentorIT/authservices#631]
We're facing some issues with SLO.

1) Currently there is no way of overriding the configuration when "LoadMetadata" is set to true. Even though explicitly set in code the configuration is lost upon metadata refresh.

2) When a metadata refresh is made outgoing Logout messages seems to default to POST binding. (Not sure about "#582: Prefer redirect binding for logout").

3) A SLO request using POST binding causes "#550: Server cannot append header after HTTP headers have been sent".

One solution would be to add a notification to update configuration upon metadata refresh. Another would be to re-apply the configuration after a reset (in this case especially "SingleLogoutServiceBinding"). What do you think?

**Comment by explunit** [comment]
Regarding #582, does this not solve your issue? Or you simply haven't used that version yet since it's not released on nuget?

In general I like the notification approach since it seems to provide maximum flexibility without greatly increasing the complexity of the core library.

**Comment by eddietisma** [comment]
This is not an issue anymore after the fix for #582 which came with [v0.20.0 release ](https://github.com/KentorIT/authservices/milestone/27?closed=1)
