### ISSUE TITLE
Insecure redirect via optional "returnUrl" param

### ISSUE THREAD

**Issue by doormalena** [KentorIT/authservices#633]
The optional "ReturnUrl" param for the SignIn command handler accepts any URL which in insecure. It can be misused for phishing or to spread malware. Desired is that only URL's within the scope of the application itself can be used, and optionally any other URL which is whitelisted in the web.config.

> /AuthServices/SignIn?ReturnUrl=http://www.google.com

**Comment by robinvanpoppel** [comment]
Related to #417

**Comment by doormalena** [comment]
Thanks robinvanpoppel. Didn't find that one.
