### ISSUE TITLE
Ecnrypted Assertion support

### ISSUE THREAD

**Issue by se** [KentorIT/authservices#640]
I need to send encrypted assertion to Facebook Workplace. But I think encrypted assertion is not supported? Or how can I implement this. Is there any way to do that?

I am always getting SP need encrypted assertion error.

**Comment by AndersAbel** [comment]
There's no support for generating encrypted assertions in the library. The crypto parts are present, so it should be possible to add if you either want to contribute it or if you want to sponsor that development.

**Comment by se** [comment]
I don't have that time right now :| But I used a simple fix. If there is Assertion in envelope I just encrypt it and my problem fixed.

**Comment by AndersAbel** [comment]
This is not a planned feature, focus of AuthServices is on the SP side, so closing the issue as won't fix.
