### ISSUE TITLE
identity.Claims empty in server (http), works on localhost (https)

### ISSUE THREAD

**Issue by YakkingYak** [KentorIT/authservices#641]
I am using Okta / Kentor. The solution works perfectly in localhost but does not work when I deploy to the server.

This is my returnUrl method code:
`
            var identity = System.Web.HttpContext.Current.User.Identity as ClaimsIdentity;
  
            var claimData = identity == null ? "Identity is null.\n" : "";
            if (identity != null)
            {
                foreach (var claim in identity.Claims)
                {
                    claimData += claim.Type + " = " + claim.Value + "\n";
                    if (claim.Type.EndsWith("nameidentifier", StringComparison.InvariantCultureIgnoreCase))
                    {
                        userName = claim.Value;
                        //break;
                    }
                }
            }
`

**HTTP:**
Claim Data: {BLANK}

**HTTPS:**
Claim Data:
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier = {USERNAME}
firstName = {FIRST NAME}
lastName = {LAST NAME}
email = {EMAIL}
... {etc}

**Comment by YakkingYak** [comment]
------------------------------
SOLUTION:
------------------------------

For HTTP:

You need the following in the web.config:

  <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" name="somename" />
    </federationConfiguration>
  </system.identityModel.services>

**Comment by AndersAbel** [comment]
Happy to hear you solved it. Looks like the default without the section in web.config is to have the session cookie marked as "secure" and with the section present (albeit empty) cookies are not secured and thus transferred over http.
