### ISSUE TITLE
Implement a Reverse Proxy for a single SP.

### ISSUE THREAD

**Issue by AdmiralRasmussen** [KentorIT/authservices#642]
For tiered security purposes, I'd like to create a Reverse Proxy on our perimeter server tier that brokers to a single Kentor.AuthServices secured SP on our middleware tier.

I currently have an instance of the Kentor.AuthServices secured SP (MVC) running on the perimeter server, but would like to move it to our middleware tier. The SP requires elevated privileges which is why we do not want it on the perimeter.

A transparent open proxy would not meet the need as that would allow all traffic to the middleware server. We only want SAML 2 requests (preferably only valid SAML 2) and cookie authenticated requests to reach the middleware server.

I'm considering creating a new Kentor.AuthServices secured SP on the perimeter, configuring it more-or-less identically to the middleware SP, and then relaying only valid SAML 2 requests to the middleware server. Any request bearing a valid auth cookie would also be relayed. 

Has anyone done this before?

**Comment by explunit** [comment]
I assume the SP requires elevated privileges for reasons other than Kentor.AuthServices? I'm not aware of any special permissions implied by the use of Kentor.AuthServices.

**Comment by AndersAbel** [comment]
If you want a separate proxy to handle SAML2, I would look into other solutions. Shibboleth (open source) and several commercial solutions for SAML2 work by creating a proxy in front of the application. The idea with AuthServices was to bring SAML2 to .NET **without** the need for a proxy.

**Comment by AdmiralRasmussen** [comment]
Thank you for your responses.

explunit - Correct, AuthServices does not require elevated privileges. My SP will have permissions to issue legacy system tokens, which is why I don't want it running on a perimeter server. 

AndersAbel - I don't actually wish to terminate SAML 2 at the proxy. I'm looking to create a dedicated proxy specifically for an AuthServices secured app to better protect it from internet hacking. ADFS 2.0 has a dedicated proxy called ADFS 2.0 Proxy [https://blogs.technet.microsoft.com/askds/2012/01/05/understanding-the-ad-fs-2-0-proxy/](url) (see "Why use an AD FS 2.0 Proxy" for the rationale behind it). A dedicated proxy tailored to AuthServices would be preferable to just fronting my middleware SP with a transparent open proxy and firewall (which would allow a lot of unauthenticated traffic through).

**Comment by AndersAbel** [comment]
No there is no such proxy for AuthServices. I don't really get the complete scope of what you are trying to accomplish. I'd be happy to look more in depth on this, if you are interested in consultancy services. Unfortunately I cannot answer complex questions here on the free issue tracker. If you're interested in our consultancy offerings, please mail me.
