### ISSUE TITLE
401 - Unauthorized: Access is denied due to invalid credentials.

### ISSUE THREAD

**Issue by robertpmansion** [KentorIT/authservices#647]
I'm getting an error whenever I click the SAML SSO button on our site.

![image](https://cloud.githubusercontent.com/assets/18090549/23263835/5cd2f3ee-fa1a-11e6-9f20-7114c9a209e8.png)

I implemented it with the following codes:

**Startup.Auth.cs**

        public void ConfigureAuth(IAppBuilder app)
        {
            app.CreatePerOwinContext<UserManager>(UserManager.Create);
            app.CreatePerOwinContext<RoleManager>(RoleManager.Create);

            UseOAuthAuthentication(app);
            UseCookieAuthentication(app);
            UseSaml2Authentication(app);
            UseSingleSignOnAuthentication(app);
        }

        private void UseSaml2Authentication(IAppBuilder app)
        {
            var culture = CultureInfo.GetCultureInfo("en-GB");

            var organisation = new Organization();
            organisation.Names.Add(new LocalizedName("Foo", culture));
            organisation.DisplayNames.Add(new LocalizedName("Foo Inc", culture));
            organisation.Urls.Add(new LocalizedUri(new Uri("https://www.foo.com"), culture));

            var support = new ContactPerson
            {
                Type = ContactType.Support
            };
            support.EmailAddresses.Add("support@foo.com");

            var spOptions = new SPOptions
            {
                ModulePath = "saml2p/metadata",
                AuthenticateRequestSigningBehavior = SigningBehavior.Never,
                EntityId = new EntityId("https://localhost:44300/saml2p/metadata"),
                ReturnUrl = new Uri("https://localhost:44300/account/AuthenticateCallback"),
                Organization = organisation
            };
            spOptions.Contacts.Add(support);

            var saml2AuthOptions = new KentorAuthServicesAuthenticationOptions(false)
            {
                AuthenticationType = "saml2",
                SPOptions = spOptions
            };

            var idpEntityId = new EntityId("http://localhost/simplesaml/saml2/idp/metadata.php");
            var idp = new IdentityProvider(idpEntityId, spOptions)
            {
                LoadMetadata = true,
            };

            idp.SigningKeys.AddConfiguredKey(new X509Certificate2(
                    HostingEnvironment.MapPath(
                        "~/App_Data/SimpleSAML.crt")));

            saml2AuthOptions.IdentityProviders.Add(idp);

            app.UseKentorAuthServicesAuthentication(saml2AuthOptions);
        }

**AccountController.cs**

        [AllowAnonymous]
        public ActionResult Authenticate(string provider, string returnUrl)
        {
            return new ChallengeResult(provider, Url.Action("AuthenticateCallback", "Account", new { provider, returnUrl }));
        }

        [AllowAnonymous]
        public async Task<ActionResult> AuthenticateCallback(string returnUrl)
        {
            var info = await AuthenticationManager.GetExternalLoginInfoAsync();
            if (info == null)
                return RedirectToAction("Login", new { returnUrl }).AndFlash(Strings.LoginFailed, FlashMessageType.Error);

           // omitted some codes

            var account = await UserManager.FindAsync(info.Login);
            if (account != null)
            {
                await SignInAsync(account, false);

                if (Url.IsLocalUrl(returnUrl))
                    return Redirect(returnUrl);

            }

            TempData["_ModelErrors"] = new[] { Strings.LoginFailed };
            return RedirectToAction("Login", new { returnUrl });
        }

    public class ChallengeResult : HttpUnauthorizedResult
    {
        public ChallengeResult(string provider, string redirectUrl)
        {
            LoginProvider = provider;
            RedirectUrl = redirectUrl;
        }

        public string LoginProvider { get; set; }

        public string RedirectUrl { get; set; }

        public override void ExecuteResult(ControllerContext context)
        {
            context.HttpContext.GetOwinContext().Authentication.Challenge(
                new AuthenticationProperties { RedirectUri = RedirectUrl }, LoginProvider.TitleCase());
        }
    }

I tried the above codes on this repository sample code for OWIN middleware and it works perfectly. I wonder what is going with it on our project as it's exactly the same configuration.

**Comment by AndersAbel** [comment]
If you set a breakpoint in the Authenticate action, is it ever hit? A common mistake in hybrid webforms/mvc applications is to have path-based authorization rules in web.config that blocks access, do you have that?

**Comment by robertpmansion** [comment]
We do not have the path-based authorization rules in web.config. 

When I set a breakpoint the Authenticate action it hits it, however, I notice that the return URL does not have any value which I think should probably have.

**Comment by robertpmansion** [comment]
The problem is just the letter casing. I'm using the lowercase 'saml2' name as AuthenticationType and in the below code convert the first letter to uppercase which causing the problem.

```
public override void ExecuteResult(ControllerContext context)
    {
        context.HttpContext.GetOwinContext().Authentication.Challenge(
            new AuthenticationProperties { RedirectUri = RedirectUrl }, LoginProvider.TitleCase());
    }
```

**Comment by AndersAbel** [comment]
@robertpmansion So it doesn't even trigger the middleware? We should look at the other middlewares if the authentication type comparison should be case sensitive.

**Comment by robertpmansion** [comment]
@AndersAbel Yes, this is also happening on other middlewares that we have, I just corrected the case sensitive.
