### ISSUE TITLE
Set custom value for ExpireTimeSpan on Cookies issued after SSO login

### ISSUE THREAD

**Issue by kb99** [KentorIT/authservices#648]
Is it possible to change the default expiredTimeSpan that is used for the session cookie issued by IdentityServer after AuthServices completes the SSO authentication?

I want to set one duration for people logging in through the standard login page (Basic Auth) and a different value for people logging in via SSO. (i.e force people logging in with SSO to have to auth every day but people logging in with username/password can stay logged in for 30 days for example)

I can see that this can be done via the IssueLoginCookie OWIN extension mentioned in this ticket [https://github.com/IdentityServer/IdentityServer3/issues/2063](https://github.com/IdentityServer/IdentityServer3/issues/2063) but I'm unsure if this can co-exist with the authservices flow?

**Comment by AndersAbel** [comment]
Are you using AuthServices together with IdentityServer or just plain AuthServices? Since you mention owin I assume you're using the Kentor.AuthServices.Owin package?

**Comment by kb99** [comment]
Yes we are using AuthServices along with IdentityServer and using the Kentor.AuthServices.Owin package.

**Comment by AndersAbel** [comment]
Then it's not really an AuthServices question. In that scenario the auth cookie issued by AuthServices is just used in an intermediate step before the IdentityServer session cookie is issued. From the name of it the IssueLoginCookie extension looks right. But you'll have to check in IdentityServer for the place where the external identity issued by AuthServices is swapped to IdentityServer's internal identity. That's where you can set the properties of the actual auth cookie used for the session.
