### ISSUE TITLE
Redirect users after login 

### ISSUE THREAD

**Issue by tomaulin** [KentorIT/authservices#651]
Hi,

We are implementing Kentor library to our Asp.Net MVC application (SP) and configured Kentor in web.config file.  This application will be deploying to 2 servers behind the load balancer. I wanted to make sure when users of this application browse the load balancer URL, one of the servers behind would initiate the SP flow and user will get authentication page loaded from IDP.

once the user logged in, would they land back into the same server behind load balancer who initiate the request? I've configured all load balancer URL in web.config.

Thanks,
-Maulin

**Comment by AndersAbel** [comment]
It's up to the load balancer to direct requests to either of the servers. AuthServices will work even if one server initiated the login flow with an AuthnRequest and the response is sent to the other server.

If you want to make sure that response is handled by the same server that initiated the request, you'll have to enable session affinity in the load balancer.

**Comment by tomaulin** [comment]
Thanks for the response.
It really helped a lot.
