### ISSUE TITLE
Implementation of logout

### ISSUE THREAD

**Issue by tomaulin** [KentorIT/authservices#652]
Hi,

We are leveraging Kentor library to our Asp.Net MVC web application (SP). how can we implement logout? 
when user click on logout, should be redirect them back to asp.net logout page? how do we ensure the session will be expired on IDP?

I would be happy to provide more info as needed.

Thanks,
-Maulin

**Comment by AndersAbel** [comment]
To initiate a single logout session redirect the user to /AuthServices/Logout. For logout to work you also need to have a service certificate configured in AuthServices. The easiest way to check if AuthServices have everything needed for logout is to check the metadata file at /AuthServices. If logout is enabled, it will contain endpoints for single logout.

**Comment by tomaulin** [comment]
Hi,

Thank you for your response on this.

I've further questions -



IDP (Site Minder) does not support single logout rather it would only
support fully deactivate the users.
Our application talk to Okta and Okta internally talks to IDP to send
logout request.

where do i obtain service certificate? where do i configure this cert?

Here is the configuration in my application web.config file.

<kentor.authServices entityId="http://localhost:58893/AuthServices"
returnUrl="http://localhost:58893/Home/Logon">
    <identityProviders>
      <add entityId="http://www.okta.com/exk8xaqdt7UE8m0iY0h7" logoutUrl="
https://epsicnof.oktapreview.com/login/signout" signOnUrl="
https://epsicnof.oktapreview.com/app/epsilon_dmp_1/exk8xaqdt7UE8m0iY0h7/sso/saml"
allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate
fileName="~/App_Data/Kentor.AuthServices.StubIdp.cer" />
      </add>
    </identityProviders>
    <federations>
      <add metadataLocation="
https://epsicnof.oktapreview.com/app/epsilon_dmp_1/exk8xaqdt7UE8m0iY0h7/sso/saml/Federation"
allowUnsolicitedAuthnResponse="true" />
    </federations>
    <serviceCertificates>
      <add fileName="~/App_Data/Kentor.AuthServices.Tests.pfx" />
    </serviceCertificates>
  </kentor.authServices>

**Comment by AndersAbel** [comment]
The service certificate can be any self-signed certificate that you generate which is marked with the correct key usage.

For the other questions about Site Minder/Okta it's too complicated to look into here. If you are interested in paid support/consulting services, please send me a mail.
