### ISSUE TITLE
AuthServices.AspNetCore with identityserver4

### ISSUE THREAD

**Issue by ravipunjwani** [KentorIT/authservices#653]
Hi @AndersAbel ,

Can you suggest how to integrate the aspnetcore version of Kentor.AuthServices with identityserver4.
I tried figuring out Kentor.AuthServices.AspNetCore on the same solution where IdentityServer4 is set up, and got the user logged in via Kentor Stub IDP, but I'm unable to get the access_token and refresh_token.

Not sure if this issue has to deal with AuthServices.AspNetCore or IdentityServer4.

Any sample project would be highly appreciated.

Also please suggest if there's any plans for releasing the final version of AuthServices.AspNetCore anytime sooner.

Cheers!
Ravi

**Comment by AndersAbel** [comment]
AuthServices.AspNetCore is still on a as-time-permits basis. There have been discussions with potential customers about sponsoring the work, but so far it is only discussions. I still intend to create a working AspNet Core middleware, but paid work comes first. When I look into it, I will of course make sure to test the asp.net core version with IdentityServer4. But until then, I can't help. If you're interested in consulting services and/or sponsoring development to get this done, please mail me).
