### ISSUE TITLE
Owin code configuration docs missing?

### ISSUE THREAD

**Issue by michaelchance** [KentorIT/authservices#654]
The Owin docs, https://github.com/KentorIT/authservices/blob/master/doc/OwinMiddleware.md point to the web.config docs, saying to configure it that way.  Then the web.config docs https://github.com/KentorIT/authservices/blob/master/doc/Configuration.md say that "The Owin middleware Can read web.config, but can also be configured from code" however no details are specified on how to do that?

**Comment by explunit** [comment]
Yes, you're right. I updated that page to give a little more description and point to the sample Owin application.
