### ISSUE TITLE
Configure Multiple ACS url for respective IDP

### ISSUE THREAD

**Issue by 9566707474** [KentorIT/authservices#657]
How to configure multiple ACS url for respective idp in sp using owin.

**Comment by AndersAbel** [comment]
Please provide a bit more context. Why do you want separate ACS urls? Would those ACS urls be on the same or different domains?

**Comment by 9566707474** [comment]
i have one Service provider(sp) and three different idp. For each idp i needs to give individual ACS url instead of common ACS in sp...

**Comment by 9566707474** [comment]
ACS url in same domains but three different idp.

**Comment by AndersAbel** [comment]
Why do you need separate ACS urls? AuthServices is designed to handle multiple Idps in one single ACS Url.

**Comment by 9566707474** [comment]
Based on our business we needs to be expose different ACS url to our client idp.

**Comment by 9566707474** [comment]
single service provider with exposing multiple ACS url.

**Comment by AndersAbel** [comment]
I still don't understand why you would need different ACS and I assume you're doing something very strange to your SAML setup.

But if you want to do it you can create an own dummy middleware that handles those extra ACS urls and calls the `AcsCommand.Run()` method.

**Comment by 9566707474** [comment]
For load balancing and security purpose our clients expecting separate urls.. because they are accessing from different idp domains with different request url..

**Comment by AndersAbel** [comment]
Looks like there's a bigger design issue here to understand. That's nothing I can answer here on the issue tracker. If you're interested I can help with this on a consultancy basis. Please mail me for details.
