### ISSUE TITLE
Connect OKTA using Owin with aspnetmembership (website-C#)

### ISSUE THREAD

**Issue by FACAMK** [KentorIT/authservices#660]
Hi,

I've been struggling to setup SAML implementation of OKTA, Kentor and the asp.net membership for some reason, and I've been requested to do the OWIN implementation.
Is this possible, and if so how?

**Comment by AndersAbel** [comment]
Yes, it's possible, but you will have to do some coding. The standard ASP.NET application template contains the code required to use owin middlewares together with ASP.NET Identity. There is no direct dependency between the owin middleware and ASP.NET Identity, so you can write your own AuthenticationController that uses an ASP.NET Membership database.

While it's possible, I'd definitely recommend against it as ASP.NET Membership's password storage (if you still will allow passwords for some users) is outdated and not considered secure any more.
