### ISSUE TITLE
Assembly signing

### ISSUE THREAD

**Issue by hoekj** [KentorIT/authservices#662]
We currently developing a MFA plugin for Microsoft AD FS which authenticates to a Second Factor endpoint using the SAML protocol.  This plugin creates and processes the SAML messages for the Second Factor endpoint. All assemblies for this plugin has to be installed in the Global Assembly Cache of the AD FS server. Currently your assembly isn’t signed so it’s not possible to install it in the GAC. Could you sign the assembly and (if necessary) provide an extra NuGet package which contains the signed assembly?

**Comment by AndersAbel** [comment]
For reference, please see #198 which discusses assembly signing.

That said, I think that a GAC requirement from ADFS is the first solid case I've heard of where strong naming is really required for a technical reason. I won't sign the official nuget packages. I suggest that you look at workarounds such as https://github.com/brutaldev/StrongNameSigner which signs imported packages. Would that be an option for you?

**Comment by hoekj** [comment]
Thanks for your reply. I tried your workaround. Yesterday tried to sign your assembly (with ildasm and ilasm), but get a runtime error about the internals visible to. The StrongNameSigner deals great with this problem. Thanks!
