### ISSUE TITLE
ASP.net form based application.

### ISSUE THREAD

**Issue by tkamesh08** [KentorIT/authservices#663]
Does the Kentor Auth Services support ASP.net form based application ?
If yes, please share the sample ASP.net form based application with Kentor auth services.

**Comment by AndersAbel** [comment]
Yes, AuthServices supports ASP.NET Form based applications with the HttpModule. Look in the SampleApplication for how it is configured. Even though that application is MVC-based, the same setup works with web forms.

**Comment by tkamesh08** [comment]
Thanks for your response. I have managed to set the config and implement for web forms. but i am getting the following error in the target page
![isuue](https://cloud.githubusercontent.com/assets/1502548/24045822/6689da00-0b46-11e7-9871-07b141550673.JPG)

MY APPLICATION CONFIG 
<configuration>
  <configSections>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="CVCpHRism.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    </sectionGroup>
    <section name="system.identityModel" type="System.IdentityModel.Configuration.SystemIdentityModelSection, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
    <section name="system.identityModel.services" type="System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
    <section name="kentor.authServices" type="Kentor.AuthServices.Configuration.KentorAuthServicesSection, Kentor.AuthServices"/>
  </configSections>
  <appSettings />
  <connectionStrings />
   <system.web>
    <httpModules>
      <add name="MyHttpModule" type=" CVCpHRism.Performance.AssessmentModule, CVC.pHRism.Web"/>
      
      <add name="SessionAuthenticationModule" type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
      
      <add name="Saml2AuthenticationModule" type="Kentor.AuthServices.Saml2AuthenticationModule, Kentor.AuthServices"/>
    </httpModules>
    <compilation debug="true" targetFramework="4.6"/>
    <authentication mode="Forms" >
      <forms loginUrl="~/AuthServices/SignIn"/>
    </authentication>
    <authorization>
      <deny users="?"/>
    </authorization>
       <pages controlRenderingCompatibilityVersion="3.5" clientIDMode="AutoID" />
    <sessionState timeout="30" />
  </system.web>
  <system.webServer>
    <defaultDocument>
      <files>
        <add value="main.aspx" />
      </files>
    </defaultDocument>
    <validation validateIntegratedModeConfiguration="false" />
    <modules>
      <add name="SessionAuthenticationModule" type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
      <add name="Saml2AuthenticationModule" type="Kentor.AuthServices.HttpModule.Saml2AuthenticationModule, Kentor.AuthServices.HttpModule"/>
    </modules>
  </system.webServer>
  <kentor.authServices
     entityId="http://laptop-tduvdrob/myHR/AuthServices"
     returnUrl="http://laptop-tduvdrob/myHR/fatca/test_sso.aspx">    
    <identityProviders>
      <add entityId="http://www.okta.com/exk9uw02r8kFdgdBG0h7"
           signOnUrl="https://dev-424154.oktapreview.com/app/phrismsolutionsdev424154_kentorauthservicesapp1_1/exk9uw02r8kFdgdBG0h7/sso/saml"
           allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate fileName="~/Fatca/App_Data/okta.cert"/>
      </add>
    </identityProviders>
  </kentor.authServices>
  <system.identityModel>
    <identityConfiguration>
    </identityConfiguration>
  </system.identityModel>
  <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" />
    </federationConfiguration>
  </system.identityModel.services>
  <system.net>
    <defaultProxy useDefaultCredentials="true" />
  </system.net>
</configuration>

SAML response in chrome pluign
![samlissue](https://cloud.githubusercontent.com/assets/1502548/24046051/2a98094e-0b47-11e7-8710-c8611899c9e4.JPG)

Can you please help me on this?

**Comment by AndersAbel** [comment]
Disable the SQL Role Provider HTTP Module. It is probably loaded from the machine.config, so you have to add a line to your web.config to remove it.

**Comment by tkamesh08** [comment]
I have added the below config in web.config but still the issue exists
<membership>
      <providers>
        <remove name ="AspNetSqlMembershipProvider"/>
      </providers>
    </membership>
    <profile>
      <providers>
        <remove name="AspNetSqlProfileProvider" />
      </providers>
    </profile>

**Comment by AndersAbel** [comment]
Is the SqlRoleProvider still listed in the stack trace? In that case you haven't removed the right thing. If the error message/stack trace is different, please post a new issue.

**Comment by tkamesh08** [comment]
Still SqlRoleProvider  is listed in the stack trace. Do you have any idea what needs to be added in the web config to remove sqlroleprovider because i have tried with all the config options it doesn't help me.

**Comment by tkamesh08** [comment]
After adding the below config in app settings it worked. Thanks for your help.
<add key="enableSimpleMembership" value="false" />

**Comment by tkamesh08** [comment]
When i logout from IDP(OKTA), my SP URLhttp://laptop-tduvdrob/myHR/AuthServices/signin works fine as expected goes to the OKTA login page.
But if I directly browse to the return URL "http://laptop-tduvdrob/myHR/Test/Test_SSO.aspx", then the ClaimsPrincipal.Current.Claims still exiists which causes the issue.
I have tried the below, but none of them works
 Session.RemoveAll();            
 Session.Abandon();
 Response.Cookies.Clear();

Can you please let me know how to clear this claim when i click on the sign-out button in my web form application.

**Comment by albinsunnanbo** [comment]
@tkamesh08 The logout issue should really be a separate issue, but you could check the sample application in this repository, they all implement sign out.

**Comment by tkamesh08** [comment]
@albinsunnanbo yes i have seen the sample application for singout, it has been implemented for MVC application as <a id="logout" href="@Url.Content("~/AuthServices/Logout?ReturnUrl=" + Uri.EscapeDataString(Url.Content("~/?Status=LoggedOut")))">..
The same i need to implement in web form application. Can you please help me on this?

**Comment by albinsunnanbo** [comment]
If your application resides in the root of the website it's just a simple link.

    <a id="logout" href="/AuthServices/Logout?ReturnUrl=%2F%3FStatus%3DLoggedOut">

If the site is in /MyApp/ you create the link 

    <a id="logout" href="/MyApp/AuthServices/Logout?ReturnUrl=%2FMyApp%2F%3FStatus%3DLoggedOut">

There might be a smarter way to do it in webforms, but this is the HTML it should boil down to
You could of course change `?Status=LoggedOut` to `/MyLoggedOutPage.html`
