### ISSUE TITLE
LoadMetadata set to false

### ISSUE THREAD

**Issue by parequena** [KentorIT/authservices#664]
Hello!
i've set loadMetadata as false

web.config: <kentor.authservices/identityproviders>:
`<add entityId="https://stubidp.STUBIDP.forest/adfs/services/trust" loadMetadata="false" signOnUrl="https://stubidp.stubidp.forest/adfs/ls/idpinitiatedsignon.aspx" allowUnsolicitedAuthnResponse="true" binding="HttpPost">
<signingCertificate fileName="~/App_Data/stubidpSSO.cer" />
      </add>`

And entityID is still treated as an URL (Or that's what i think) because, i've commented "metadataLocation" attribute from that idp and i still can connect my idp (adfs) to my application.

Also, when i debbug the app, on the IOptions from kentor, i see that metadataLocation is set as the entityid value (when loadMetadata is set to false)
![bug](https://cloud.githubusercontent.com/assets/22152384/24006092/1165dbb8-0a6b-11e7-982a-e92e76d7b1ed.png)

If i'm wrong (probably) how can my application (SampleMVCApplication) know wich is my idp metadata if is not set on metadataLocation?

Or is the metadata not necessary for an idp to connect to the application?

Thank you!

**Comment by albinsunnanbo** [comment]
AuthServices by default sets `MetadataLocation = EntityId` if you don't specify `MetadataLocation` explicitly.
But since you have `loadMetadata = false` the metadata is never loaded, instead it should use the `signOnUrl` as specified in web.config

**Comment by parequena** [comment]
So, if we have the signOnUrl we don't need the metadata? And if we have the metadata, we need the signOnUrl?

**Comment by AndersAbel** [comment]
There are two ways to configure and Idp in AuthServices. Either load the Ipds metadata. Then you don't have to fill in anything else (such as`SignOnOurl`). Or configure all the relevant properties yourself, then you don't have to load metadata.
