### ISSUE TITLE
Not all claims from ClaimsIdentity are present on ApplicationUser and I don't know why

### ISSUE THREAD

**Issue by olavaukan** [KentorIT/authservices#665]
I'm trying to use the Kentor.AuthServices OWIN middleware in my application and I'm experiencing some weirdness that I don't understand. This weirdness can be observed in the sample SampleOwinApplication application:

- Build and launch application
- Log in with KentorAuthServices, using the StubdIdp and selecting the Admin Almighty user
- In the ExternalLoginCallback method of the AccountContoller we get a 'loginInfo' object by calling AuthenticationManager.GetExternalLoginInfoAsync();
- The loginInfo.ExternalIdentity.Claims property contains all the claims from the StubIdp:
```
{http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: AdminAlmighty}
{http://schemas.microsoft.com/ws/2008/06/identity/claims/role: Administrator}
{http://schemas.microsoft.com/ws/2008/06/identity/claims/role: root}
{SpecialPowers: All of them}
{http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod: urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified}
{http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant: 2017-03-16T11:35:31.000Z}
{http://kentor.se/AuthServices/LogoutNameIdentifier: ,,urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified,,AdminAlmighty}
{http://kentor.se/AuthServices/SessionIndex: 42}
```
- On first login the code redirects to ExternalLoginConfirmation to promt for an email.
- In the ExternalLoginConfirmation method of the AccountController we get a 'info' object by again calling AuthenticationManager.GetExternalLoginInfoAsync();
- The info.ExternalIdentity.Claims property still contains all the claims from the StubIdp.
- It then creates a 'user' object of type ApplicationUser, passing in the email and the calling UserManager.CreateAsync(user);
- The user.Claims property is empty.
- It then adds a login for the user by calling UserManager.AddLoginAsync(user.Id, info.Login);
- The user.Claims property is still empty.
- It then logs in the user by calling SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
- This calls ApplicationSignInManager.CreateUserIdentityAsync(); which in turn calls ApplicationUser.GenerateUserIdentityAsync();
- The ApplicationUser.Claims property is still empty.
- In the GenerateUserIdentityAsync method of ApplicationUser we get a 'userIdentity' object by calling manager.CreateIdentityAsync();
- The userIdentity.Claims property contains a different set of claims than the original claims from the StubIdp:
```
{http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: 4180fe31-5ba4-4086-b6aa-df5ebc569859}
{http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: blah@derp.com}
{http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider: ASP.NET Identity}
{AspNet.Identity.SecurityStamp: 11f579d5-c96a-4bfb-a235-ec1c682e0a25}
```
- After having logged in you are redirected back to the front page of the sample application. Here it lists all the claims on the current user, but now there are two additional claims from the StubIdp that were not in the userIdentity.Claims collecion:
```
{http://kentor.se/AuthServices/SessionIndex: 42}
{http://kentor.se/AuthServices/LogoutNameIdentifier: ,,urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified,,AdminAlmighty}
```
- The complete list of claims now looks like this:
```
{http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: 4180fe31-5ba4-4086-b6aa-df5ebc569859}
{http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: blah@derp.com}
{http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider: ASP.NET Identity}
{AspNet.Identity.SecurityStamp: 11f579d5-c96a-4bfb-a235-ec1c682e0a25}
{http://kentor.se/AuthServices/SessionIndex: 42}
{http://kentor.se/AuthServices/LogoutNameIdentifier: ,,urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified,,AdminAlmighty}
```
There is a comment saying 'Add custom user claims here' but as far as I can tell there is no place in ApplicationUser.GenerateUserIdentityAsync() where we get a reference to the original claims provided from the StubdIdp so what am I doing wrong here? How to I ensure that the 'userIdentity' contains all the claims from the StubIdp?

**Comment by AndersAbel** [comment]
What you describe is the standard MVC template with ASP.NET Identity. In that solution, the external identity (with the claims from the StubIdp) are only used to look up an internal identity from ASP.NET Identity. If you want to preserve any of the info you got from the StubIdp, you need to write custom code in the ExternalLoginCallback method to carry those claims over. To understand what's happening, please see https://coding.abel.nu/2014/06/understanding-the-owin-external-authentication-pipeline/

Finally for those to extra claims (SessionIndex and LogoutNameIdentifier). Those are needed for Single Logout to work. AuthServices does some black magic to ensure that those claims are carried over to the new identity that was loaded from ASP.NET Identity, to make it easier to get logout working.

**Comment by olavaukan** [comment]
Thanks for the quick response. I did kind of suspect this was by design and just a case of me now knowing enough about how this is supposed to work.

That being said, I'm still a bit confused on where my custom code should go. If I understand correctly I should handle this in the ExternalLoginCallback method of AccountController, after SignInManager.ExternalSignInAsync() is called, but at that point I don't have an ApplicationUser object to add claims to. As far as I can tell that is only created when the user is logged on the first time and registers an email address in the ExternalLoginConfirmation method.

So I added some code in ExternalLoginConfirmation after UserManager.CreateAsync() but before UserManager.AddLoginAsync() that copies claims from the external identity onto the ApplicationUser object. This seems to do the trick. If I log out and log in again with the same external user (this time ExternalLoginConfirmation is not called since the user has a local identity) I now get the complete list of claims whereas before I would only get the local identity claims if I logged out and in again. 

Is this a reasonable way to handle it?

**Comment by AndersAbel** [comment]
Looks like you found a reasonable way to handle it yes. But please be aware that doing the copying in `ExternalLoginConfirmation` will only copy the claims on the first login. If attributes are updated in the source Idp that won't get carried over. To do that, you need to invoke the copying from `ExternalLoginCallback` too.
