### ISSUE TITLE
Kentor Cookie

### ISSUE THREAD

**Issue by parequena** [KentorIT/authservices#668]
Hello, there is an easy way to rename the created cookie? A module, variable or defined constant?

**Comment by explunit** [comment]
No, the cookie names are part of the source code at the moment and are not configurable. You can turn off the logout state cookie through the Compatibility.DisableLogoutStateCookie option, but other cookies remain.

**Comment by AndersAbel** [comment]
@parequena By the way, why would you need to change the name?

**Comment by parequena** [comment]
Nothing special
