### ISSUE TITLE
Invalid cert for https://stubidp.kentor.se

### ISSUE THREAD

**Issue by albinsunnanbo** [KentorIT/authservices#670]
![image](https://cloud.githubusercontent.com/assets/5158396/24197318/71c1c554-0f01-11e7-92f4-d117a3033f05.png)

**Comment by AndersAbel** [comment]
We've never promised https for the stubidp. That's the default azure hosted certificate that you are served up for *.azurewebsites.net.

For now, enabling https on the stub idp is won't fix.
