### ISSUE TITLE
Help with some holes in the documentation

### ISSUE THREAD

**Issue by jimitndiaye** [KentorIT/authservices#671]
Is there a way to get/set the SP metadata URL for metadata exchange purposes?
There doesn't seem to be a way of doing so. I mean the SP metadata to be used to create federation relationships with specific IdPs. "~/FederationMetadata/2007-06/federationmetadata.xml" is the standard path, but I've had the module path itself respond with the SP metadata XML. 

I'm basically replacing the standard OWIN Wsfederation setup with Kentor.AuthServices.Owin (so passive redirect straight to IDP - no login forms in-app) but it is proving quite tricky and none of the examples in the source code seem to help. Basically what is the expected setup configuration when not using ASP.Net Identity, but instead just going for a straight up passive redirect, similar to the standard WsFederation OWIN auth provider.

**Comment by jimitndiaye** [comment]
Nevermind. Figured it out by going through the source code.

**Comment by Dunkirk** [comment]
I would really like to know what the answer to this was. Seems like the docs ought to be updated with this information. If they have; I can't find it.

**Comment by explunit** [comment]
I added a brief description of this to the OWIN middleware doc: https://github.com/Sustainsys/Saml2/blob/master/docs/owin-middleware.rst#module-path-and-metadata
