### ISSUE TITLE
How to combine internal and external authentication?

### ISSUE THREAD

**Issue by BjoernBeeli** [KentorIT/authservices#676]
I have a ASP.NET web form site with ASP.NET Identity. On the own login page it will make an internal authentication.

I successful extended this site to use Kentor.AuthServices.HttpModule for external authentication instead of the internal one. That way the own login page is not used, but the one from the IdP.

Requirement:
We have to allow for some users to use the internal and for the other the external authentication for the same site.
For that the own login page should be extended with a button 'external authentication'. That way it will redirect then to the IdP. Otherwise the user can login directly from this login page.

I have no idea how to implement that. I don't want to use a own federated authentication site, which will manage that.
Is there an example how to do that or any hint?

**Comment by AndersAbel** [comment]
If you want to integrate ASP.NET Identity for local accounts and SAML based authentication you should use the owin module instead. It integrates nicely with ASP.NET Identity. Please see the SampleOwinApplication in the repository.
