### ISSUE TITLE
Signout at IdP does not sign out of session at Relying Party

### ISSUE THREAD

**Issue by willrosn** [KentorIT/authservices#683]
We are using Kentor authservices to manage a relying party website.  When the user signs out of the session at the IdP's website, the session at the relying party website is still active. This is unusual to us as other applications that use the IdP's SAML guid are automatically redirected to the login page of the IdP.  Is there a setting in the webconfig that would force unauthenticated users to the IdP login page?

**Comment by AndersAbel** [comment]
What you need to do is enable Single Logout in AuthServices and configure the Idp with the SLO endpoint. If you are using metadata for configuration things should work if you ad a service certificate for AuthServices (which is require for the single logout functionality to be enabled).
