### ISSUE TITLE
User.IsAuthenticated remains false after successful login

### ISSUE THREAD

**Issue by nicswan** [KentorIT/authservices#684]
I'm attempting to integrate this plugin with an existing MVC project (currently on .NET 4.6.1), using ADFS as the IdP. I've worked through a bunch of issues, but am finally close (or at least it seems like it).  I am successfully sent to ADFS, can log in, and am sent back to my web app. I can follow the SAML request/response and see a success status code in the response from ADFS to my app. (It uses an encrypted assertion, so I cannot see the claims in the response.) However, I don't have user info and a call to User.IsAuthenticated returns false. Using code from the sample MVC project, I attempted to output the claims (with type and value). Only one type is outputted (`http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name`) and no value.

My config:
```
<kentor.authServices entityId="https://local.example.com/myapp/AuthServices" returnUrl="https://local.example.com/myapp" authenticateRequestSigningBehavior="Always" outboundSigningAlgorithm="SHA256">
    <identityProviders>
      <add entityId="http://adfs.example.com/adfs/services/trust" signOnUrl="https://adfs.example.com/adfs/ls" logoutUrl="https://adfs.example.com/adfs/ls" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect" loadMetadata="true" metadataLocation="https://adfs.example.com/federationmetadata/2007-06/federationmetadata.xml" />
    </identityProviders>
    <serviceCertificates>
      <add storeName="My" storeLocation="LocalMachine" findValue="xxx" x509FindType="FindByThumbprint" />
    </serviceCertificates>
</kentor.authServices>
<system.identityModel.services>
	<federationConfiguration>
	  <cookieHandler requireSsl="false" name="MyApplicationAuth" />
	</federationConfiguration>
</system.identityModel.services>
```

Anyone have ideas on how to fix/troubleshoot this?

Thanks,

--Nicole

**Comment by nicswan** [comment]
I'm back to doing more investigation. Once I've logged in (been sent to ADFS, entered credentials, and returned), even though `System.Web.HttpContext.Current.User.Identity.IsAuthenticated` (when used in my view) continues to return false (and the `User.Identity.Name` is empty), if I go to log in again, I do a round trip to ADFS and am not asked to reenter my credentials. And, if I follow the logout URL, I can see my username as the NameID in the LogoutRequest.  So...it appears the authentication info is...somewhere. What am I missing here?

**Comment by nicswan** [comment]
Is there another preferred location for questions that I missed (StackOverflow seems hit or miss too)? I've done extensive investigation on my end and don't think I'm missing anything obvious. As I understand it, in older versions of .NET framework (before 4.5?), claims from an external authenticator had to be translated to the native User/Identity context, but that isn't necessary in newer versions (I've now tried .NET 4.5.2, 4.6.1, and 4.6.2). I even experimented with trying claims translation and the values weren't there.

**Comment by explunit** [comment]
Are you able to create a simplified/standalone project that shows the problem and then publish it on github? It sounds like your problem is not specific to ADFS so perhaps your open source recreation of the problem could use the Stub IDP?

Another avenue of support is to email [Anders Abel](https://github.com/AndersAbel) regarding paid consulting time.

**Comment by nicswan** [comment]
Thanks so much for the response, @explunit. I had been able to set up the sample AuthServices MVC project with the StubIDP and had just started adding our ADFS IdP to that setup as a test when I found the problem. As happens, it was a dumb one - I discovered an enabled role manager I had missed. Once I disabled that, I could see the claims and the user identity was populated as expected. Gah.

**Comment by explunit** [comment]
Glad to hear you found the problem. Thanks for reporting the resolution here so others who search on this issue can watch out for that kind of thing.

**Comment by anhhoangbui** [comment]
Hi guys,

I'm having the exact same issue here. Can someone help me elaborate on what is the "enabled role manager I had missed" and how do I go and disable it?

**Comment by nicswan** [comment]
@anhhoangbui The role manager I mention has nothing to do with the Kentor AuthServices library. It's something that is a part of my application for _authorization_ purposes once authentication is complete. In my case, though, an error coming from it was obscuring my ability to troubleshoot claims issues (as returned from my ADFS instance via AuthServices authentication). If your app is using a role manager it would be set up in your web.config.

**Comment by JohanHeyvaert** [comment]
Hi everyone,

We had a similar problem (User.IsAuthenticated always returned false). 

A relic from a previous config turned out to be the cause:
```
  public partial class Startup
  {
    public static void ConfigureWebApi(HttpConfiguration config)
    {
        // Configure Web API to use only bearer token authentication.
        **config.SuppressDefaultHostAuthentication();** 

        // etc
    }
  }
```
Removing that line fixed the problem.

Hopefully this helps someone out.

**Comment by patilmohan91** [comment]
@nicswan I am getting Request.IsAuthenticated True but When I am reading claims as 
Var claims = (User as ClaimsPrincipal).Claims;
returns me null. I have generated the web.config from FedUtil.exe

**Comment by nicswan** [comment]
@patilmohan91 I suggest looking through the sample projects in the repo to make sure you are accessing and outputting the claims correctly.

**Comment by patilmohan91** [comment]
@nicswan I did it Correctly, There was issues of Certificates. The code is working now. Thanks for your reply.

**Comment by divekarvinit** [comment]
I was facing this problem because, I had set;

`app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);`

Due to the above line, `Microsoft.Aspnet.Identity` is not set.

If you want to use external sign in follow this [link] (app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);)

**Comment by pagetangalin** [comment]
> @nicswan I did it Correctly, There was issues of Certificates. The code is working now. Thanks for your reply.

Hi @patilmohan91  what was your issue with the certificate? im having the same issue with the MVC app i deploeyd in an IIS server im getting null reference exception in the Claims
