### ISSUE TITLE
NullReferenceException in Saml2RedirectBinding.Bind

### ISSUE THREAD

**Issue by JJoe2** [KentorIT/authservices#685]
I am new to SAML and am trying to get a ServiceProvider with kentor.authservices.mvc working together with an example IdentityProvider (the MvcExampleIdentityProvider sample provided with the ComponentSpace SAML component).

Signon is working fine, but when I try to initiate an IdentityProvider-initiated logout, my ServiceProvider throws an NRE in the Saml2RedirectBinding.Bind method:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Kentor.AuthServices.WebSso.Saml2RedirectBinding.Bind(ISaml2Message message)
   at Kentor.AuthServices.WebSso.LogoutCommand.HandleRequest(UnbindResult unbindResult, IOptions options)
   at Kentor.AuthServices.WebSso.LogoutCommand.Run(HttpRequestData request, String returnPath, IOptions options)
   at Kentor.AuthServices.WebSso.LogoutCommand.Run(HttpRequestData request, IOptions options)
   at Kentor.AuthServices.Mvc.AuthServicesController.Logout()
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
  ... etc ...

I've run it under the debugger, and the NRE is thrown at the following line, because "message.DestinationUrl" is null:

            var redirectUri = new Uri(message.DestinationUrl.ToString()
                + (string.IsNullOrEmpty(message.DestinationUrl.Query) ? "?" : "&")
                + queryString);

Is this a bug?  Or if not, how can I ensure message.DestinationUrl is not null?

**Comment by AndersAbel** [comment]
Looks like a bug in AuthServices. Can you please show how you've configured the IdentityProvider in AuthServices?

**Comment by JJoe2** [comment]
Thanks for the fast reply. My kentor.authServices configuration has a single identityProvider configured as follows:

    <add entityId="http://localhost/MvcExampleIdentityProvider"
         signOnUrl="http://localhost/MvcExampleIdentityProvider/SAML/SSOService"
         allowUnsolicitedAuthnResponse="true" binding="HttpRedirect"
         wantAuthnRequestsSigned="true"
        >
      <signingCertificate fileName="~/App_Data/Certificates/idp.cer" />
    </add>

**Comment by AndersAbel** [comment]
Ok, the setup lacks som configuration. But AuthServices should throw an exception telling you that the configuration is missing instead of a `NullReferenceException`.

You need to add a `logoutUrl` attribute pointing to the single logout service of the idp. That's what's causing the nullref - it hits null when reading the destination of the logout response message.

**Comment by JJoe2** [comment]
Thanks for being so responsive.  That's fixed it.

**Comment by AndersAbel** [comment]
You were lucky - I'm working on a bug fix release that should go out later today so I wanted to see if this was something that I should get included.
