### ISSUE TITLE
Is Deflate here a good idea?

### ISSUE THREAD

**Issue by leotohill** [KentorIT/authservices#689]
I see that Saml2RedirectBinding uses DeflateStream().    I'm a little surprised, because I thought that generally, compression would be the responsibility of the web server.   No?

**Comment by albinsunnanbo** [comment]
Saml2RedirectBinding compresses the Query string argument and that decompression is as far as we know not supported by any web server.

**Comment by AndersAbel** [comment]
Further to what @albinsunnanbo already said, this behaviour is part of the SAML2 standard and not a design decision we've made.
