### ISSUE TITLE
Single Logout from application

### ISSUE THREAD

**Issue by tomaulin** [KentorIT/authservices#691]
I'm implementin Singlelogout by configuring selfsigned x509 cert and using pfx file in kentor configuration, it makes my login functionality not working. if i take this out and replace with default okat pfx file then it works.

how do i make my selfsigned cert work for single logout? 
Am i missing any other configuration?
what should be my logoutUrl?
```
 <kentor.authServices entityId="http://localhost:58893/AuthServices" returnUrl="http://localhost:58893/Home/Logon">
    <identityProviders>
      <add entityId="http://www.okta.com/exk8xaqdt7UE8m0iY0h7" logoutUrl="https://localhost:58893/AuthServices/Logout" signOnUrl="https://epsicnof.oktapreview.com/app/epsilon_dmp_1/exk8xaqdt7UE8m0iY0h7/sso/saml" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate fileName="~/App_Data/Kentor.AuthServices.StubIdp.cer" />
      </add>
    </identityProviders>
    <federations>
      <add metadataLocation="https://epsicnof.oktapreview.com/app/epsilon_dmp_1/exk8xaqdt7UE8m0iY0h7/sso/saml/Federation" allowUnsolicitedAuthnResponse="true" />
    </federations>
    <serviceCertificates>
      <!--<add fileName="~/App_Data/Kentor.AuthServices.Tests.pfx" />-->
    <add fileName="~/App_Data/Epsilon.Tests.pfx"  />
    </serviceCertificates>
  </kentor.authServices>
```

**Comment by AndersAbel** [comment]
The `<signingCertificate>` node under `<identityProviders>` should be the Okta certificate (as you already have discovered)

The service certificate looks right. What's missing is a `logoutUrl` in the `<identityProviders><add>` tag. It should point to the logout service url of okta.
