### ISSUE TITLE
SSO end user experience

### ISSUE THREAD

**Issue by ArjunPathak** [KentorIT/authservices#695]
I have used SampleMvcApplication from the [repository ](https://github.com/KentorIT/authservices)and configured it to use with Okta. It works fine. 
One thing I see missing here is this case:
1. User opens browser and logs in in his Okta account.
2. He then opens a new tab and hit my application url (http://localhost:2181/home)
>> It shows again SignIn options 
>> Expected : It should sense user is already logged in and show as logged in user.
Although I am new to SSO, but as a common case if one is logged in to his gmail and hits drive.google.com in another tab, the drive app does not ask for login again. 
Is this experience possible to achieve using Kentor ? Is there any module/service available in the Kentor library that "_**Sense**_" if the user is logged in to his IdP in the target browser so that he can be redirected directly to the page he wants to access ?

**Comment by AndersAbel** [comment]
In "It shows again SignIn options" I assume you mean Okta sign in options? In that case it is an Okta configuration issue. AuthServices just redirects the user to the Idp. It's up to the Idp to use an existing session on the Idp or require the user to create a new one.

**Comment by ArjunPathak** [comment]
Hi Anders,

By "It shows again SignIn options" - I mean it shows the sample MVC application's SignIn page  (index.cshtml - as below), reason being, the `User.Identity.IsAuthenticated` is false due to SSO is not initiated yet. 

![signinoptions](https://cloud.githubusercontent.com/assets/8929371/25370290/8a3d3858-2981-11e7-87ef-4dc86dc224e2.png)

Here, case is - user has already logged into his Okta and hits the SP site's url in another tab (not clicked the App chicklet in his Okta dashboard) and he is presented with the SP site's Sign In page. However, clicking on the Okta sign in link on this page, the code just verifies browser and senses that user is logged in alerady there and skips Okta login page - which is good. **I am just wondering how can I initiate this sensing on the page load itself** so that it first checks whether user is logged in to Okta, and if not, then only show the sign in page; otherwise allow user to continue accessing the SP site.

Given code perspective this is ok because SSO is not initiated at this point so the `User.Identity` is not populated with user info and it ends up asking user to select sign in option, but per the end user perspective - as he knows he has logged into Okta already, he may expect that direct accessing the url would allow him to see the SP page directly instead of landing first on sign in options.

Regards,
Arjun

**Comment by AndersAbel** [comment]
You need to make a roundtrip to Okta to detect if the user is already logged in there. You can do that in a hidden iframe, with setting "IsPassive=true" in the request. But that would require some code changes to AuthServices to support it. Either you can do it yourself as a pull request, or we can do it as a consultancy service. Mail me if that's interesting.

**Comment by ArjunPathak** [comment]
Ok Anders, thanks for the information. I will get back to you if require this as a feature.

**Comment by PeetKavel** [comment]
Because this is an old topic. Is Passive mode already available
