### ISSUE TITLE
Looking for an example to send saml request to identityserver3 and get back saml resposne

### ISSUE THREAD

**Issue by VjParmar** [KentorIT/authservices#696]
Hi,
 in my project i want to send saml request to our identityserver3 provder which will then redirect to actual saml server which will be authenticating user and then send back the respone and the idenittyserver3 read the response , generate the single sign on cookie and return the result in form of saml token

I am able to figure out how to send normal/http request and redirect to external saml server and get back the token and claims  but sending saml request and getting saml response is something not able to find out.

**Comment by explunit** [comment]
If your IdentityServer3 is already set up to broker the authentication with the SAML Idp, then why do you also want SAML between your application and IdentityServer3? Wouldn't it be more straightforward to use OpenId Connect between your application and IdentityServer3?

**Comment by AndersAbel** [comment]
IdentityServier3 does not support receiving AuthnRequests from a SAML2 SP such as AuthServices. There's been discussions on creating such a plugin for IdentityServer3 but it won't happen unless someone sponsors the work.

Do as @explunit recommends and use OpenID Connect from your application to IdentityServer3.
