### ISSUE TITLE
authservices / adfs / saml2p tutorial?

### ISSUE THREAD

**Issue by osudude** [KentorIT/authservices#697]
Is there a tutorial that shows how to configure authservices for use with ADFS / SAML2P?

thanks

**Comment by nicswan** [comment]
Not that I've found, though there is a good amount of info in the [AuthServices configuration information](https://github.com/KentorIT/authservices/blob/master/doc/Configuration.md). I'm also working on ADFS authentication and have worked through many issues (most related to certificates and authservices config in web.config) so my config might be of help:

```
<kentor.authServices entityId="https://local.example.com/myapp/AuthServices" returnUrl="https://local.example.com/myapp" authenticateRequestSigningBehavior="Always" outboundSigningAlgorithm="SHA256">
    <identityProviders>
      <add entityId="http://adfs.example.com/adfs/services/trust" signOnUrl="https://adfs.example.com/adfs/ls" logoutUrl="https://adfs.example.com/adfs/ls" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect" loadMetadata="true" metadataLocation="https://adfs.example.com/federationmetadata/2007-06/federationmetadata.xml" />
    </identityProviders>
    <serviceCertificates>
      <add storeName="My" storeLocation="LocalMachine" findValue="xxx" x509FindType="FindByThumbprint" />
    </serviceCertificates>
</kentor.authServices>
<system.identityModel.services>
	<federationConfiguration>
	  <cookieHandler requireSsl="true" name="MyApplicationAuth" />
	</federationConfiguration>
</system.identityModel.services>
```

I'm using the Kentor.AuthServices.Mvc package, so I also had to add routes to the AuthServices controller actions in my Global.asax file. Let me know what other info you need, and I can try to help if I can.

--Nicole

**Comment by osudude** [comment]
@nicswan is it possible to set the kentor.authServices configuration via code instead of via config?  We just finished gutting our ws-fed wif config and replaced it with code to make our web.config a little more manageable across our many web apps.

**Comment by explunit** [comment]
Yes, configuration via code is another option. See example here: https://github.com/KentorIT/authservices/blob/v0.21.1/SampleOwinApplication/App_Start/Startup.Auth.cs#L54-L82
