### ISSUE TITLE
POST to /authservice/acs redirect 302 to user/ExternalLoginCallback with error=access_denied

### ISSUE THREAD

**Issue by hamish-tushar** [KentorIT/authservices#698]
I am trying to write a simple service provider with auth0 as IDP. The setup is correct since i have debugged on auth0 UI and also with auth0 sdk.

I have linked my project to Kentor.AuthServices.owin 0.21.1. 
My startup.cs is ripped off from https://github.com/auth0/auth0-aspnet-owin/blob/master/examples/MvcSample-SAML/Startup.cs

Do i need to define the controller myself AuthService/ACS? 
Copying the same credential and using kentor auth services i can see in saml tracer the post coming back from IDP with saml xml having all details.
My saml response post is 
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>

My call back is:
        [AllowAnonymous]
        public async Task<ActionResult> ExternalLoginCallback(string returnUrl)
        {
            var loginInfo = await HttpContext.GetOwinContext().Authentication.GetExternalLoginInfoAsync();
            if (loginInfo == null)
            {
Can you tell me what i have missed.? My loginInfo null. and Is missing the claims.

**Comment by AndersAbel** [comment]
When the external LoginInfo is null, it's often a case of the owin cookie monster. Please see [this blog post](https://coding.abel.nu/2014/11/catching-the-system-webowin-cookie-monster/) for an explanation and recommendations.
