### ISSUE TITLE
Single Logout issue

### ISSUE THREAD

**Issue by tomaulin** [KentorIT/authservices#699]
I've posted this issue before but did not get any response. to be able achieve single logout with Okta IDP,
I've generated x509 cert using openssl.

After i replace private key in <serviceCertificate> section with pfx file, it throws crypto error and would not allow application to proceed further.

can you point us on how do i generate x509 cert using crypto algorithm in .Net? or how do i export public key from you Tests.pfx file?

I really appreciate your early response on this.

**Comment by AndersAbel** [comment]
Please don't open duplicate issues. Questions on the issue tracker are answered when we have time.

If you want support with guaranteed response times, we do offer a commercial support option. Please mail me at anders.abel@kentor.se if you are interested in that.
