### ISSUE TITLE
How to handle an Identity Provider that uses transient NameID

### ISSUE THREAD

**Issue by olavaukan** [KentorIT/authservices#700]
I'm trying to use the Kentor.AuthServices OWIN middleware in my application and after developing for a while agains the Kentor StubIdP I've now moved on to the Test-version of the actual Identity Provider that my application will be using: https://idp-test.feide.no/simplesaml/saml2/idp/metadata.php.

This IdP is doing something a bit different in that it uses transient NameID:

```
<md:NameIDFormat>
	urn:oasis:names:tc:SAML:2.0:nameid-format:transient
</md:NameIDFormat>
```
The problem with this is that the NameID is used as the ASP.Net Identity ProviderKey that keeps track of which external identity belong to which internal identity, and this means that every time the user logs in he is treated as if this is the first login and is asked to register his email.

This can be observed in the sample SampleOwinApplication application:

- Build and launch application
- Log in with KentorAuthServices, using the Feide IdP and providing credentials for a test user
- In the ExternalLoginCallback method of the AccountContoller we get a 'loginInfo' object by calling AuthenticationManager.GetExternalLoginInfoAsync();
- It then attempts to sign in the user by calling SignInManager.ExternalSignInAsync(loginInfo, isPersistent: false); but this results in SignInStatus.Failure because the user has not logged in before and does not have a corresponding internal identity.
- The code then redirects to ExternalLoginConfirmation to promt for an email.
- It then creates a 'user' object of type ApplicationUser, passing in the email and calling UserManager.CreateAsync(user);
- It then adds an internal user by calling UserManager.AddLoginAsync(user.Id, info.Login);
- Finally it logs in the user by calling SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
- Log out
- Log in again with KentorAuthServices, using the Feide IdP and providing credentials for the same test user
- In the ExternalLoginCallback method of the AccountContoller we get a 'loginInfo' object by calling AuthenticationManager.GetExternalLoginInfoAsync();
- It then attempts to sign in the user by calling SignInManager.ExternalSignInAsync(loginInfo, isPersistent: false); but this results in SignInStatus.Failure because the loginInfo.Login.ProviderKey is different from what it was the first time the user logged in.

So my question is how do I handle this? The ProviderKey somehow ends up in the claim 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier' which seems to be tied to the other "automagic" claim 'http://kentor.se/AuthServices/LogoutNameIdentifier'. I'm assuming these two are connected and need to stay in sync, so how do I go about connecting the second login of the same external identity to the internal identity created on the first login?

**Comment by AndersAbel** [comment]
The "magic" LogoutNameIdentifier claim keeps track of the information needed to perform a logout. It is automatically constructed when the incoming SAML response is processed. As long as you don't touch it, logout should work. The reason it's kept separate is to enable scenarios like this, where the provided NameIdentifier doesn't work as a key for the user in the application.

Using the NameIdentifier claim of the incoming identity is hard coded into ASP.Net Identity:

````
var idClaim = result.Identity.FindFirst(ClaimTypes.NameIdentifier);
````

So what you need to do is to change the NameIdentifier Claim into something that is persistent across sign ins. Is there any other attribute such as an e-mail address that you can use? Or can you persuade the Idp folks to configure the Idp to use a Persistent name identifier instead?

To swap out the NameIdentifier Claim, hook the `AcsCommandResult` created notification. In there you can modify the identity before it is returned out of AuthServices. Just remember to keep the LogoutNameidentifier claim intact as that is needed for single logout.

**Comment by olavaukan** [comment]
Thanks for the help so far, but it seems like the AcsCommandResultCreated method is called too late, or maybe I'm doing something wrong here. I've manipulated the identity object and added a couple of claims, but the ExternalLoginInfo object returned by AuthenticationManager.GetExternalLoginInfoAsync() in the AccountController does not seem to reflect these changes. I'm using the following code:

```
private static KentorAuthServicesAuthenticationOptions CreateAuthServicesOptions()
{
    var spOptions = CreateServiceProviderOptions();
    var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
    {
        SPOptions = spOptions,
        Notifications = {
            AcsCommandResultCreated = (cr, r) =>
            {
                if (r.Status == Kentor.AuthServices.Saml2P.Saml2StatusCode.Success)
                {
                    var identity = cr.Principal.Identity as ClaimsIdentity;
                    if (identity != null)
                    {
                        var nameIdClaim = identity.Claims.FirstOrDefault(c => c.Type.Equals(ClaimTypes.NameIdentifier, StringComparison.OrdinalIgnoreCase));
                        var nameClaim = identity.Claims.FirstOrDefault(c => c.Type.Equals(Business.Configuration.FeideServiceProviderNameClaim, StringComparison.OrdinalIgnoreCase));
                        if (nameIdClaim != null && nameClaim != null)
                        {
                            identity.RemoveClaim(nameIdClaim);
                            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, nameClaim.Value));
                            identity.AddClaim(new Claim(ClaimTypes.Name, nameClaim.Value));
                        }

                        var emailClaim = identity.Claims.FirstOrDefault(c => c.Type.Equals(Business.Configuration.FeideServiceProviderEmailClaim, StringComparison.OrdinalIgnoreCase));
                        if (emailClaim != null)
                        {
                            identity.AddClaim(new Claim(ClaimTypes.Email, emailClaim.Value));
                        }
                    }
                }
            }
        }
    };

    authServicesOptions.IdentityProviders.Add(new IdentityProvider(new EntityId(Business.Configuration.FeideIdentityProviderEntityId), spOptions)
    {
        AllowUnsolicitedAuthnResponse = true,
        Binding = Saml2BindingType.HttpRedirect,
        MetadataLocation = Business.Configuration.FeideIdentityProviderMetadataUrl,
        LoadMetadata = true                
    });

    return authServicesOptions;
}
```

Any tips for what I might be doing wrong here?

**Comment by olavaukan** [comment]
I ended up handling this in the Authenticate method of the ApplicationClaimsAuthenticationManager and swapping the name identifier claim with a new claim using the username as the value.

```
var oldNameIdClaim = externalIdentity.Claims.FirstOrDefault(c => c.Type.Equals(ClaimTypes.NameIdentifier, StringComparison.OrdinalIgnoreCase));
var newNameIdClaim = externalIdentity.Claims.FirstOrDefault(c => c.Type.Equals(Business.Models.AppSettings.FeideServiceProviderNameIdentifierClaim, StringComparison.OrdinalIgnoreCase));
if (oldNameIdClaim != null && newNameIdClaim != null)
{
    externalIdentity.RemoveClaim(oldNameIdClaim);
    externalIdentity.AddClaim(new Claim(ClaimTypes.NameIdentifier, newNameIdClaim.Value));
}

```
I hooked up the ApplicationClaimsAuthenticationManager from the SPOptions object:

`spOptions.SystemIdentityModelIdentityConfiguration.ClaimsAuthenticationManager = new ApplicationClaimsAuthenticationManager();`

Now in the ExternalLoginCallback method of the AccountController class, when calling AuthenticationManager.GetExternalLoginInfoAsync() the returned ExternalLoginInfo object has the username as the value for ExternalLoginInfo.Login.ProviderKey instead of the transient name identifier value from before. 

Only weird issue I had was that messing with the name identifier claim seems to cause the IdP EntityID to be replaced with 'LOCAL AUTHORITY' in ExternalLoginInfo.Login.LoginProvider, so I manually set this value back to the EntityID of the IdP I'm using.

Thanks for your help! =)

**Comment by fanc-mso** [comment]
@olavaukan Thanks for posting the solution, helped me a great deal.

Regarding the entity ID being set to LOCAL AUTHORITY, you need to pass the issuer in the constructor of Claim if you want to set it to something else.

I altered your code like this to use the same issuer as the original nameid claim:

`externalIdentity.AddClaim(new Claim(ClaimTypes.NameIdentifier, newNameIdClaim.Value, null, oldNameIdClaim.Issuer));`

**Comment by amisial** [comment]
@olavaukan and @fanc-mso, I know that I'm a year late but I want to know where would do all of this in an ASP.NET Core 2 application because I'm having the same issue

**Comment by AndersAbel** [comment]
@amisial Override the AcsCommandResultCreated notification and update the generated ClaimsPrincipal. Replace the NameIdentifier clame that is set to the transient NameId with a proper persistent value from one of the other attributes.

**Comment by amisial** [comment]
Do I do that in the Startup.cs file or somewhere else?

**Comment by AndersAbel** [comment]
@amisial It's part of the options, so yes, probably in your startup.
