### ISSUE TITLE
The signing algorithm http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 is weaker than the minimum accepted 

### ISSUE THREAD

**Issue by GaurangPoolCar** [KentorIT/authservices#703]
I am having issue with following:
Exception message: The signing algorithm http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 is weaker than the minimum accepted http://www.w3.org/2000/09/xmldsig#rsa-sha1.
   at Kentor.AuthServices.XmlHelpers.ValidateSignatureMethodStrength(String minIncomingSignatureAlgorithm

I read that this issue has been resolved in version 0.21, but it seems that it is not fixed yet. I am currently using version 0.21

Any idea on this?

**Comment by explunit** [comment]
That message does seem wrong. Just curious though, what version of .Net are you running? If it is less than 4.6.2, have you called `Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures()` on startup?

**Comment by GaurangPoolCar** [comment]
Yes, I am using .net version 4.5 and called Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures() on Application Start.

**Comment by explunit** [comment]
Version v0.21.0 or v0.21.1?

**Comment by GaurangPoolCar** [comment]
0.21.1

**Comment by GaurangPoolCar** [comment]
This is bit wired, It is working fine for client who is using Shibboleth , but not working with NetScaler. 
 
For NetScaler, when I move this code to Startup, I am getting RelayState related error( Netscaler  read RelayState value and use this as the location header in the 302 response it sends.)

**Comment by explunit** [comment]
And both of these clients are using SHA256 as the signing algorithm?

**Comment by GaurangPoolCar** [comment]
Yes, both clients are using SHA256.

**Comment by GaurangPoolCar** [comment]
This issue has been resolved, there was some issue with NetScalar.

Thanks @explunit for your help regarding this.
