### ISSUE TITLE
IDP initiated SSO Saml2p response with AttributeStatement

### ISSUE THREAD

**Issue by jsnb** [KentorIT/authservices#704]
I need to make an IDP initiated SAML2 SSO POST request (http://saml.xml.org/wiki/idp-initiated-single-sign-on-post-binding) which requires that I make a signed xml SAML2P response that contains an assertion with custom fields in the AttributeStatement. Is this supported with AuthServices? I am testing out creating a response in a console app and I can create a response based on the code I saw in the unit tests:

            var issuer = new EntityId("http://myentity.com");
            var identity = new ClaimsIdentity(new Claim[] 
            {
                new Claim(ClaimTypes.NameIdentifier, "JohnDoe"),
            });
            var response = new Saml2Response(issuer, null, null, null, identity);

But if I try to create claims with a custom type (label) like this: new Claim("OrgId", "5555555") I get a System.InvalidOperationException when calling response.ToXml().

I would have expected the following nested in the <Assertion>
  <saml:AttributeStatement>
    <saml:Attribute Name="OrgId">
      <saml:AttributeValue xsi:type="xs:string" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">5555555</saml:AttributeValue>
    </saml:Attribute>
  </saml:AttributeStatement>

Is this supported?

(sorry if this is out of line to ask in the issue board - i saw other questions in here)

**Comment by AndersAbel** [comment]
It's perfectly fine to ask questions like that here.

Yes, posting an outbound SamlResponse is supported. Check the StubIdp source for an example of how it's done.
