### ISSUE TITLE
Kentor not setting System.Web.HttpContext.Current.User.Identity.Name

### ISSUE THREAD

**Issue by inrakshworld** [KentorIT/authservices#705]
We are using kentor + okta. Before using kentor my website is working fine. I'm able access all the pages on website after okta login.

But after integrating kentor my System.Web.HttpContext.Current.User.Identity.Name not setting. It is always blank. Hence my Membership & Role provider is not working due to above value is blank.

Also if I get the username from claims then few pages don't load and goes into loop.

**Comment by rharting** [comment]
I am seeing this same issue.  HttpContext.Current.User.Identity.IsAuthenticated is true, but Name is null. Is there any fix for this?

**Comment by AndersAbel** [comment]
The `User.Identity.Name` property returns the value of the claim configured as `NameClaimType` on the `ClaimsIdentity`. Normally it has a standard value of `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name`. If there is no claim of that type the Name property will return blank. With AuthServices, it will only be automatically populated if there is an attribute with the right type in the incoming assertion.

**Comment by inrakshworld** [comment]
Hi,

Thanks for youe email.

Yes. I found the solution by adding additional claim.

Regards,
Rakesh Lad

**Comment by abilash1205** [comment]
where to added claim

**Comment by abilash1205** [comment]
public ActionResult Index()
        {

            var identity = System.Web.HttpContext.Current.User.Identity as ClaimsIdentity;
            return View();
        }

**Comment by inrakshworld** [comment]
I added in Okta App configuration under Attribute Statements section.

[image: Inline image 1]

**Comment by abilash1205** [comment]
i added but till getting null

![image](https://cloud.githubusercontent.com/assets/19603112/25946581/67b0d412-3669-11e7-9e16-87cc8058b6b0.png)

**Comment by abilash1205** [comment]
hai inrakshworld you have any documentation for kentor + okta mvc, can you please  send me it will help so much for my application

**Comment by rharting** [comment]
Thank you again AndersAbel! 
@abilash1205, I am not working with Okta, but given your screenshot, add the Name "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" and give it whatever Value Okta calls username, and it should work.
