### ISSUE TITLE
Help with IIS

### ISSUE THREAD

**Issue by rharting** [KentorIT/authservices#709]
I have built and setup the Kentor Sample Application on IIS. I am able to get into the initial page, but when I click on SignIn:
"HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly." The URL being /KentorSamlSample/AuthServices/SignIn/

This same code works on IIS Express when run on my development server (running as debug). I use same web.config file and everything.  It seems like I'm missing some component on the server I publish to, or that I don't have IIS 7 on the server I published set up correctly.

(just as a test: I created AuthServices and SignIn sub folder, and that bypassed that issue, but now I have a 403 error, "Forbidden".  (I don't think manually creating the "AuthServices/SignIn" folder is necessary?))
Thank for any hints.

**Comment by AndersAbel** [comment]
You shouldn't need to create the folders.

Try enabling the RAMMFAR setting in web.config (RAMFAR=RunAllManagedModulesForAllRequests). Without it IIS sometimes does not call the HttpModule that handles those URLs.

**Comment by rharting** [comment]
Thank you for your reply AndersAbel. I tried this and still have the same issue. This is what I added to web.config 
`<system.webServer>
    <validation validateIntegratedModeConfiguration="false" />
    <modules runAllManagedModulesForAllRequests="true">      
      <add name="SessionAuthenticationModule" type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
      <add name="Saml2AuthenticationModule" type="Kentor.AuthServices.HttpModule.Saml2AuthenticationModule, Kentor.AuthServices.HttpModule" />
    </modules>
  </system.webServer>`
I am now wondering if something with defaults on Server or IIS versions. On my development server, I have IIS 8.5 (I was incorrect about IIS Express) on Server 2012. My publish server is IIS 7.5 on Server 2008 R2. Both have .NET Framework 4.6.2 installed. I can't do anything to update versions, so I wonder if something different with default setup of the two machines.

**Comment by AndersAbel** [comment]
Looks like some debugging is needed on a Win 2008 R2 machine. I can do that as a consultancy service, please mail me at anders.abel@kentor.se if that's interesting. Here on the free issue tracker there's only time for quick answers that doesn't require more investigation.

**Comment by rharting** [comment]
I figured out a solution. As you have probably figured out, I am an IIS novice. But I discovered that many inherited modules in my website application in IIS were missing compared to the one that worked. No "managed" modules were not there since I was using classic app pool. So I switched to the integrated app pool on IIS and now it works. Thanks Anders, your post sent me on the right track.

**Comment by AndersAbel** [comment]
Thanks for reporting back on the solution so that others with the same issue can find the info.
