### ISSUE TITLE
Open redirect issue partially still applies

### ISSUE THREAD

**Issue by doormalena** [KentorIT/authservices#710]
Take the following URL and it's blocked since v0.20.0

> https://<app>/AuthServices/SignIn?ReturnUrl=http://google.com

However the following still leads to a redirection:

> https://<app>/AuthServices/SignIn?ReturnUrl=//google.com

**Comment by AndersAbel** [comment]
That's the issue that was fixed as #677. Have you tried v0.21.2?

And please don't report security issues on the public issue tracker but via mail.

**Comment by doormalena** [comment]
Will do next time Anders. 

I've just updated v0.21.1 to v0.21.2 and retested this. Issue is fixed. Thnx.
