### ISSUE TITLE
GlobalEnableSha256XmlSignatures() Breaks SHA1

### ISSUE THREAD

**Issue by gibbygano** [KentorIT/authservices#715]
Just posting this here as requested:

When  **Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures()** is added
to Global.asax, it breaks SHA1. It actually creates the same error that adding it was meant to stop, though I suppose it's actually an accurate error this time. Current solution when dealing with actual SHA1 signing certificates is to simple remove the line from Global.asax.

**Comment by AndersAbel** [comment]
What .NET Framework version are you running on when you see this?

**Comment by gibbygano** [comment]
4.5

**Comment by AndersAbel** [comment]
Thanks, I need to create a dev machine with 4.5 to test this myself.

**Comment by explunit** [comment]
We encountered this today on .Net 4.6.1. `GlobalEnableSha256XmlSignatures()` makes AuthServices default to requiring SHA-256 unless you specify SHA1 in your configuration. So "breaks SHA1" may be too strong a description, but somewhat accurate if your existing identity providers were already using that algorithm.

Maybe the release notes for v0.20.0 should emphasize this a bit more?

**Comment by gibbygano** [comment]
Yeah, I probably should of said it disables compatibility with SHA1. I think the bigger concern is that our client was SHA1 :X. I know root is trusted by identity instead of by hash, but c'mon. It's just a better idea to bump up to SHA2.

**Comment by AndersAbel** [comment]
That's by design. SHA1 shouldn't be used any more as soon as SHA256 is enabled. But there is a setting for minimum trust level that can be set to still allow SHA1.
