### ISSUE TITLE
Given key not present in dictionary

### ISSUE THREAD

**Issue by rharting** [KentorIT/authservices#719]
Hello, I have almost managed to make the Kentor SampleApplication work with our chosen Identity Provider. However, when our Idp SAML POST comes in, I receive an error in my browser,  "System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary"
`[KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Generic.Dictionary 2.get_Item(TKey key) +14331515
   Kentor.AuthServices.Configuration.IdentityProviderDictionary.get_Item(EntityId entityId) in C:\Visual Studio Projects\KentorSAML\authservices-master\Kentor.AuthServices\Configuration\IdentityProviderDictionary.cs:46

[KeyNotFoundException: No Idp with entity id "****" found.]
`
I am most likely missing something during setup of web.config. What do you recommend that I check? Thanks

**Comment by AndersAbel** [comment]
You've not added the Identity Provider to the config. Or if you did, you've got the wrong EntityId of the IdentityProvider. The **** that you've masked out contains the EntityId that the Idp actually uses. That's what should go into the config.

**Comment by rharting** [comment]
Thank you AndersAbel! I had the EntityID set to the URL of the Metadata, but the Issuer URL in the POST was different. So I made use of the metadataLocation attribute to specify metadata URL and it worked!
