### ISSUE TITLE
System.Web.HttpContext.Current.User.Identity.Name

### ISSUE THREAD

**Issue by abilash1205** [KentorIT/authservices#722]
i added but till getting null

https://cloud.githubusercontent.com/assets/19603112/25946581/67b0d412-3669-11e7-9e16-87cc8058b6b0.png

**Comment by AndersAbel** [comment]
Stop commenting all over and opening new issues. You've already commented on #705 which is this exact question. If you need further assistance than what is available there, it's nothing we can do for free on the issue tracker. Mail me if you want consultancy services.
