### ISSUE TITLE
Implement ECP with Kentor

### ISSUE THREAD

**Issue by hungleon2112** [KentorIT/authservices#726]
Hello!

Does Kentor library support for implement ECP? I don't find any example.

**Comment by AndersAbel** [comment]
No, it doesn't implement ECP at the moment. It could of course be extended to do that and we are always open to adding features as sponsored work. Or if you prefer you can add it yourself and submit a pull request.

**Comment by hungleon2112** [comment]
Thank you @AndersAbel :)
