### ISSUE TITLE
Remove Cookie from IDP when Single Log Out

### ISSUE THREAD

**Issue by hungleon2112** [KentorIT/authservices#727]
Hi @AndersAbel ,

I'm implementing a website using Kentor to interact with IDP (OKTA)

I already enabled the Single Log Out on OKTA, when I Log Out, it's work, but the Cookie still there, so when I go back to Okta Login page, it Login automatically.

Can you advice?
Thank you!!

**Comment by AndersAbel** [comment]
What cookie is still there?

Did you configure AuthServices for single logout? You need to add a servicecertificate to enable the logout endpoints in AuthServices.

**Comment by hungleon2112** [comment]
Hi @AndersAbel ,

Is it a X509 Certificate??

**Comment by AndersAbel** [comment]
Yes.

**Comment by hungleon2112** [comment]
Thank you very much!! ^_^
