### ISSUE TITLE
ReturnUrl issue in MVC application

### ISSUE THREAD

**Issue by olivierPflieger** [KentorIT/authservices#730]
Hi,

First, thanks for your great job on this API :)

I have a problem with the returnUrl parameter in my MVC application. 
(Or may be a lack of understanding).

So i have downloaded the sampleMvcApplication to check if the problem is the same,  and finally i have easily reproduced the problem.

By default, the Home/Index method (in the sampleMvcApplication ) is accessible in anonymous way.
So, on first start, MVC routes to the _Index_ view, and then, i can click on the Secure button. It works like a charm.

But, what i need in my application, is an automatic redirect when the user isn't authenticated without having to navigate through the Index view. For that purpose, i just have add an [Authorize] attribute on the Home/Index method and set a returnUrl in the web.config.

![image](https://cloud.githubusercontent.com/assets/9209194/26204054/e28fa220-3bdd-11e7-9eab-db7008bffb71.png)

On first start, the MVC automatically redirects on the SSO provider (thanks to Authorize attribute), but the returnUrl doesn't seems to be taking in account. The return is always done on the domain (in this case, mySite).

Here you can see the filder log and notice the returnUrl parameter :

![image](https://cloud.githubusercontent.com/assets/9209194/26204098/0b86b07e-3bde-11e7-8ecb-cbbbc43e0a06.png)

What do you think about that ?

Thank you very much :)

**Comment by explunit** [comment]
The ReturnUrl in the web.config is only used if there was no ReturnUrl generated during the authentication flow, so this is expected that it will return to the original path that triggered the authentication flow.
