### ISSUE TITLE
Azure AD - "The signature verified correctly with the key contained in the signature, but that key is not trusted."

### ISSUE THREAD

**Issue by augustg** [KentorIT/authservices#735]
Using azure as IdP i always get an exception saying "The signature verified correctly with the key contained in the signature, but that key is not trusted.".

I did some digging and this is what I've found so far:
The exception is being thrown from VerifySignature in XmlHelpers.cs.
The metadata (which is automatically downloaded) contains 3 signing certificates and one certificate within the signature itself. The latter cert is the exact same as the first of the 3 signing certificates.
In VerifySignature() the 3 signing certs are checked first and they all fail and the method falls through to checking against the certificate within the signature. Which partly succeeds, but ultimately fails because the certificate is not trusted.
I'm making the assumption that i should not have to add the certificate to trusted root certs in windows.

Another odd thing I noticed is that the asymmetric algorithm used when checking the 3 signing certs is hardcoded to SignedXml.XmlDsigRSASHA1Url. However checking the metadata reveals that the signature method used is "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256".
I figured this was the problem so i just passed in "signedXml.Signature.SignedInfo.SignatureMethod" to GetAsymmetricAlgorithm but it did not solve the problem. Signature check still failed.
I dont have enough knowledge about saml to know how it's supposed to work and my outstanding questions are:

Is my reasoning above correct? Should we check the signature method and choose an algorithm based on that?
The last check is "signedXml.CheckSignature(containedKey, true)" which explicitly does not validate the certificate. However when the exception is thrown it assumes the certificate is invalid. Am I correct in assuming that the 3 signing certs decides what keys are trusted.

**Comment by AndersAbel** [comment]
Something odd is definitely going on here.

You are right in that you should not have to add the certificate to the trusted root certs. When a SAML2 message is received, it should validate against one of the keys found in the Idp metadata, because the keys from the metadata is what we trust.

That final check against the certificate contained in the signature is just a debug aid, to show whether the content has been tampered with or whether it is signed by a key not found in metadata.

Can you check if the certificate in the signature matches any of those from metadata?

**Comment by augustg** [comment]
Yes, the first of the signing certs in the metadata (specifically under the node IDPSSODescriptor) matches the cert in the signature.

**Comment by AndersAbel** [comment]
Would you mind sending the actual metadata and the SAMLResponse to me in a mail (anders@abel.nu) so that I can look at them?

**Comment by augustg** [comment]
Email sent!

**Comment by AndersAbel** [comment]
Checked the data I received via e-mail and none of the certificates in the metadata match the certificate of signature of the SamlResponse. So AuthServices is giving the right error message.

**Comment by nguidoux** [comment]
@augustg I know this was closed over 2 years ago, but wondering if you figured out what the root cause of this issue was? I'm attempting to use Azure AD as the IDP and running into the same problem.

**Comment by AndersAbel** [comment]
@nguidoux In the case above, the SAML2 library was incorrectly configured.

**Comment by nguidoux** [comment]
@AndersAbel thanks for the response! We got it correctly configured and working now.

**Comment by augustg** [comment]
Now I'm curious if you know more about this than i do.
I dont remember the SAML2 library being incorrectly configured. The metadata from azure just didnt have the certificates required.
We ended up downloading the metadata manually (there is a button hidden somewhere in the Azure portal) and using that xml worked. But then anytime certs change you have to do this manually again. So not an ideal solution.

@nguidoux How did you resolve it?

**Comment by Narshe1412** [comment]
@nguidoux @augustg Any chance you can share how did you solved it?

Thanks!

**Comment by AndersAbel** [comment]
@augustg @Narshe1412 In the case of Azure AD. Configure the library with a MetadataLocation to the Azure AD metadata location. The library will automatically download new metadata with the new keys periodically.
