### ISSUE TITLE
Authenticated User without needed Role goes into Loop

### ISSUE THREAD

**Issue by GerwinNL** [KentorIT/authservices#740]
Hello.

I'm currently implementing Okta in some of our companies application. We have succesfully used your Library to do this in MVC 4/5 Website's. However ..
We also like to enable SAML on one of our legacy application thats using Forms Authentication and the old aspnet providers. We managed te get everything up and running except 1 part.

When a user is Authenticated, but we demand a certain Role/Claim, the user is then redirected to Okta for re-validation. When the user comes back, the role still is not there, so the application calls the Authentication module again. U can see where this is  going. In MVC we added a handler to the controllers, this works like a charm. On the HttpModule we dont have a event /handler like that. 

Is this something we can handle with some extra code or do we need another implementation ?

TIA:

Gerwin

BTW: We use this on MVC to prevent the Looping ...

     public sealed class LogOnAuthorize : AuthorizeAttribute
     {
       protected override void HandleUnauthorizedRequest(AuthorizationContext filterContext)
        {
            if (filterContext.HttpContext.Request.IsAuthenticated)
            {
                filterContext.Result = new System.Web.Mvc.HttpStatusCodeResult((int)System.Net.HttpStatusCode.Forbidden);
                return;
            }
            else
            {
                base.HandleUnauthorizedRequest(filterContext);
            }
        }
    }

**Comment by AndersAbel** [comment]
This is not an AuthServices specific question, but a general problem with how the forms auth works. When access is denied it redirects to the specified login page, which if you have specified `~/AuthServices/SignIn` directly kicks of a SAML flow.

I'd suggest a workaround by setting the login page to a custom page, that contains something like the above code and redirects to `~/AuthServices/SignIn` if needed.
