### ISSUE TITLE
Can't run sample app (MVC).  Provided certificate is not valid for encryption/decryption

### ISSUE THREAD

**Issue by dwhitmore** [KentorIT/authservices#742]
This is perhaps more of a question.

I clone the project.
I install the .pfx and .cer through MMC as an admin to the local computer.
Run the app

No matter what I try i keep getting this error.  Any chance I just misunderstood something and missed a step?  

If it helps, trying different combinations, I've install both in Personal->Certificates and the .cer also in Trusted Root Certification Authority

**Comment by explunit** [comment]
I'm not sure what version you are running, but the latest version has adding some more detail to that error message:
```Provided certificate is not valid for encryption/decryption. There may be insufficient permissions to its private key in the windows certificate store or the certificate itself may not have the correct purposes. If you only want to use it for signing, set the Use property to Signing (CertificateUse.Signing).```

It sounds like in your case the problem is likely to be private key permissions in the windows certificate store.

**Comment by dwhitmore** [comment]
After seeing that it worked when I ran VS in 'Admin' mode, I gave the regular user 'Full Control' to the directory 'C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys' per a Stack Overfow issue.
