### ISSUE TITLE
Error load config when virtual directory

### ISSUE THREAD

**Issue by T4YoO** [KentorIT/authservices#744]
Hello, 

In our project we use a virtual directory with IIS Express:
Project Url : http://localhost:56000/Website

We have an exception when calling `new KentorAuthServicesAuthenticationOptions(true)`

> "The type initializer for 'Kentor.AuthServices.Configuration.KentorAuthServicesSection' threw an exception."
InnerException:
> The entry 'https://sts.windows.net/5da355b1-xxxx-xxxx-xxxx-xxxxxxxx/' has already been added. (C:\\Workspaces\\xxxx\\WebSite\\web.config line 96

We have no problem to load the config with no virtual directory:
Project Url : http://localhost:56000

Thank you

**Comment by AndersAbel** [comment]
Looks like something is wrong in how your web.configs are setup, have never heard of this type of exception before.

**Comment by T4YoO** [comment]
I tested in an empty mvc 5 project

I have the same exception with a virtual directory.
Even if I just call 
`ConfigurationManager.GetSection("kentor.authServices") as KentorAuthServicesSection`

In web.config I only have:

```
<configSections>
<section name="system.identityModel"  ...
<section name="system.identityModel.services"   ...
<section name="kentor.authServices"   ...
</configSections>
```


```
<kentor.authServices entityId="http://localhost:49746/WebSite/AuthServices" returnUrl="http://localhost:49746/WebSite">
    <identityProviders>
       <add entityId="https://sts.windows.net/xxxxxxx/" 
           signOnUrl="https://login.microsoftonline.com/xxxxxxxxxx/saml2" 
           logoutUrl="https://login.microsoftonline.com/xxxxxxxx/saml2" 
           allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate fileName="~/App_Data/AzureAD.crt" />
      </add>
    </identityProviders>

    <serviceCertificates>
      <add fileName="~/App_Data/Kentor.AuthServices.Tests.pfx" />
    </serviceCertificates>

  </kentor.authServices>
```

```
<system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" name="ApplicationAuth" />
    </federationConfiguration>
  </system.identityModel.services>
```

```
<system.identityModel>
    <identityConfiguration>
      <audienceUris mode="Never">
      </audienceUris>
    </identityConfiguration>
  </system.identityModel>
```

And in Startup.ConfigureAuth:
`app.UseKentorAuthServicesAuthentication(CreateAuthServicesOptions());`

```
private static KentorAuthServicesAuthenticationOptions CreateAuthServicesOptions()
{
    var authServicesSection = ConfigurationManager.GetSection("kentor.authServices") as KentorAuthServicesSection;
    var authServicesOptions = new KentorAuthServicesAuthenticationOptions(true);
    return authServicesOptions;
 }
```

**Comment by explunit** [comment]
I would guess this is more about IIS Express doing odd things with physical path than it is about AuthServices. For example: https://stackoverflow.com/questions/18506826/iis-express-cannot-add-duplicate-collection-entry-of-type-add-with-unique-key
