### ISSUE TITLE
ADFS issue

### ISSUE THREAD

**Issue by olivierPflieger** [KentorIT/authservices#755]
Hi,

I'm facing an issue with an external ADFS Provider. 
In fact, I'm correctly redirected on the ADFS url, but get an error before having the login form (so i can not enter my credential).

Here is my config file :

```
<kentor.authServices 
    entityId="https://localhost:44388/AuthServices" returnUrl="https://localhost:44388">
```

```
<add entityId=" ... "
        signOnUrl=" ... "
         logoutUrl=" ... "
         allowUnsolicitedAuthnResponse="true" binding="HttpPost">
        <signingCertificate fileName="~/App_Data/SSO/....crt" />
   </add>
```

</kentor.authServices>

The message is the following : 
"The requested relying party trust 'https://localhost:44388/AuthServices' is unspecified or unsupported. If a relying party trust was specified, it is possible that you do not have permission to access the trust relying party. Contact your administrator for details."

I have no problem when i'm testing on Azur and OneLogin.

The IT admin tells me that the issue is on my side (may be a problem with 'localhost'.

Have you already encouter this issue ? 

What do you think about that ?

Thanks very much for your reply.

**Comment by explunit** [comment]
This ADFS-specific question probably belongs on Stackoverflow rather than this issue board, but my guess is that your EntityId does not match (including case-sensitive) what is configured on the ADFS side in the relying party trust.

**Comment by olivierPflieger** [comment]
Hi,

You right. Sorry for posting here.  But i'm struggling with this bug ...

The entityID is correct. I copy/past it from the metada file...  

```
<EntityDescriptor ID=" ... " 
     entityID=" **the entityID url**"
```

Is it correct ?

**Comment by explunit** [comment]
I meant **your** entity id: `<kentor.authServices entityId="https://localhost:44388/AuthServices"`

ADFS needs to have this configured as a relying party trust, either by reading your metadata or by manual configuration of this entity and the allowed endpoint URLs.

**Comment by olivierPflieger** [comment]
The IT admin said that he has correctif configured this part.

Are you sure that localhost is not the problem ?

Last question before closing the issue.

How Can i generate a metadata file to give to the admin ?

Ty

**Comment by explunit** [comment]
Yes I'm sure that it's possible to have a sample application work with ADFS using a localhost address.

The service provider metadata is available by default at the /AuthServices path in your application.
