### ISSUE TITLE
how can i get access to Service Provider from asp.net client application?

### ISSUE THREAD

**Issue by humbertojacobm** [KentorIT/authservices#756]
Hi, I gotten run one asp.net application like as SP with Kentor, but when I am trying to run another asp.net application, this can not have relationship with the SP, how can I do that?

**Comment by explunit** [comment]
The SAML model is that you have multiple Service Providers/Relying Parties associated with an IDP. You do not associate additional applications with the same SP. Each one would become their own SP.
