### ISSUE TITLE
Federation Metadata 

### ISSUE THREAD

**Issue by scriptmonkey69** [KentorIT/authservices#767]
If I am loading the metadata from the federation via a url, and this metadata includes the encryption and signing certificates for communication, why do I need to have the certificate installed on my client computer?

**Comment by explunit** [comment]
You do not need to have **their** certificate installed on your client, but if you are using encrypted assertions or signing outbound messages then you need to have **your** certificate installed because you are the only one that should have its private key.

**Comment by scriptmonkey69** [comment]
So in the MVC example web.config what is the signing certificate inside the
identityprovider?

**Comment by scriptmonkey69** [comment]
My context is, I work for a large international bank and we are using
kentor authservices to integrate our MVC .net application into the adfs.

Regards

**Comment by explunit** [comment]
That example is just one way of doing it (some IDPs don't support the metadata standard and for those you have the option of manually receiving the public key and having it locally).

**Comment by scriptmonkey69** [comment]
Cheers, keep up the good work.
