### ISSUE TITLE
Connection forcibly closed 

### ISSUE THREAD

**Issue by scriptmonkey69** [KentorIT/authservices#768]
I have been battling with AuthServices for 2 days, and the error has been 
'Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.'

I then tried my configuration in the SampleMvcApplication, with the same result, this prompted me to check the exact cause of this error and this resulted in me adding the following line of code 

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
before the WebClient creation in the MetadataLoader.Load function.

The IT department in our company have completely removed SSL2 and SSL3 support, and only support TLS.

My question is:

Is there anyway of specifying to the MetadataLoader that it must use TLS?

**Comment by scriptmonkey69** [comment]
Fixed it by just adding the line of code in the StartUp class. So no need to use an amended, non standard,  AuthServices library.

**Comment by explunit** [comment]
Thanks for reporting your findings here for others to benefit from.
