### ISSUE TITLE
ADFS SignOut problem and configuration without Web.config

### ISSUE THREAD

**Issue by Shiro013** [KentorIT/authservices#769]
Hi, I have two questions.
I've implemented the Auth with ADFS and MVC and its working.

First, Is there any way I can configure my application to work without the web.config sections? I wish to configure Kentor by code to leave my web.config as default, my applications need it. If there is a way, can you guys give me an example please?

Second, I have two applications working with the same ADFS server. When I log in with one, the second autenticates too as expected, but when I sign out from one, the second remains logged in. I check the cookies and the second one is not erasing the cookies from their path.

Thanks!

**Comment by explunit** [comment]
Regarding configuration, see this comment: https://github.com/KentorIT/authservices/issues/771#issuecomment-318852977

Regarding single logout, it is indeed hard to debug sometimes. A couple suggestions:
 1. See the conditions checked here https://github.com/KentorIT/authservices/blob/v0.21.1/Kentor.AuthServices/WebSSO/LogOutCommand.cs#L155-L170
 1. See the other [Troubleshooting](https://github.com/KentorIT/authservices#troubleshooting) suggestions, e.g. connecting a logger. Another example [here](https://stackoverflow.com/questions/45332533/kentor-authservices-and-log4net)
