### ISSUE TITLE
How to retrieve data from the ACS

### ISSUE THREAD

**Issue by anhhoangbui** [KentorIT/authservices#770]
Is there a way I can change the ACS Url in the metadata generated from ~/AuthServices to my own URL instead of ~AuthServices/ACS ?

The problem I have right now is that I need to read the POST coming from the ADFS. However, once the ADFS POST to the ACS, the ACS simply redirects me to my returnURL without the POST content so I would prefer if the ADFS POST directly to my own url.

**Comment by explunit** [comment]
I'm curious what processing you are trying to do on the ADFS POST. If you simply want to read the attributes in the SAML, those should be available as claims in the identity generated by AuthServices after successful validation.

**Comment by anhhoangbui** [comment]
I'm definitely out of my comfort zone when it comes to ASP .NET so I'm not sure how to get those attributes using claims. Is there any example I can take a look at? I tried googling but there seems to be more then 1 type of claims and I don't know which one is applicable to Kentor. My work space is limited to a Page_Load on the returnURL only.

**Comment by explunit** [comment]
See this controller and view in the MVC sample application:
https://github.com/KentorIT/authservices/blob/v0.21.2/SampleMvcApplication/Controllers/HomeController.cs#L18-L22
https://github.com/KentorIT/authservices/blob/v0.21.2/SampleMvcApplication/Views/Home/Secure.cshtml#L11-L14
