### ISSUE TITLE
SAML2:EncryptedAssertion support

### ISSUE THREAD

**Issue by gheeres** [KentorIT/authservices#78]
Interfacing with [Shibboleth IDP](https://shibboleth.net/).

```xml
<saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
</saml2:EncryptedAssertion>
```

**Comment by explunit** [comment]
I see there has been some progress toward supporting encrypted assertions. Is there anything I can do to help with this effort? E.g. It looks like #85 from @gheeres was close to being merge-able. Is there value in me picking up that code and modifying it to address the comments from @AndersAbel?

Or do we think the branch from @Raschmann is going to be moving toward a PR sometime soon?

**Comment by PoyaManouchehri** [comment]
We also really need this feature. Would be happy to help with anything to get that branch merged.

**Comment by AndersAbel** [comment]
I think that #85 is quite close to being possible to merge. Next step would be to pick up the discussion and answer my comment from June 11th 2014. As a start, please feel free to comment.

Another option is that you sponsor the development of the feature. Please mail me if that is of interest.

**Comment by PoyaManouchehri** [comment]
I did comment on that PR. Any thoughts?

**Comment by AndersAbel** [comment]
@PoyaManouchehri Sorry for not getting back to you. I've been extremely busy the last few weeks. I'll get back to you as soon as I have time.

**Comment by rdefreitas** [comment]
Looks like it still had a few merge conflicts. Do you need help getting this resolved?

**Comment by AndersAbel** [comment]
@rdefreitas Help getting this done would be appreciated.
