### ISSUE TITLE
Support SP AuthnRequest signing

### ISSUE THREAD

**Issue by simongustaf** [KentorIT/authservices#95]
Hi, this lib plugged in nicely in my app without any hassle (this is my first atempt with SAML and SSO). I just have one question, are you planning to add signing of the AuthnRequest (with the SP:s certificate)?

Great work guys!
/Simon

**Comment by cornem** [comment]
I'm looking for the same functionality, as we're trying to connect to an IdP that requires a signed AuthnRequest.

I'm going to give this a try myself, if you have not planned this issue yet.

**Comment by AndersAbel** [comment]
Nothing is planned from me on this currently.

If you make a try, please have a look at the comments in #123 and the work in #78 which probably contains some work on adding SP certificates to the configuration.

**Comment by AndersAbel** [comment]
Waiting for #355 to be completed first.
