### ISSUE TITLE
ValidateInResponseTo results in "The Saml2Response didn't pass validation" in a farm setup

### ISSUE THREAD

**Issue by doormalena** [KentorIT/authservices#98]
ValidateInResponseTo checks if the responseId was issued during a previous AuthN request. This responseid is cached in a static variable within PendingAuthnRequests. This variable however is different per node in a web farm. When a load balancer decides to route the returning request to a different node, the ValidateInResponseTo method is unable to find the responseId in it's PendingAuthnRequests cache. This results in  "The Saml2Response didn't pass validation" while the response is perfectly valid.

**Comment by martinjt** [comment]
@AndersAbel Could we simply create an interface to the PendingAuthnRequests, then use that in the code.  Then additionally, allow it to be overridden when the IdentityProvider object is created.  That would be a great start, and would allow people to create their own implementations until you've decided on yours.  Beyond that, it would allow a simple way to support both the old (application state) and new methods (cookie/redis)?

I can do that implementation and submit a pull request.  We want to use the library as is, without modification, so I'm happy to invest the time if you can give me some assurance that you will be able to review and merge within the next few weeks?  It should be a relatively minor change to just add the interface and make it public so it can be set, then set the default to the existing implementation?

Sidenote: using cookies would rely on the site supporting cookies, although it's not a problem for us, some folks might not like using them.  Are there any other dependencies on cookies that would make that point m00t?  I'm no security expert, but SAML authentication seems to be something that, unless done right, could be catastrophic, so allowing the user to choose the implementation of storing the replay stuff would be beneficial.

**Comment by martinjt** [comment]
@AndersAbel I've put together an outline of my thoughts on the interface in this commit:

https://github.com/martinjt/authservices/commit/eb332c5400c0a948c29da2ef27cccde745e4dff5

it needs cleaning up, but I think it provides a decent extensibility point.

**Comment by AndersAbel** [comment]
Adding an interface as the extensibility point is a good start. I don't think I'll have time to do the cookie-based solution for quite some time anyway.

When the cookie-based solution discussed above is completed, it can be added as another provider. It has some drawbacks, as the amount of data that need to be serialized can be quite large.

I briefly looked through the code and it looks like the right approach.

**Comment by akiander** [comment]
I created a pull request that restructures the PendingAuthnRequests data structure so that it is now an interface with the existing functionality as the default implementation. This should maintain backwards compatibility for existing consumers, but allow people like me to provide my own implementation that works in a web farm. See  [Pull 322](https://github.com/KentorIT/authservices/pull/322) for details

**Comment by akiander** [comment]
Let me know if you want to see any changes in [pull 322](https://github.com/KentorIT/authservices/issues/322) and I can try to accomplish that this week. I think it will be important for this component to support the ability to operate in a multiple web server environment.

**Comment by AndersAbel** [comment]
@jhoerr, I'm answering your comment from #326 here as that PR is now closed.

No, I can't give an ETA on the cookie based solution right now. Some Cookie-handling support code has been implemented as part of Single Logout. There's also a PR #235 that contains some interesting code using a binary formatter that can be used.

The problem for doing this is that none of my paying customers are running a farm setup, so this will have to be done in whatever spare time I have. If anyone is interested in sponsoring this to get it moved higher on the priority list, please drop me a mail.

**Comment by doormalena** [comment]
@AndersAbel
Dropped you an e-mail regarding implementation!
